### ISSUE TITLE
FOQUS does not seem to be running when the computer "sleeps"

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#1021]
I am running an optimization in FOQUS, and it seems that when my computer sleeps, FOQUS is not running.

Can you please let me know what I can do to have FOQUS run even if my computer sleeps?

Thank you very much for your help.

**Comment by ksbeattie** [comment]
Hey @fsoepyan, I don't think it's possible for any non-system level software to continue running while a computer is sleeping.

I think the only option would be to change your system settings to not sleep while you are running FOQUS (or anything else that needs to keep running).

I know there are tools out there to specifically prevent a system from sleeping, like a "mouse jiggler" that either simulates the moving or, or even literally moves, your mouse.  I've never used those myself, so I can't really advocate any of them, but I'd hope that your OS would provide some kind of "don't go to sleep" knob somewhere that you could turn on when running FOQUS, then turn it off when you aren't.

**Comment by fsoepyan** [comment]
Thank you @ksbeattie for the prompt response and suggestion.

I am currently running the optimization, with the sleep function in my computer disabled.

I will let you know what happens.

If this works, we can close the issue.

**Comment by fsoepyan** [comment]
@ksbeattie: I think your solution (to set the computer system setting so that the computer does not sleep) works, and therefore, I will close this issue. Thank you for your help.
