### ISSUE TITLE
FOQUS installation failures on Windows when creating desktop shortcut

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#1037]
Also a note on Windows in order to get the Foqus install (at least desktop shortcut) to actually work, I had to follow one of the more evil hacks suggested on this page https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api , namely copying the files `pywintypes38.dll` and `pythoncom38.dll` from the Conda environment Lib into my Windows system32 lib (!!!)

_Originally posted by @dangunter in https://github.com/CCSI-Toolset/FOQUS/issues/1014#issuecomment-1119946758_

**Comment by lbianchi-lbl** [comment]
The command to create the desktop shortcut is mentioned in the docs but we're not actually testing it in CI, so it might very well be that creating shortcuts hasn't worked in a while.

**Comment by lbianchi-lbl** [comment]
@dangunter any chance you still have access to the environment where you first encountered the error?

@Ryan-Hughes-8 reports that the command worked just fine on a fresh Windows installation so my guess is that there might be due to pip, Conda, Python version (and/or any combination of those).

**Comment by ksbeattie** [comment]
can't reproduce.
