### ISSUE TITLE
SimSinter Unable to Open a .json File

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#1039]
An attempt to open a .json file for an Aspen Plus model in SimSinter resulted in the following error:

![image](https://user-images.githubusercontent.com/30811140/174674530-b50113f9-adee-4847-8e97-143222d9ac22.png)

**Comment by ksbeattie** [comment]
We think we might have seen this before.  Can you check the installation of Aspen and the status of it's license?  Also let us know details about the OS and Aspen version you're using here?

**Comment by fsoepyan** [comment]
Thank you @ksbeattie for the prompt response.

Answering your question: 
- The Aspen license has been renewed this past Thursday (the license needs to be renewed every 30 days).
- The version of Aspen used is Aspen V12.1.
- The computer is a 64-bit operating system.

**Comment by fsoepyan** [comment]
I found a set of instructions in the following website: https://docs.microsoft.com/en-US/troubleshoot/windows-server/application-management/error-8008005-when-start-complus-applications

I will give this method a try, and let you know if it works.

**Comment by fsoepyan** [comment]
The above approach did not work. I will continue looking for other ways to resolve this issue.

**Comment by fsoepyan** [comment]
I found another set of instructions on this website: https://answers.microsoft.com/en-us/windows/forum/all/retrieving-the-com-class-factory-for-component/d801f311-cc39-4d83-8058-a209ef8f97cf

I will give this method a try, and let you know if it works.

**Comment by fsoepyan** [comment]
This method did not work either.

**Comment by ksbeattie** [comment]
Is this a specific .json file you can't open, or is it any/all files that you can't open?

And do you know when this stopped working for you?

**Comment by fsoepyan** [comment]
By the way, I found the following passage from the SimSinter manual regarding this issue:

"The error means that SimSinter cannot find the CCSIUnits COM interface. This should be unusual, since CCSIUnits is now packaged with SimSinter. If the error occurs try reinstalling CCSIUnits separately."

Is there a way to uninstall and reinstall CCSIUnits separately?

**Comment by boverhof** [comment]
Sounds like process can't locate a library, likely CCSIUnits.  To confirm this you might just want to run ConsoleSinter directly and see if it throws the same COM error.

This issue should explain how to setup it up and run it:

https://github.com/CCSI-Toolset/SimSinter/issues/27

If that is the case, I would recommend removing SimSinter and reinstalling it.  If that doesn't fix it maybe we can do a Zoom call and I can help you figure this out.

**Comment by fsoepyan** [comment]
@ksbeattie and @boverhof: Thank you for your help, I appreciate it.

I am sorry I have not told you the full detail, but my colleague is actually the one having this issue with Aspen/SimSinter.

One of the reasons I am struggling with this issue is because I am using Aspen v12.1, and a 64-bit operating system, and I manage to open the .json file for the Aspen models in SimSinter without any issue. I can also run Aspen models in FOQUS in my computer. As a result, I could not reproduce the issue.

**Comment by boverhof** [comment]
@fsoepyan I think this is probably an easier way to test:
<img width="942" alt="Screen Shot 2022-07-20 at 4 28 00 PM" src="https://user-images.githubusercontent.com/738295/180099651-8ef0fe78-7309-474e-8a49-eaac3599a7b2.png">

**Comment by boverhof** [comment]
@fsoepyan I guess figuring out the differences between your setup and your colleagues is the best next step.   Did you install as Administrator or a User?

**Comment by fsoepyan** [comment]
@boverhof: Can you please let me know what test you are referring to?

Answering your question, I think I installed as an Administrator, as I am using a personal computer.

**Comment by fsoepyan** [comment]
My colleague has uninstalled and reinstalled both the Aspen software and the Aspen license file, and this has resolved the issue.

I will close this issue.

@ksbeattie and @boverhof: Thank you very much for your help.
