### ISSUE TITLE
UQ: Allow user to use response surface model in Flowsheet

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#105]
In the UQ tab, the "Expert" mode of the "Analysis" menu allows the user to "Validate" the performance of response surface models (e.g., Polynomial, MARS, etc.).

It would be great if the user can use these response surface models in the Flowsheet, where the response surface model is used to compute the value of the output variable given the input variables.

**Comment by ksbeattie** [comment]
@eslickj says he sent @ngbrenda an example from work that  @jmorgan29 did that might help here.

Josh says he will look to dig up that email again...

**Comment by eslickj** [comment]
From @jmorgan29:

Hello all,

Based on the conversation during yesterday’s meeting, I have reorganized the MARS code to include a template file (‘main’) that calls a series of additional files (‘rs1’,’rs2’,…) to calculate the interpolated value for each of 5 outputs. Also included in the template file are names of the input and output variables as well as example values for the inputs. I am hoping this is a good starting point for setting up the FOQUS plugin. Please let me know of any additional questions or issues with the setup.   . 

[MARS.zip](https://github.com/CCSI-Toolset/FOQUS/files/2105989/MARS.zip)

**Comment by eslickj** [comment]
From me:

A flowsheet plugin based on what Josh sent is attached.  Now if we can automate the generation we'll be set.  I don't know want goes in with the UQ stuff so someone else will have to take it from here.


[mars_plugin.zip](https://github.com/CCSI-Toolset/FOQUS/files/2105991/mars_plugin.zip)

**Comment by ksbeattie** [comment]
@ou3llnl will take a look at this.

**Comment by ou3llnl** [comment]
So I'm thinking we will depend on the user to generate the different response surface models for each output and then have a dialog that you use to associate an output with the code file and generate the "main.py". @eslickj : How do you actually specify this file as the plugin for the node?

**Comment by ksbeattie** [comment]
@eslickj, will take another look at this, talking to @fsoepyan to come up with a plan to address this.  "It could be a bit of work".

**Comment by fsoepyan** [comment]
From my understanding, the solution for this issue would be to have FOQUS automatically generate the .py file that @eslickj wrote (attached in one of his previous comments) whenever the user goes to UQ and clicks the "Validate" button for the MARS model.

Is this correct?

**Comment by ou3llnl** [comment]
Almost. So the user would have UQ generate a response surface python script for each output during validation. It doesn't have to be MARS, other response surfaces also generate model code as well. To be used in flowsheet, FOQUS would need to automatically generate the glue code that @eslickj wrote to use all these scripts. In order to do this, it seems to me this would require some kind of dialog to allow the user to specify which script maps to which output. You could have this process done in UQ, but I think it makes more sense to do this in flowsheet because only flowsheet requires this glue code. Hope this makes sense.

**Comment by fsoepyan** [comment]
- If the equations of the UQ surrogate models (i.e., response surface) aren't complicated, then would copying and pasting the equation to the "Python Script" portion of "Node Editor" be an acceptable solution?
- If so, we just need to let the user know where they can find the equation of the surrogate model.

**Comment by fsoepyan** [comment]
After talking with @eslickj, I learned that resolving this issue requires modifications in both the Flowsheet and UQ tabs.

Is this worth pursuing?

**Comment by ksbeattie** [comment]
@eslickj  will follow up with @jmorgan29 on if this is worth pursuing.

**Comment by fsoepyan** [comment]
After communicating with @jmorgan29, I learned that the procedure for transferring the .py file generated by the UQ tab into a Flowsheet Plugin is simple. Therefore, the automation of the process may not be necessary.

I will close the issue.
