### ISSUE TITLE
UQ/SDOE Plotting Issues From Matplotlib Version Update

### ISSUE THREAD

**Issue by bpaul4** [CCSI-Toolset/FOQUS#1059]
`matplotlib` released version 3.6 which removed the `set_window_title` call. This affects several UQ tests which call the deprecated method. Additionally, the SDOE plotting utilities script calls this method a few times and should be altered to avoid using the outdated call.

Alternatively, we could pin `matplotlib<3.6` for now.

**Comment by ksbeattie** [comment]
If we can't figure this out in time, I'm fine with pinning the matplotlib for the Sept release here.
