### ISSUE TITLE
Tests for plugin loading from string reading

### ISSUE THREAD

**Issue by bpaul4** [CCSI-Toolset/FOQUS#1074]
Recently, I noticed that FOQUS is not correctly loading Pymodel plugins from the user_plugins or examples/.../pymodels folders. A recent update had run `black` on `session.py` and `surrogates.py` which generate the idString objects used to detect and load plugins, so that files contained `black`-formatted `# FOQUS-[tag]` while the search expected `#FOQUS-[tag]`.

The issue went undetected until `black` was run on the working directory and those plugins failed to load; the console did not display any error or warning message that the idString did not properly parse. There should be tests that check that plugins are correctly loaded when FOQUS is launched, and we should add better logger messages for when this case arises.

**Comment by lbianchi-lbl** [comment]
Hi @bpaul4, thanks for spotting this and creating an issue.

Can I ask you to point out where exactly the files for the plugins that are failing to load are located within the FOQUS repository? I'm starting to look into this (also in relation to #908) and I'd like to make sure I'm at least aware of the existing plugins.
