### ISSUE TITLE
Semi Batch/Cyclical/Dynamic Modeling

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1076]
# Description
Explore using FOQUS rather than Excel as the controller for the workaround for Dynamic ACM.

FOQUS Optimization generates a batch of parameters, runs the iteration, gathers the results, then determines a new parameter set to attempt.  It does this until the Optimization function succeeds.

## Details
Link to Excel Workaround and description @Ryan-Hughes-8

**Comment by Ryan-Hughes-8** [comment]
@boverhof sorry I let this slip, do you need anything from me here?

**Comment by boverhof** [comment]
related to https://github.com/CCSI-Toolset/FOQUS/issues/1044

**Comment by ksbeattie** [comment]
@Ryan-Hughes-8 did this workaround get documented somewhere?

**Comment by Ryan-Hughes-8** [comment]
@ksbeattie not yet, still working on it

**Comment by ksbeattie** [comment]
Moving this to March, but raising priority since it should be relatively easy to add just the workaround docs.
