### ISSUE TITLE
SDoE: Adding previous data to IRSF

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#1077]
Currently only Uniform Space-Filling (USF) and Non-Uniform Space-Filling (NUSF) are able to handle previous data files. That capability needs to be added to the Input-Response Space-Filling (IRSF) side of things as well.

**Comment by ksbeattie** [comment]
@sotorrio1 is this still possible for the Dec release (as in next week)?

**Comment by sotorrio1** [comment]
@ksbeattie Still possible, trying hard to make it happen :)

**Comment by ksbeattie** [comment]
@sotorrio1, any update?  We've only got a few days now...

**Comment by sotorrio1** [comment]
I'll get you an update on this either later today or tomorrow. R code turned out not to be as straight forward as I though...

**Comment by sotorrio1** [comment]
@ksbeattie don't hold the release for this. We'll get it into the master before the end of the year.
