### ISSUE TITLE
Add type annotations to SDoE

### ISSUE THREAD

**Issue by franflame** [CCSI-Toolset/FOQUS#1111]
Add typing to SDoE functions for testing purposes, prioritize usf.py

**Comment by lbianchi-lbl** [comment]
@dangunter recently suggested https://pypi.org/project/pyleft/, a tool that checks that type annotations are present without actually enforcing them (as opposed to e.g. MyPy, pyright, ...). If we can manage to make it work on a limited subset of files, this could be a good intermediate step going forward.
