### ISSUE TITLE
FOQUS Cloud License Problem

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1117]
# Description
- AspenPlus license fails to checkout
- SLM Profiler shows licenses available from the internal license server from the VM FOQUS Cloud worker.

## Problem
- AMI is configured incorrectly with old SLM Server IP Address

- [ ] update AMI to SLM Server `10.0.0.100`

```
-------------- SLM Common Error Dialog ---------------

Application: aspenplus.exe

--------------- Information Flags ---------------

Error while checking out license AspenPlus
IgnoreLocal
Error while checking out license AspenPlus
SuppressBroadcasts


--------------- Sequence of Events ---------------

Server: PUBLIC_IP_ADDRESS_OF_SLM_SERVER
Bucket: default
Type: Standard License
Code: 5
Description: There is an issue with your network communication.  

Please verify that the License Manager service (Sentinel RMS License Manager) is running on the license server.  
Also check that port UDP 5093 is open on both the client and server machines.


```

![Screen Shot 2023-03-07 at 1 40 47 PM](https://user-images.githubusercontent.com/738295/223559885-ae3933ba-df6f-4a5f-8170-bcedef255052.png)

**Comment by SarthakJain04** [comment]
How to solve this issue?

**Comment by ksbeattie** [comment]
> How to solve this issue?

You need to have an Aspen license.
