### ISSUE TITLE
Release Candidate Test:  March 2023 RC0

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1130]
# Description
## Setup
- grabs zips from release page and install
```
>conda create --name ccsi-foqus -c conda-forge python=3.8 pywin32
>conda activate ccsi-foqus
>cd FOQUS-3.17.0rc0
>pip install .
```

**Comment by boverhof** [comment]
## Dev 
- install dev requirements so can run tests
- @lbianchi-lbl is this expected behavior?  Tests can be run without a GIT clone?
```
>pip install -r requirements-dev.txt

> pytest
======================================================================================== ERRORS =========================================================================================
_________________________________________________________________________ ERROR at setup of test_results_empty __________________________________________________________________________

    @pytest.fixture(scope="session")
    def _repo_root():
        this_file = Path(__file__).resolve()  # FOQUS/foqus_lib/conftest.py
        repo_root = this_file.parent.parent
>       assert (repo_root / ".git").is_dir()
E       AssertionError: assert False
E        +  where False = <bound method Path.is_dir of WindowsPath('C:/Users/Administrator/Desktop/FOQUS-3.17.0rc0/.git')>()
E        +    where <bound method Path.is_dir of WindowsPath('C:/Users/Administrator/Desktop/FOQUS-3.17.0rc0/.git')> = (WindowsPath('C:/Users/Administrator/Desktop/FOQUS-3.17.0rc0') / '.git').is_dir

foqus_lib\conftest.py:54: AssertionError
```

**Comment by boverhof** [comment]
# Optional Install Page Outdated
- Bad link for SQL Compact 4.0
- https://www.microsoft.com/en-us/download/details.aspx?id=30709

**Comment by boverhof** [comment]
# Local Flowsheet Test: BFB_OUU_06_09_2020.foqus
- success, ran 4 times in a row
- ccsi-foqus-3.17.0rc0-examples\examples\test_files\OUU_Remote_Turbine_BFB\BFB_OUU_06_09_2020.foqus

**Comment by lbianchi-lbl** [comment]
> ## Dev
> 
>     * install dev requirements so can run tests
> 
>     * @lbianchi-lbl is this expected behavior?  Tests can't be run without a GIT clone currently.

Yes, that's the expected (although perhaps not intended) behavior - currently running pytest is only supported for the "developer workflow", i.e. `git clone` + `pip install requirements-dev.txt`.

However, being able to run the test suite (or a subset of it) after a non-editable or non-git installation would be useful, especially in the context of testing releases. I've opened #1131 to keep track of this.
