### ISSUE TITLE
OUU BFB Test Hanging:   z3samples file

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1141]
I'm trying to get this OUU example to work on the new release #1009 to run but it appears to just hang using both 'local' and 'remote' options.  I used a trimmed down z3 file with just a couple entries but it hangs.

The z3samples file I uploaded to the aforementioned issue doesn't seem to match the description from @sotorrio1.  It has four Z3 variables and the description indicates two.  

So I think we need to get a z3 file that matches up with that description so I can test if it works correctly.

**Comment by boverhof** [comment]
![Screenshot 2023-04-25 at 1 42 58 PM](https://user-images.githubusercontent.com/738295/234398997-2aa5679e-5140-4824-962a-68a1bd63a874.png)

**Comment by sotorrio1** [comment]
[z3Samp.smp.txt](https://github.com/CCSI-Toolset/FOQUS/files/11327043/z3Samp.smp.txt)

Use this z3Samp.smp (remove the .txt extension)

**Comment by boverhof** [comment]
Think it was hanging on "location of PSUADE" GUI pop up.  I uninstalled and installed with GIT Repo and now I get a pop up with a message.  Before it was empty.  

- If I don't select the location of PSUADE it hangs with an empty message
- now if I close FOQUS and open it back up, it just hangs with empty dialog

![Screenshot 2023-05-08 at 1 59 06 PM](https://github.com/CCSI-Toolset/FOQUS/assets/738295/26b6950d-09eb-4976-9a6a-75d96033f382)

**Comment by boverhof** [comment]
# Logic Error
- these paths are typically wrong
- if user cancels first time asked to select location of psuade seems configuration is busted 
```
(py3.9) Joshuas-MacBook-Pro:foqus boverhof$ find . -name \*.py  | xargs grep -s 'psuade_project'
./foqus_lib/framework/uq/LocalExecutionModule.py:            psuadeLoc = 'C:/Program Files (x86)/psuade_project %s/bin/psuade.exe' % LocalExecutionModule.psuadeVersion
./foqus_lib/framework/session/session.py:            "C:/Program Files (x86)/psuade_project 1.7.5/bin/psuade.exe"
(py3.9) Joshuas-MacBook-Pro:foqus boverhof
```

**Comment by boverhof** [comment]
- Moving to new issue but problem still here.
- Partial Fix  https://github.com/CCSI-Toolset/FOQUS/pull/1133
