### ISSUE TITLE
PSUADE support on ARM MacOS

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#1150]
This is still a WIP.

- [x] Upload tarball to Anaconda (@lbianchi-lbl)
- [ ] ~~Update PSUADE to 1.10 (@lbianchi-lbl)~~
- [ ] ~~Test FOQUS with PSUADE 1.10 (TBD)~~

**Comment by kbuma** [comment]
I've created https://github.com/LLNL/psuade-lite/pull/6 for the changes to switch the psuade macos builds to utilize an SDK that has arm64 support and bump up the version to 1.10.0
I can't assign that to anyone for review so @lbianchi-lbl can you pick that up when you have a chance. Also, the workflow is such that it requires approval from a maintainer to run the github actions as part of the acceptance testing.

**Comment by kbuma** [comment]
Here's the psuade-lite 1.10.0 osx-arm64 build (attached - renamed to .zip instead of .bz2 since github won't accept extension so need to rename back before uploading to conda)
[psuade-lite-1.10.0-h48bf9af_0.tar.zip](https://github.com/CCSI-Toolset/FOQUS/files/11860587/psuade-lite-1.10.0-h48bf9af_0.tar.zip)

**Comment by lbianchi-lbl** [comment]
@kbuma @franflame it should now be possible to install `psuade-lite` on macOS ARM with Conda:

```sh
conda activate ccsi-foqus  # or, the appropriate name for the FOQUS Conda env
conda install -c conda-forge -c CCSI-Toolset psuade-lite=1.10
```

**Comment by lbianchi-lbl** [comment]
I apologize for the confusion with PSUADE (-lite) 1.10 - apparently, the changes that we thought we would need (i.e. that would have warranted a 1.10 version) never actually got implemented, so the most recent version of `psuade-lite` remains 1.9.0.

Following up after today's dev call:

- [ ] @kbuma, would it be possible to re-build the package on your Apple Silicon machine after changing the version in the Conda `meta.yml` to 1.9.0 (see https://github.com/LLNL/psuade-lite/pull/6/files#r1370784036)?
- [ ] @lbianchi-lbl: upload the 1.9.0 Apple Silicon build to the CCSI-Toolset channel (and possibly remove the 1.10 build to reduce potential for confusion)

**Comment by lbianchi-lbl** [comment]
The Apple Silicon version of `psuade-lite` 1.9 has been built and uploaded, so this can be considered complete (since we don't yet have access to Apple Silicon GHA runners to test this with).
