### ISSUE TITLE
Implement "Minimum Viable Product" for ML/AI model creation GUI tool

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#1158]
The MVP should support a minimal subset of the required features to get things up and running

- Supported framework: Tensorflow Keras
- Use existing standalone scripts and datasets such as https://github.com/CCSI-Toolset/FOQUS/blob/master/examples/other_files/ML_AI_Plugin/mea_column_model_training.py

**Comment by ksbeattie** [comment]
Added in #1163
