### ISSUE TITLE
FOQUS_Cloud: SDoE Parallelism 

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1167]
Able to run function `compute_min_distance` on AWS Lambda, next steps are to batch request this via the REST API because the function run times are very low can't round trip each request through an HTTP call because the overhead would be too much relative to the function runtime.

- [x] Batch submit compute_min_distance to AWS Lambda
- [x] Evaluate if this methodology is practical to reduce runtimes of large requests, hopefully by a factor of 

# Related
https://github.com/CCSI-Toolset/FOQUS/issues/1110

**Comment by ksbeattie** [comment]
@boverhof what's the status on this?

**Comment by boverhof** [comment]
I ran 1000 using the current REST interfaces.  My conclusion is this method won't work because it is limited to batches of 25 during submission, which are too small because the function runtimes are under 1 second.  It takes on the order of a minute to load up a 1000 jobs in 25 job batches.  I could tweak the REST API and backend lambda to load up larger batches, but the issue comes down to utilizing AWS DynamoDB on the submission to store job status.  DynamoDB imposes this 25 entry limit.

**Comment by boverhof** [comment]
My recommendation is to add a "HTTP POST" job submission hook that returns an AWS S3 presigned URL, which provides time limited secure access to an S3 Object for writing.  This URL can be used to save a very large batch of jobs directly to S3, and then the AWS Lambda backend can be invoked asynchronously and in parallel to digest it.  I've already implemented the presigned URL pattern in parts of the python turbine client so I think this can be done with a couple days efffort.

**Comment by boverhof** [comment]
Batch 25 limit:  https://github.com/CCSI-Toolset/FOQUS/issues/290
