### ISSUE TITLE
Documentation for NLOpt install

### ISSUE THREAD

**Issue by Ryan-Hughes-8** [CCSI-Toolset/FOQUS#1174]
Current documentation states that NLOpt should get installed with psuade-lite 1.9.0, but that either isn't the case or the optimization tab doesn't recognize the install so NLOpt isn't listed with available solvers. I instead installed through conda-forge which worked fine.

**Comment by ksbeattie** [comment]
Updating the documentation seems like the needed thing here.  @Ryan-Hughes-8 is there a failure anywhere if you try running without having installed NLOpt properly?  If so we might want to provide a helpful error message in that situation.

**Comment by ksbeattie** [comment]
Looks like https://github.com/CCSI-Toolset/FOQUS/commit/72f18fdf405905cf6cf79c5a2a7d2c371a06d13b#diff-ea1e7a4b740752f3b1d58cc0277fdeb0402f52643cd77a321392d407d43b38cd is where the documentation was last changed.  @boverhof should be able to undo that.
