### ISSUE TITLE
PSUADE `std::bad_alloc` Memory Issue During GP Response Surface Generation

### ISSUE THREAD

**Issue by bpaul4** [CCSI-Toolset/FOQUS#1178]
One of our collaborators encountered the error below when attempting to generate a GP response surface:

![image](https://github.com/CCSI-Toolset/FOQUS/assets/86113916/9d1f30d2-d7b9-490e-9a5e-87ad943b4719)

**Comment by ksbeattie** [comment]
Perhaps running this again while watching the TaskManager memory use and see if it is running out of memory.  If so, try running on a machine with more RAM.

Another idea would be to run it again entirely outside of FOQUS, running psuade from the command line using the same input file that FOQUS generated.

There might be a psuade setting that could handle things better.

**Comment by ksbeattie** [comment]
Haven't heard back from Anderson on this in a few weeks.
