### ISSUE TITLE
FOQUS documentation has incorrect paths to files in examples package

### ISSUE THREAD

**Issue by kbuma** [CCSI-Toolset/FOQUS#1180]
The online FOQUS documentation for Tutorial 2 (https://foqus.readthedocs.io/en/latest/chapt_flowsheet/tutorial/sim_flowsheet.html) refers to paths in the examples package as e.g. `example/Optimization/Model_Files/` whereas the files seem to be now located in e.g. `examples/test-files/Optimization/Model_Files/`

Is there a different example this is referring to or was there a change to the location?

**Comment by ksbeattie** [comment]
Looks like this was something missed way back with https://github.com/CCSI-Toolset/FOQUS/pull/586
