### ISSUE TITLE
FOQUS, SimSinter, and Turbine Testing

### ISSUE THREAD

**Issue by bpaul4** [CCSI-Toolset/FOQUS#1189]
The workflow below has been used to verify release candidates of FOQUS, SimSinter, and Turbine on manual model creation and execution, and should be added to the documentation for future use as a release acceptance test:

Purpose: Verifying that the latest versions of FOQUS, SimSinter and Turbine perform as expected. 

Setup – verify that all downloads/installs are trusted, and that no security warnings pop up 

Follow [FOQUS Installation and Running — FOQUS](https://foqus.readthedocs.io/en/latest/chapt_install/index.html) to get the desired release of FOQUS 

Follow [Install Optional Software — FOQUS](https://foqus.readthedocs.io/en/latest/chapt_install/install_optional.html#install-turbine-and-simsinter-windows-only) to get the desired SimSinter and Turbine releases 

Tutorial Tests 

1. [Tutorial 2: Creating a Flowsheet with Linked Simulations — FOQUS](https://foqus.readthedocs.io/en/latest/chapt_flowsheet/tutorial/sim_flowsheet.html) - test loading and running pre-existing an Aspen Custom Modeler simulation and linked Excel model. Test the resultant session file with [Tutorial 1: Optimization — FOQUS](https://foqus.readthedocs.io/en/latest/chapt_opt/tutorial/simple.html) using the NLOpt solver. 

2. [Tutorial 1: Aspen Custom Modeler (ACM) Configuration — FOQUS](https://foqus.readthedocs.io/en/latest/chapt_sinter/tutorial/acm.html) - test modifying and saving an Aspen Custom Modeler simulation in SinterConfigGUI. 

3. [Tutorial 2: Aspen Plus Configuration — FOQUS](https://foqus.readthedocs.io/en/latest/chapt_sinter/tutorial/ap.html) - test modifying and saving an Aspen Plus simulation in SinterConfigGUI. 

4. [Tutorial 3: Microsoft Excel Configuration — FOQUS](https://foqus.readthedocs.io/en/latest/chapt_sinter/tutorial/excel.html) - test modifying and saving an Excel simulation in SinterConfigGUI 

5. Run Aspen Plus models 

a. Using the “Flash_Example” from Step 2, open the .json and edit the arguments to use "version": "36.0" "constraint": "REQUIRED" to use Aspen V10 and save the .json file. Create a new FOQUS session, update the model to Turbine, add and populate a node with the model, and run the flowsheet. 

b. After finishing successfully, close FOQUS without saving, and repeat Step 5a setting "constraint": "REQUIRED" and setting "version" to "37.0" for Aspen V11, "38.0" for Aspen V12, and "40.0" for Aspen V14. 

6. Run Excel model 

a. Using the “exceltest” from Step 4, create a new FOQUS session, update the model to Turbine, add and populate a node with the model, and run the flowsheet. 

7. [MATLAB-FOQUS interface - tutorials — FOQUS](https://foqus.readthedocs.io/en/stable/chapt_matlab/tutorial/matlab_foqus_tutorial.html) - test loading and running MATLAB plugins

**Comment by ksbeattie** [comment]
More tests documented here: https://github.com/orgs/CCSI-Toolset/discussions/1188

**Comment by ksbeattie** [comment]
Let's move this into the new DevOps repo.

**Comment by bpaul4** [comment]
The documentation lives here now: https://github.com/CCSI-Toolset/devops/blob/main/manual-software-testing.md
