### ISSUE TITLE
Configuration Panel:  Add Timeouts for AspenConsumer 

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1199]
# Description
The AspenConsumer executes and manages AspenPlus and ACM flowsheets and is configured to kill the AspenEngine when a time out value is exceeded.  This parameter is modifiable in an XML configuration file.  The purpose of this issue is to expose these configuration parameters in the FOQUS configuration UI ( screen shot below ).  Should read and edit the `AspenSinterConsumerConsole.xml`, display the values in this UI and allow the user to edit it which may require a restart of FOQUS.
 

##  web API Timeouts
  - these monitor the Web API in a loop
  - if the "status" doesn't change eventually it sends a "Kill"

## AspenSinterCosumerConsole  Timeouts
- `\Program Files (x86)\Turbine\Lite\Consumers\AspenSinterConsumerConsole.xml`
- 
<img width="818" alt="Screenshot 2024-03-05 at 12 54 21 PM" src="https://github.com/CCSI-Toolset/FOQUS/assets/738295/d7754624-0640-4b36-bc98-087c16f1db6b">

**Comment by sotorrio1** [comment]
@boverhof basically it would be adding another section under "Settings" called for example "Aspen Configuration Parameters" where the user can specify the path to the XML file and edit the parameters in the UI. 

I would need the possible paths to this file and a copy of an example file.

Thanks!

**Comment by sotorrio1** [comment]
something like this...

![Screenshot 2024-07-16 at 4 12 57 PM](https://github.com/user-attachments/assets/75797a0c-3454-4adc-a22d-741e9092d407)

**Comment by boverhof** [comment]
@sotorrio1 This is the "template" that gets converted to the XML file:

[App.config](https://github.com/CCSI-Toolset/turb_sci_gate/blob/master/Master/AspenSinterConsumerConsole/App.Config)

**Comment by sotorrio1** [comment]
@boverhof Thanks!

**Comment by boverhof** [comment]
There is a complication with the Windows Software, it expects XML namespaces to be declared as the default namespace.  I tried using element tree to rewrite the XML Configuration but it declares namespaces with prefixes and the Windows software doesn't understand that.  
```
Unhandled Exception: System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized attribute 'xmlns:ns0'. Note that attribute names are case-sensitive.
```

```python
# -*- coding: utf-8 -*-
"""
"""
import os
from shutil import copyfile
import time
import xml.etree.ElementTree as ET

DIR='\Program Files\Turbine\Lite\Clients'
XML_CONFIG = os.path.join(DIR,  'AspenSinterConsumerConsole.exe.config')
COPY_XML_CONFIG = XML_CONFIG + '-backup-' +  str(time.time())

def main():
    assert os.path.isdir(DIR)
    assert os.path.isfile(XML_CONFIG)
    copyfile(XML_CONFIG, COPY_XML_CONFIG)
    tree = ET.parse(XML_CONFIG)
    root = tree.getroot()
    print(root)
    node = root.find("./userSettings/Turbine.Console.Properties.Settings/setting[@name='TimeOutIterations']/value")
    assert node is not None
    print("TEXT: %s" %(node.text))
    val = int(node.text)
    
    # Double the Timeout value
    val *= 2
    print("NEW VALUE: %d" %(val))
    node.text = str(val)
    
    tree.write(XML_CONFIG)
    

if __name__ == '__main__': main()
```
