### ISSUE TITLE
Flowsheet: Recover progress from log file?

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#12]
From JIRA:
- Reporter: Miguel Zamarripa (@MAZamarripa)
- Assignee: Charles Tong
- Original title: turbine - FOQUS interaction.
- Created: 15/Feb/17 2:07 PM
- Updated: 15/Feb/17 2:07 PM

Description:

After running 2000 simulations, the computer shutdown. I can see the simulations are stored in the log file. Can we recover this results?
In the flowsheet "import" panel, can we include an option to import from log file? (FOQUS allows imports from "clipboard" and "csv file")

**Comment by ngbrenda** [comment]
This happened within the UQ tab, when the user had created an input ensemble (saved as WORKING_DIR/psuadeData) and clicked the "Launch" button to launch the jobs. @sotorrio1 will figure out how to save the launched samples. Then we can write a parser to load this file back as an ensemble.

**Comment by anujad95** [comment]
Currently in UQ, i think the samples that have run successfully do get stored in the ensemble result table, either after the launch is fully completed, or after the stop button is pressed, or if the user keeps saving the session regularly. I'm not sure what would happen if the GUI automatically shuts down. Is this something that still needs to be looked into?
