### ISSUE TITLE
Resolve Keras File Format Issues

### ISSUE THREAD

**Issue by bpaul4** [CCSI-Toolset/FOQUS#1202]
TensorFlow updated to version 2.16.1 on March 8, 2024. Calling Keras in Python 3.9+ environments now throws errors similar to the message below:

```
E           ValueError: File format not supported: filepath=D:\a\idaes-pse\idaes-pse\idaes\core\surrogate\plotting\tests\keras_surrogate. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(D:\a\idaes-pse\idaes-pse\idaes\core\surrogate\plotting\tests\keras_surrogate, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).
```

Tests and code that use Keras should be updated accordingly. This is not currently a breaking issue because we only run Keras in Python 3.8 test environments which use an older Keras version. It would be good to discuss whether running optional dependencies in 3.9 or 3.10 instead of 3.8 going forwards is worthwhile.

**Comment by ksbeattie** [comment]
Will follow how this is addressed in IDAES: https://github.com/IDAES/idaes-pse/issues/1369
