### ISSUE TITLE
Failures in ML/AI plugin tests: ModuleNotFound: no module named 'jsonpointer'

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#1222]
- Originally noticed in #1221, but likely unrelated
- Need to see if it can be reproduced in isolation, e.g. by opening a dedicated PR with no changes wrt `main`

![image](https://github.com/CCSI-Toolset/FOQUS/assets/48035537/32309e2b-8222-4535-8764-ea46696d36d5)

**Comment by ksbeattie** [comment]
This will wait for #1202, as it might resolve or at least inform this issue.

**Comment by ksbeattie** [comment]
This isn't happening any more.
