### ISSUE TITLE
Not All Arguments Converted During String Formatting 

### ISSUE THREAD

**Issue by jmorgan29** [CCSI-Toolset/FOQUS#1237]
I am working with the latest version of FOQUS, installed with pip based on the installation instructions. I have also recently updated software versions of SimSinter to 3.1.0 and TurbineLite to 3.0.0. When attempting to run any Aspen file in FOQUS, I get the following error:

![string formatting error](https://github.com/user-attachments/assets/bf8b1d91-88ed-4414-97ae-ef3565d59aa9)

**Comment by jmorgan29** [comment]
The main text here that seems to be relevant to diagnosing the problem is "the system cannot find the file specified" and "TypeError: not all arguments converted during string formatting"

**Comment by jmorgan29** [comment]
I have also confirmed getting the same error when working with a simple Excel example.

**Comment by jmorgan29** [comment]
This has been solved through discussion during the dev call, but there could be improvements made in the documentation to make clearer that the user should manually change the paths of the Turbine and SimSinter installations to reflect the 64-bit software.

For example, the workflow I used to fix the problem was a manual update of the following two paths under the FOQUS Settings:

![SimSinter Path](https://github.com/user-attachments/assets/518ae418-afca-4852-9526-df85a3186934)

![Turbine Path](https://github.com/user-attachments/assets/9280139b-1795-45b4-82ad-a1a9da454111)

**Comment by ksbeattie** [comment]
- [ ] @karlo will update the documentation as described above
- [ ] @boverhof will change the default (for new installations) to use the 64-bit path ("Program Files")
