### ISSUE TITLE
OUU: investigate nonlinear compute time

### ISSUE THREAD

**Issue by ngbrenda** [CCSI-Toolset/FOQUS#126]
Byron reported some performance issues related to sample size. Here is his email:

Here is what I did:
- I went to the OUU tab.
- I selected "Full flowsheet" under "Choose Flowsheet Node".
- I set X01 to X04 as "Continuous Z1", and I set the rest of the variables as "Z4".
- Under "Outputs", I selected "surrogate.negCO2" as "Objective Function", and I set all other variables as "Not used".
- Under "UQ Setup", I selected "Load existing sample for Z4", I clicked "Browse", and selected the file "PosteriorSampleNew", which was developed by Pedro.
- I checked the box next to "Use Response Surface".
- I specified the number N of "Response Surface Sample Size".
- I clicked "Run OUU" under "Launch/Progress".

Here is the issue:
- When I set N = 20, within minutes, results are generated by FOQUS.
- When I set N = 25, in 20 minutes, there were still no results.
- When I clicked "Stop" under "Launch/Progress", the mouse cursor turns into the hourglass, and the "Stop" button did not return to the "Run OUU" button (Issue #101 in GitHub). In order to rerun OUU, I had to close FOQUS and reopen it.

**Comment by fsoepyan** [comment]
- I tested the OUU tab using an example Aspen Plus simulation
- I ran OUU using 20 samples and 25 samples
- When I ran OUU using 25 samples, it took about 1 hour (more or less)
- The message box that says the OUU runs are finished appeared, and the "Stop" button reverts to the "Run OUU" button
- I will close this issue

**Comment by fsoepyan** [comment]
- I tested the OUU tab using the same example Aspen Plus simulation
- I ran OUU using 50 samples
- It took between 2.5 to 3 hours (which is fine)
