### ISSUE TITLE
Separate Examples?

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#130]
Some of the example simulation files are pretty large.  Would it be better to create a separate examples download?  Or a page somewhere that was like an examples gallery?

**Comment by ksbeattie** [comment]
Adding this to the July release board, I will take a look at moving these to a different repo or moving them to LFS.

**Comment by fsoepyan** [comment]
- I have no problem with the FOQUS download time, even when the example files are downloaded together with FOQUS.
- Would anyone object if we close this issue? (Because we are close to closing this issue, I will move this issue to "High" priority in the project board.)

**Comment by eslickj** [comment]
I don't object to closing it as long as everyone is happy keeping it all together.  It doesn't matter to me.
