### ISSUE TITLE
Clean up of psuade files

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#146]
When I run OUU, the iterations are no longer recorded in the Flowsheet table.

**Comment by ou3llnl** [comment]
I  think this has to do with OUU not able to advance due to issue #101. When I can fully debug what is going on and fix it, this should no longer be an issue. Some progress has been made, but it is still ongoing.

**Comment by ou3llnl** [comment]
@fsoepyan : Try this with psuade 1.7.12 and let me know. I think it should work now.

**Comment by fsoepyan** [comment]
- I downloaded psuade 1.7.12 from GitHub
- I made sure the psuade directory under the "Settings" tab refers to the correct folder
- When I ran OUU, I got this error message:

<img width="961" alt="ouu_06_13_2018" src="https://user-images.githubusercontent.com/30811140/41371766-5a3c2a4a-6f19-11e8-81af-163c6ff8f009.png">

- I closed the error message
- I checked the "Flowsheet Results" table, and the OUU runs are not recorded

**Comment by ou3llnl** [comment]
Ok. That's an error I was not anticipating. At least you are getting plot points now, which I assume you were not getting before. I'll have to look into how this could have happened.

**Comment by fsoepyan** [comment]
Actually, I managed to get the plot points (in the bottom right corner) with the previous version of psuade.

**Comment by ou3llnl** [comment]
@fsoepyan : What is the method the flowsheet is using to calculate the errors? Is this a standard turbine node? Or is this an attempt to use the surrogate capability that Josh Morgan and John Eslick have been adding to flowsheet?

If you were to run a standard turbine/turbine lite problem, does it work?

**Comment by fsoepyan** [comment]
Answering your first question:
- I did not use the new surrogate capability
- I used "Plugin" and the ALAMO surrogate model

**Comment by fsoepyan** [comment]
Answering your 2nd question:
- I ran OUU using a turbine lite model
- I got the same error message that I showed earlier, and the OUU runs were not recorded in the Flowsheet table
- I'm also having the same problem as that mentioned in Issue #131

**Comment by ksbeattie** [comment]
@ou3llnl says that this is waiting on a new version of psuade?

**Comment by ou3llnl** [comment]
We found the error from foqusPSUADEClient.py is actually a problem with Python setup in Windows, which causes calls to Python scripts from console to omit command line arguments.  Follow the steps in the following links to fix your environment.

[https://eli.thegreenplace.net/2010/12/14/problem-passing-arguments-to-python-scripts-on-windows](url)
[https://stackoverflow.com/questions/2640971/windows-is-not-passing-command-line-arguments-to-python-programs-executed-from-t](url)

**Comment by sotorrio1** [comment]
@fsoepyan , you actually need to add that to your registry keys. In Windows go to Start button and search for "regedit". Open the regedit.exe and follow the instructions in the first link Jeremy sent (https://eli.thegreenplace.net/2010/12/14/problem-passing-arguments-to-python-scripts-on-windows). I used to have the same issue and now it's fixed. Let me know if you need help with this

**Comment by fsoepyan** [comment]
- I went to the Windows Start button and searched for "regedit"
- Registry Editor is opened
- I looked for: HKEY_CLASSES_ROOT\py_auto_file\shell\open\command
- I double-clicked "(Default)"
- I changed the "Value data" to: "C:\Users\fsoepyan\AppData\Local\Continuum\anaconda2\python.exe" "%1" %*
- I ran OUU
- The results still are not recorded in the Flowsheet table

**Comment by sotorrio1** [comment]
Did you change both registry keys? 
HKEY_CLASSES_ROOT\Applications\python26.exe\shell\open\command
HKEY_CLASSES_ROOT\py_auto_file\shell\open\command

The results are not recorded but, do you get the error message anymore?

**Comment by fsoepyan** [comment]
- I changed both registry keys
- I still get the error message

**Comment by sotorrio1** [comment]
odd... @fsoepyan what happens when you run the simple example from the link in the command line? Does it work?

**Comment by fsoepyan** [comment]
I ran the example problem from the link, and it works:

<img width="406" alt="ouu_07_30_2018" src="https://user-images.githubusercontent.com/30811140/43405879-e9852528-93e8-11e8-9b30-6e3265a858ab.png">

**Comment by sotorrio1** [comment]
@fsoepyan so you still get this error?
![screen shot 2018-07-30 at 11 16 09 am](https://user-images.githubusercontent.com/33531919/43415288-09317542-93ea-11e8-8052-f4f3ceb6813a.png)

**Comment by fsoepyan** [comment]
No.

**Comment by sotorrio1** [comment]
ah ok, what error do you get then?

**Comment by fsoepyan** [comment]
- I used to get the error message that I showed in my June 13 comment, which is the same error message that you showed in your July 30 comment
- But when I ran OUU today with 2 different files, I no longer get this error message

**Comment by sotorrio1** [comment]
got it. So the only issue now is that the runs are not recorded?

**Comment by fsoepyan** [comment]
Yes.

**Comment by ou3llnl** [comment]
@fsoepyan: I just tried it and I get runs recorded in the Flowsheet run table. I loaded Rosenbrock_no_vectors, went to OUU, set Rosenbrock.x1 to Z1, and then "Run OUU". When done, I went to flowsheet and hit the "Results and Filtering" table and runs show up. Do you get any kind of errors or warnings in the console?

**Comment by eslickj** [comment]
There is a chance this is the same as issue #251. @fsoepyan can you try again now that that has been fixed? That's only if the samples disappear after saving and loading. If this is still a problem can send log messages from session where the problem occurs.

**Comment by fsoepyan** [comment]
- I tried running OUU with the latest pull requests (#256 and #257)
- The OUU runs are still not being recorded in the Flowsheet table
- However, the OUU runs are successful
- Here is the message from "Log Viewer":

2018-08-09 15:25:57,506 - DEBUG - foqus.foqus_lib.framework.graph.graph - Running flowsheet(s) locally
2018-08-09 15:25:57,553 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Starting simulation consumer...
2018-08-09 15:25:57,553 - DEBUG - foqus.foqus_lib.framework.graph.node - Generated Job JSON:
[
{
"ConsumerId": "{CA99B34B-A19A-4213-B437-BD4F6FB7078D}",
"Initialize": false,
"Input": {
"B2.alpha": 5.0,
"B2.beta": 5.0,
"B2.d1": 1.0,
"B2.d2": 1.0,
"B2.d3": 1.0,
"B2.d4": 1.0,
"B2.delta": 5.0,
"B2.omega1": 1.0,
"B2.omega2": 1.0,
"B2.omega3": 1.0,
"B2.omega4": 1.0,
"MinStepSize": 0.001,
"RunMode": "Steady Optimization",
"Script": "",
"Snapshot": "",
"TimeSeries": [
0.0
],
"TimeUnits": "Hours",
"homotopy": 0,
"printlevel": 0
},
"Reset": false,
"Simulation": "ouu_toy2",
"Visible": false
}
]
2018-08-09 15:25:57,773 - DEBUG - foqus.foqus_lib.framework.graph.node - Started Job: 1845 Turbin SID: 1bd40982-2e91-4925-b99c-fa86269a0216
2018-08-09 15:26:02,046 - INFO - foqus.foqus_lib.framework.sim.turbineConfiguration - Job 1845 Started Running
2018-08-09 15:26:02,046 - DEBUG - foqus.foqus_lib.framework.graph.node - Job finished successfully: 1845
2018-08-09 15:26:02,046 - INFO - foqus.foqus_lib.framework.graph.node - Job 1845 Finished Successfully
2018-08-09 15:26:02,046 - DEBUG - foqus.foqus_lib.framework.graph.node - Outputs: status = 0
B2.z = 2.85705080757
B2.x4 = 4.875
B2.x3 = -3.25
B2.x2 = -2.5
B2.x1 = -1.0

**Comment by fsoepyan** [comment]
- I tested the OUU tab using the same example Aspen Plus file from issue #126 
- I have 3 decision variables, 2 uncertain (UQ) variables, and I ran OUU using 50 samples
- The OUU results are saved in the Flowsheet table with "listener" as the set name
- According to the OUU tab, there are 3150 iterations
- But the Flowsheet table only shows 1300 data points
- Can anyone please let me know why these numbers are different?

**Comment by ksbeattie** [comment]
@sotorrio1 is blocked from being able to reproduce this possibly because of #147 
@fsoepyan is now mostly concerned about the difference described above
@ou3llnl will follow up with Charles Tong on if this is an issue in psuade.

**Comment by ou3llnl** [comment]
Per Charles, the only reason he can think of for why # of iterations is greater than number of data points is that PSUADE can detect duplicate runs and not repeat calculations that have already been performed. However, we need to find out if that really is the case here.

**Comment by ksbeattie** [comment]
@sotorrio1  can you now reproduce this?  And maybe look into if psuade skipping dup calculations explains the discrepancy that @fsoepyan mentions?

**Comment by ksbeattie** [comment]
@sotorrio1 is continuing to work on this with Charles Tong

**Comment by sotorrio1** [comment]
PR #339 should take care of cleaning up the psuade files in the working directory

**Comment by ksbeattie** [comment]
@fsoepyan will test this now that PR #339 has been merged.

**Comment by fsoepyan** [comment]
I have tested OUU in FOQUS, and the old "psuadeEval.out" files are automatically deleted at the beginning of each OUU run.

The PR works. Thank you!
