### ISSUE TITLE
Turbine: Add/Update Model to Turbine produces BadStatusLine error

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#147]
Within FOQUS I went to "Open Session..." and selected Byron's example #2 (BFB_Opt_03.07.2018.foqus). After that I went to "Add/Update Model to Turbine..." and the "Turbine Upload" window pops up. Under the "Sinter Configuration File" I hit "Browse..." and selected the file "BFB_v11_FBS_01_26_2018.json". I loaded the file and when I click "Okay" in the "Turbine Upload" window, the following error message pops up (see below):

<img width="339" alt="screen shot 2018-03-20 at 9 21 57 am" src="https://user-images.githubusercontent.com/33531919/37690128-60590f6a-2c66-11e8-85b1-8f57c77231f0.png">

**Comment by ksbeattie** [comment]
@sotorrio1 can you take another stab at this?

**Comment by sotorrio1** [comment]
I tried loading a few of the Heat_Integration examples and I for all of them I get the following error:

<img width="353" alt="screen shot 2018-07-10 at 3 13 55 pm" src="https://user-images.githubusercontent.com/33531919/42540665-36f9e5fe-8454-11e8-8454-e11d7218c15b.png">

**Comment by ksbeattie** [comment]
@eslickj, can you take a look at this?

**Comment by ksbeattie** [comment]
@boverhof and @sotorrio1 will work together to try and solve this.

**Comment by sotorrio1** [comment]
@boverhof helped me this morning and this specific issue is resolved.

LLNL has a couple processes running that take ports we use, using “netstat -a -b” as Administrator we were able to see the processes.  Changed to 8001 and found another process, finally changed to 8010 and it works!

- port 8000
	msirest.exe is known as Cisco MSI Management Windows Service

- port 8001
	SecomSDK.exe is part of Sennheiser Softphone SDK and developed by Sennheiser Communications
