### ISSUE TITLE
JIRA Issue: Submitting jobs slows down with number of jobs in Turbine DB

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#15]
From JIRA:
- Reporter: John Eslick (@eslickj)
- Assignee: Joshua Boverhof (@boverhof)
- Original title: Submitting jobs slows down with number of jobs in Turbine DB
- Created: 09/Oct/15 8:47 AM
- Updated: 11/Jul/16 3:11 PM

Description:

As you submit jobs to turbine, it seems to take longer and longer to submit jobs. After about 10,000 jobs this seems to lead to significant slow down on the Turbine server. I suspect and inefficient SQL query may be the cause. I think it also happens in TurbineLite. When I first install it job submission is very fast and slows down the more I use it.

Chat history:

Abdelrahman Elbashandy added a comment - 26/Jan/16 4:52 PM 
Does this happen only on a single submission or in general? 
Josh, should we backup the data and clean up the database periodically?

Joshua Boverhof added a comment - 26/Jan/16 9:55 PM 
I suspect it is an ORM layer inefficiency. Since it's present in TurbineLite we shouldn't have too much trouble replicating the issue. Just grab a SQL Compact database file and store it with the test code. 
Once we have a few unittests that we can use to easily time operations we can dig in a little and replace some of the inefficient ORM code.

**Comment by ksbeattie** [comment]
Closing this due to age and the unlikelihood that anyone will be submitting 10K jobs anytime soon.
