### ISSUE TITLE
Help "?" Does Nothing in Flowsheet Data Viewer

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#150]
![help_button_does_nothing](https://user-images.githubusercontent.com/37089145/37723559-45657e44-2cf4-11e8-9157-329c4ebfe3e8.PNG)

When viewing results in the results column view from the flowsheet there is a "?" that does nothing. I've circled it in the picture.

**Comment by fsoepyan** [comment]
Should we considering removing the "?" button from the dialog box corner?

**Comment by CSRussell2319** [comment]
I think that was what @eslickj initially suggested. You're probably safe to remove it or comment it out.
