### ISSUE TITLE
Option for SSH Download of Dependencies

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#161]
When running `python setup.py install` the installer looks for turb_client and attempts to install it. It uses an https link for downloads and installs. For my current network configuration that doesn't work and I need to use ssh instead. Is this a common enough situation that we should have a standard way to deal with it (maybe user input of how they would like to download dependencies)?

For my network I have to change the following:
setup.py line 53
Old:
`dependency_links=['git+https://github.com/CCSI-Toolset/turb_client@2.0.0-alpha#egg=TurbineClient']`
New:
`dependency_links=['git+ssh://git@github.com/CCSI-Toolset/turb_client@2.0.0-alpha#egg=TurbineClient']`

**Comment by CSRussell2319** [comment]
#247 adds in the code to easily enable ssh download of dependencies, but we should document this. SSH is still not the default behavior and the only way to use ssh with this code is to manually comment the https line and uncomment the ssh line

**Comment by ksbeattie** [comment]
I'd think that the most correct way of installing turb_client should be via a `pip install` and/or `conda install`.  That should fix this, right?  @boverhof, thoughts?

I'm going to put this on the Nov release board, so we can follow this idea....

**Comment by CSRussell2319** [comment]
Yes, I believe that would fix this issue.

**Comment by CSRussell2319** [comment]
Tried using pip to install the turbine client and received the same error message. 
Here's my code for the yaml file: `"--editable=git+https://github.com/CCSI-Toolset/turb_client@2.0.0-alpha#egg=TurbineClient"`
Looks like pip just does a git clone so it's no different than what the setup file does natively. If we could get the repo added to a pip or conda repo that might fix the issue.

**Comment by ksbeattie** [comment]
Fixed with PR #283
