### ISSUE TITLE
Flowsheet Result Data Tutorial Fix

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/foqus#166]
Following the instructions for this tutorial (Pg 54) and opening the examples\Data\Simple flow.foqus file displays a list of results in the Flowsheet Result Data Viewer. The tutorial should be changed from sorting with ResultName to sorting with result. Specifically the following changes should be made (I still can't upload code):

manual\Chapt_flowsheet\tutorial\data.tex line 40
Old:
`	\item Enter \verb|["-ResultName"]| as the \textbf{Sort Term\underline{}}. Include the square brackets. The square brackets indicate that there is a list of sort terms, although in this case there is only one. If multiple search terms are given, the additional terms will be used to sort results having the same value for the previous terms. The ``-'' in front of \textbf{\underline{ResultName}} indicates the results should be sorted in reverse.  The names of the sort terms come from the column headings, and are case sensitive.`

New:
`	\item Enter \verb|["-result"]| as the \textbf{Sort Term\underline{}}. Include the square brackets. The square brackets indicate that there is a list of sort terms, although in this case there is only one. If multiple search terms are given, the additional terms will be used to sort results having the same value for the previous terms. The ``-'' in front of \textbf{\underline{result}} indicates the results should be sorted in reverse.  The names of the sort terms come from the column headings, and are case sensitive.`

manual\Chapt_flowsheet\tutorial\data.tex line 55
Old:
`	\item The results are shown in Figure \ref{fig.filter.1.result}. The data should be sorted in reverse alphabetical order by \textbf{\underline{ResultName}}. Some of the columns are hidden to make the relevant results easier to see.`

New:
`	\item The results are shown in Figure \ref{fig.filter.1.result}. The data should be sorted in reverse alphabetical order by \textbf{\underline{result}}. Some of the columns are hidden to make the relevant results easier to see.`

manual\Chapt_flowsheet\tutorial\data.tex line 71
Old:
`	\item Enter \verb|["Error", "-ResultName"]| in the \bu{Sort Term} field.  This will sort the data first by \textbf{\underline{Error}} code then by \textbf{\underline{ResultName}} in reverse alphabetical order.`

New:
`	\item Enter \verb|["Error", "-result"]| in the \bu{Sort Term} field.  This will sort the data first by \textbf{\underline{Error}} code then by \textbf{\underline{result}} in reverse alphabetical order.`

manual\Chapt_flowsheet\tutorial\data.tex line 86
Old:
`	\item The results are shown in Figure \ref{fig.filter.2.result}. The data should be sorted so all \textbf{\underline{Error}} code zero results are first then sorted in reverse alphabetical order by \textbf{\underline{ResultName}}.`

New:
`	\item The results are shown in Figure \ref{fig.filter.2.result}. The data should be sorted so all \textbf{\underline{Error}} code zero results are first then sorted in reverse alphabetical order by \textbf{\underline{result}}.`

LA-UR-18-22653

**Comment by fsoepyan** [comment]
- Taken care of in Pull Request #192.
- I will close the issue.
