### ISSUE TITLE
Remove duplicate files

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#168]
The below are sets of duplicate files in the repo.  For the small files this is not a big deal but the large ones, it seems worth the effort figure out how to only have one copy checked in.

~~~~
1732596808 9486 ./examples/Testing/Excel_Test_01/Excel_Test_01.xlsx
1732596808 9486 ./examples/Excel_Testing/Test_01/MyExample.xlsx
~~~~

~~~~
1986948760 14416 ./foqus_lib/framework/surrogate/bssanova/xdat.csv
1986948760 14416 ./foqus_lib/framework/surrogate/acosso/xdat.csv
~~~~

~~~~
2098434091 22678558 ./examples/Testing/BFB/BFBv6.2.acmf
2098434091 22678558 ./examples/Optimization/Model_Files/BFBv6.2.acmf
~~~~

~~~~
2117569950 452 ./foqus_lib/framework/surrogate/bssanova/mkdata.R
2117569950 452 ./foqus_lib/framework/surrogate/acosso/mkdata.R
~~~~

~~~~
2118880274 2493 ./foqus_lib/gui/icons/load.svg
2118880274 2493 ./foqus_lib/gui/icons/folder.svg
~~~~

~~~~
2159491434 17262 ./examples/Testing/Mass_Bal_Test_01.foqus
2159491434 17262 ./examples/Recycle/Mass_Bal_Test_01.foqus
~~~~

~~~~
2443891952 14628 ./examples/Heat_Integration/Model_Files/BFB_System_ACM/BFB_2ads_2rgn_old.json
2443891952 14628 ./examples/Heat_Integration/Model_Files/BFB_System_ACM/BFB_2ads_2rgn.json
~~~~

~~~~
2736431264 3401 ./foqus_lib/framework/surrogate/bssanova/ydat.csv
2736431264 3401 ./foqus_lib/framework/surrogate/acosso/ydat.csv
~~~~

These were found using the following command:
~~~~
find . -type d \( -path '.*/\.svn' -o -path '.*/\.git' \) -prune -o -type f -print0 | xargs -0 cksum | sort | awk '{ print $1 }' | uniq -cd
~~~~

**Comment by fsoepyan** [comment]
- In the reorganization (PR #574) of the "examples" folder, I think I did my best to delete duplicate files.
- However, I still have duplicate files in some places, on purpose.
- For example, in the PR, I have the Rosenbrock_no_vectors.foqus file in both the examples/tutorial_files/UQ and the examples/tutorial_files/Surrogates folders.
- This is to help the user, because if the user needs to use the Rosenbrock file for the Surrogates tutorial, then by having duplicates, the user won't need to look for the file in the UQ folder.

**Comment by anujad95** [comment]
Yes, in the reorganization PR most of the duplicate files have been deleted, so this issue can be closed if everyone agrees.

**Comment by ksbeattie** [comment]
I'll take another look at this and make sure they are (mostly) gone.

**Comment by ksbeattie** [comment]
So, there are still several places where we have identical files across the repo.  I've only listed here the ones that are over 1M in size though.

Given that these are under `examples/{tutorial_files,test_files}/` might it be possible to consolidate them into a new `examples/common/` or some such dir?

22M file in 4 places:
```
examples/test_files/Optimization/Model_Files/BFBv6.2.acmf
examples/tutorial_files/Flowsheets/Tutorial_2/BFBv6.2.acmf
examples/tutorial_files/Optimization/Tutorial_1/BFBv6.2.acmf
examples/tutorial_files/SimSinter/Tutorial_1/BFBv6.2.acmf
```
5.4M file in 2 places:
```
examples/tutorial_files/UQ/Tutorial_2/gmoat5012_9levels.filtered
examples/tutorial_files/UQ/Tutorial_3/gmoat5012_9levels.filtered
```
2 identical 12M files in the same dir!
```
examples/test_files/Heat_Integration/Model_Files/BFB_System_ACM/BFB_2ads_2rgn_old.acmf
examples/test_files/Heat_Integration/Model_Files/BFB_System_ACM/BFB_2ads_2rgn.acmf
```

**Comment by ksbeattie** [comment]
I'm not going to worry about the duplicate files anymore.
