### ISSUE TITLE
Parameter Estimation Tutorial Manual Update

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/foqus#173]
Page 82 of the user manual includes "Figure 63: Adding Node Calculation" that needs to be updated with the new GUI layout. The manual text appears to be updated already.

Old:
![pe_tutorial_node_script_manual](https://user-images.githubusercontent.com/37089145/38103896-dd095800-3344-11e8-905e-856afeeab658.PNG)

New:
![pe_tutorial_node_script](https://user-images.githubusercontent.com/37089145/38103909-e33fdf64-3344-11e8-997e-1ec69663a633.PNG)

**Comment by eslickj** [comment]
@fsoepyan go ahead and update this too.  Let me know if you need any help with LaTeX.

**Comment by fsoepyan** [comment]
- Taken care of in Pull Request #192.
- I will close the issue.
