### ISSUE TITLE
Parameter Estimation Tutorial Doesn't Optimize

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/foqus#174]
I'm running the parameter estimation tutorial under the optimization section and I encounter an error where no optimization occurs. I've used a sample file I had from a previous release as well as a new one created by me for testing. The following is what is displayed:

![pe_tutorial_optimization_error](https://user-images.githubusercontent.com/37089145/38104985-0f83fef4-3348-11e8-8bb7-581914cabe11.PNG)

I have installed the NLopt package and tried it as well as others without success. Can someone reproduce this?

**Comment by eslickj** [comment]
@fsoepyan, can you update this.  I think the trouble is probably that the tutorial and example file still has the time step in the objective expression, but I didn't check that carefully.  If you have any trouble, just let me know.

**Comment by fsoepyan** [comment]
- Taken care of in Pull Request #192.
- I will close the issue.

**Comment by CSRussell2319** [comment]
Since this came up again during my automated testing I should point out that the issue was in the objective function. The original reads as follows:
`sum([(f[i]['model']['y'][0] - x[i]['model']['ydata'][0])**2 for i in range(len(x))])`
The new function reads as follows:
`sum([(f[i]['model']['y'] - x[i]['model']['ydata'])**2 for i in range(len(x))])`

The [0] returned a constant instead of a variable and made the optimization impossible.

**Comment by ksbeattie** [comment]
@CSRussell2319, I just want to confirm: your comment above is just for reference, there's no need to re-open this issue, or create a new one?

**Comment by CSRussell2319** [comment]
@ksbeattie, correct. I just included this comment to more explicitly state what the issue was and how it was solved with a PR. No action is required and this issue can remain closed.
