### ISSUE TITLE
Epistemic-Aleatory mode for UQ throws an error

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/foqus#175]
I attempt to follow the "Response Surface Based Analysis" walkthrough and switch the UQ analysis to Epistemic-Aleatory in expert mode as instructed on page 126 of the manual. I choose a random input to be Epistemic and then click analyze. The sample file is examples\UQ\lptau100_10inputs_4outputs.dat.

The error looks like this:

![epistemic-aleatory error](https://user-images.githubusercontent.com/37089145/38108949-aa070ba0-3353-11e8-96f7-3f52e1d7642b.PNG)

**Comment by CSRussell2319** [comment]
I'm using the latest foqus code synced with GitHub (I synced this morning and still have the error). Could this be an issue with the example file?

**Comment by sotorrio1** [comment]
I'm using same example file... 
From your error messages it looks like you're having issues with matplotlib. Have you tried updating the library or something?

**Comment by CSRussell2319** [comment]
It looks like the main issue is with line 426 of foqus_lib\framework\uq\Plotter.py
Current:
`self.sliderax = self.fig.add_axes([left, bottom, width, height], axisbg='lightgoldenrodyellow')`

According to recent documentation "axisbg" has been depreciated in favor of "facecolor". If I change the line to the following I don't have an error:
`self.sliderax = self.fig.add_axes([left, bottom, width, height], facecolor='lightgoldenrodyellow')`

![mixed_aleatory-epistemic_uncertainty_analysis_based_on_linear_response_surface](https://user-images.githubusercontent.com/37089145/38255929-572bec28-371a-11e8-92c5-d79df2da23d6.png)

I am unable to see the slider in this image except for a thin sliver of black when moving the slider.

**Comment by sotorrio1** [comment]
Interesting and odd at the same time... "axisbg" still works for me and I can see the slider without an issue. Let me take a look at this and I'll get back to you :)

**Comment by CSRussell2319** [comment]
@sotorrio1 I'm using matplotlib 2.2.2 for python 2.7 if that helps

**Comment by sotorrio1** [comment]
@CSRussell2319 I was using maplotlib 2.1.0. I upgraded my maplotlib and now I get same error message. Let me see if I can fix the slider issue

**Comment by sotorrio1** [comment]
@CSRussell2319 can you try a different example file? The slider should work with a different example file

**Comment by CSRussell2319** [comment]
Yes, I tried all of the examples in the examples\UQ folder as well as some in the examples\UQ\test_suite\... folders all with the same results: no slider bar visible except for a sliver of black when adjusting the slider. The background error has been resolved.

**Comment by sotorrio1** [comment]
What about the RS Visualization with 3 inputs? Does the slider in the isosurface plot work?

**Comment by CSRussell2319** [comment]
Yes, the slider in the RS Visualization with 3 inputs does work correctly.

**Comment by ksbeattie** [comment]
This was reportedly fixed in #195
