### ISSUE TITLE
Basic Data Window is Too Small

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#176]
When using SolventFit the UI window doesn't show all input boxes by default. There's also no side bar to indicate that there is more to the window if expanded. User currently needs to resize the window to be able to see all of the options for this tool. The window in the manual's screenshot (pg 144) is perfectly sized.

Current Default:
![basic_data_window_too_small](https://user-images.githubusercontent.com/37089145/38112027-eeebb554-335d-11e8-813d-d2c3116bda95.PNG)
Expanded to See Everything:
![basic_data_window_see_all](https://user-images.githubusercontent.com/37089145/38112136-335387b2-335e-11e8-9fb9-3729763259b2.PNG)
Manual Screenshot:
![basic_data_window_manual](https://user-images.githubusercontent.com/37089145/38112382-0120b14c-335f-11e8-8a95-ecec9a287c9a.jpg)

**Comment by ngbrenda** [comment]
I am having the same issue too (running on Mac). Is there a way to add scrollbar?

**Comment by sotorrio1** [comment]
Added a scroll bar and testing it. Hopefully I can create a PR today to solve this issue.

**Comment by sotorrio1** [comment]
@CSRussell2319 PR #380 should fix this issue in Windows and also in iOS. Please test and let me know :)
Thanks!

**Comment by ksbeattie** [comment]
@sotorrio1 is waiting on #408 on if this will even need to be done.

**Comment by sotorrio1** [comment]
PR #474

**Comment by ksbeattie** [comment]
Closing this for now, possibly re-opening it if we want to keep the basic data tab.
