### ISSUE TITLE
QCursor Error When Running SolventFit

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#177]
When attempting an inference using the example alamo.dat file in SolventFit I get the following error:

![solventfit_error](https://user-images.githubusercontent.com/37089145/38112691-fb104b36-335f-11e8-90e2-a370890a9783.PNG)

**Comment by eslickj** [comment]
Should be fixed with PR #191, which is awaiting review.

**Comment by eslickj** [comment]
@fsoepyan, the second issue here is something different than the qcursor problem.  Can you refile the second issue as a new issue and assign it to @ou3llnl?  Close this issue once that's done. Having two issues mixed up together could get confusing.
