### ISSUE TITLE
Surrogates: error with filtering ALAMO

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#178]
When following the ALAMO tutorial trying to add a filter as instructed on page 189 throws the following error:

![surrogate filter error](https://user-images.githubusercontent.com/37089145/38373809-549ab412-38af-11e8-9ca1-57e1f6ea7ad2.PNG)

**Comment by eslickj** [comment]
@fsoepyan can you see if you can reproduce this?  Just let me know if you can't find the problem or can't fix it.

**Comment by fsoepyan** [comment]
- I did the Alamo tutorial in Section 8.2 of the user's manual
- I did the steps in Page 180
- I made sure that the word set has no quotes, and the word UQ_Ensemble has quotes
- I applied the "Initial" filter
- I got similar error message that Chris (@CSRussell2319) got:

<img width="961" alt="alamofilter_04_19_2018" src="https://user-images.githubusercontent.com/30811140/39007225-d749373a-43f4-11e8-9cac-7f44eb750144.png">

- I checked the filter dialogue box, and I saw that the word set is enclosed in quotes:

<img width="631" alt="alamofilter2_04_19_2018" src="https://user-images.githubusercontent.com/30811140/39007252-e7eff01a-43f4-11e8-84f1-2ab775506a3c.png">

- Did FOQUS automatically enclose the word set in quotes?

**Comment by fsoepyan** [comment]
I tested FOQUS, and the issue has been resolved.
