### ISSUE TITLE
ALAMO Tutorial Manual Update

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/foqus#179]
In the ALAMO tutorial (manual\Chapt_surrogates\tutorial\alamo.tex) line 155 should be updated to reflect the new labeling.

Old:
`\item In the ``Term 1'' column enter: SetName (no quotes).`
New:
`\item In the ``Term 1'' column enter: set (no quotes).`

**Comment by eslickj** [comment]
@fsoepyan go ahead and make this change

**Comment by fsoepyan** [comment]
- Taken care of in Pull Request #192.
- I will close the issue.
