### ISSUE TITLE
Surrogate Samples Aren't Auto-Generated

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/foqus#183]
Following the "Tutorial - Surrogates with UQ Tools" section in the FOQUS manual part 3 sub-parts b and c imply that by clicking done the "Flowsheet Results" area will fill with the samples. Instead the user needs to switch to the Uncertainty tab and launch the runs for them to appear. I also have an iReveal issue that may or may not be related. I've provided screenshots below. The first image is after attempting to add samples.

![surrogate samples issue 1](https://user-images.githubusercontent.com/37089145/38756305-4e39b8b6-3f26-11e8-9239-7df087426646.PNG)
![surrogate samples issue 2](https://user-images.githubusercontent.com/37089145/38756307-4e688fa6-3f26-11e8-8d9c-5742fa0b2a4f.PNG)
![surrogate samples issue 3](https://user-images.githubusercontent.com/37089145/38756309-4e7e5692-3f26-11e8-8f80-5525b4d5fecb.PNG)

**Comment by fsoepyan** [comment]
@eslickj will look into this

**Comment by ksbeattie** [comment]
Waiting for review/merge of #194 ...

**Comment by fsoepyan** [comment]
Taken care of in PR #194.
