### ISSUE TITLE
Flowsheet: The Flowsheet Results Dialog needs capability for adding calculated columns

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#187]
Suggestions:
- Add a button to bring up new window that has the same python script capability, allowing user to define variable transformations. 
- The variable transformations should then be accessible to define rules of the form x1 < f(x2, x3) where f is a specific variable transformation on x2 and x3. So f(x2, x3) would be a calculated column.

**Comment by eslickj** [comment]
Should be done in PR #193

**Comment by ksbeattie** [comment]
@eslickj says that the filer dialog will be re-written and this will go away as an issue...

**Comment by fsoepyan** [comment]
I tested FOQUS, and I no longer run into the issue.
