### ISSUE TITLE
Flowsheet: Code in foqus_lib/framework/sampleResults/results.py

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/foqus#188]
- There are extra flags in CAPS. Delete the unused ones or add comments to those that are not obvious (or are reserved for future use). 
- Delete Results.exportPSUADE() if it is obsolete or add a comment to justify why it's still there.

**Comment by eslickj** [comment]
Should be done in PR #193

**Comment by fsoepyan** [comment]
Since PR #193 has been merged, can we close this issue?
