### ISSUE TITLE
Surrogates: "Current Filter" dropdown menu should default to "all"

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#208]
In the Surrogates module, under the Data tab, the "Current Filter" dropdown menu defaults to "blank" so the "Number of Rows" doesn't display anything. I suggest it defaults to "all" so "Number of Rows" equals the number of samples. 
<img width="1243" alt="screen shot 2018-05-22 at 6 15 05 pm" src="https://user-images.githubusercontent.com/33531919/40398409-c04568bc-5dec-11e8-8875-36e747eb130a.png">

**Comment by fsoepyan** [comment]
- I did a UQ example
- As Pedro (@sotorrio1) mentioned, the "Number of Rows:" is blank when you go to the "Surrogates" tab for the first time
- But after swapping the filter from blank to "All", the "Number of Rows:" has the correct number
- I swapped the filter back to blank, and the "Number of Rows:" still has the correct number
- This gives me the impression that the "Number of Rows:" will be blank the first time you go to the "Surrogates" tab regardless of the default value of the filter

**Comment by sotorrio1** [comment]
@fsoepyan That's why we are suggesting the menu to start by default at "all" instead of blank

**Comment by ngbrenda** [comment]
@eslickj, can you please look into this?

**Comment by eslickj** [comment]
I didn't change the default filter to all, but I did fix the missing row count in PR #257

**Comment by fsoepyan** [comment]
- PR #257 has been approved
- I will close this issue
