### ISSUE TITLE
Response Surface Gaussian Process Validation Error

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#209]
![gaussian process rsanalyzer error](https://user-images.githubusercontent.com/37089145/40453670-30dccd20-5ea3-11e8-9ccc-71962b1850c4.PNG)
The above error occurs when attempting to validate runs in FOQUS using the Gaussian process. This is using the rosenbrock_no_vectors.foqus example file with 1000 runs from a UQ ensemble. All inputs are left as variables and LHS is used for the sampling scheme.

**Comment by sotorrio1** [comment]
@CSRussell2319 Could you try installing the new psuade version (https://github.com/LLNL/psuade/releases/tag/1.7.12) and try the Gaussian process again? It will take a while but it should work.

**Comment by CSRussell2319** [comment]
@sotorrio1 I tried installing the latest psuade version, but the exe file is instantly deleted by my anti-virus software. I'll work with support on my side to see what's going on, but in the meantime can you verify that the exe on GitHub is safe and actually psuade?

**Comment by sotorrio1** [comment]
@CSRussell2319 I had same issue in the past, but I just ignored it. I've uploaded the exe file to GitHub myself, so I assure you it is safe and it is psuade.

**Comment by CSRussell2319** [comment]
@sotorrio1 I finally was able to install the latest version of PSUADE. It fixed the issue with the Gaussian process, but MARS with Bagging now has the same exact error.

**Comment by ou3llnl** [comment]
@CSRussell2319 : Can you attach the "psuadelog" file in your working directory that is generated right after running MARS with Bagging and getting this error? Thanks

**Comment by CSRussell2319** [comment]
@ou3llnl here's the log file:
[psuadelog.txt](https://github.com/CCSI-Toolset/FOQUS/files/2098385/psuadelog.txt)

**Comment by ksbeattie** [comment]
I'm adding this to the June release board as "in progress" since that seems to be the case...

**Comment by ksbeattie** [comment]
This may require a new psuade version...

**Comment by sotorrio1** [comment]
@CSRussell2319 : I've replaced the "psuade_project-1.7.12-win32.exe" file with a new one. This psuade version should take care of MARS with Bagging error.

**Comment by CSRussell2319** [comment]
Updated psuade version fixes the error.
