### ISSUE TITLE
Surrogate Testing Suite

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#217]
Create a testing suite that goes through the different features of the Surrogate tab in FOQUS.

**Comment by anujad95** [comment]
Can we generalize this and rename it as automated testing in general?

**Comment by CSRussell2319** [comment]
This task was originally designed to be specific to the surrogate testing suite. There are other issues that involved making tests for other suites that have already been closed. If this is no longer relevant/useful than the issue can be closed.

**Comment by ksbeattie** [comment]
Hopefully with putting into place coverage metrics on our test cases, our efforts to increase those numbers will get us to test surrogates and all parts of FOQUS.
