### ISSUE TITLE
Input PDF Parameters Via Script

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#219]
I'm trying to use a testing script to put a value into these two boxes (and wherever else PDF selection appears) so I can test different PDFs. I'm having trouble figuring out the syntax of how to push a value to these boxes. 

Does anyone know how to do this? 

Best I can tell it's the box title (mean/std ..) that's throwing off the standard methods for pushing values here.

![pdf parameters](https://user-images.githubusercontent.com/37089145/41000464-467a4068-68cb-11e8-892c-8ef702948ea8.PNG)

**Comment by ou3llnl** [comment]
So the Param cells are actually 1-row, 2-column tables embedded within the cell. To modify, the Param1 in row 0, You would do something like this:
w.distTable.cellWidget(0, 6).item(0, 1).setText("0.3523523")

**Comment by CSRussell2319** [comment]
@ou3llnl Thanks, that at least pointed me in the right direction. the code needed for this was:
`w.inputPrior_table.cellWidget(2,4).setItem(0,1, QtWidgets.QTableWidgetItem("0.3523523"))`

Apparently it's a QTableWidgetItem that needs to be set
