### ISSUE TITLE
UQ parity plots

### ISSUE THREAD

**Issue by MAZamarripa** [CCSI-Toolset/FOQUS#224]
Issue when selecting the user regression in UQ, the parity plot seems to be incorrect. @ngbrenda @fsoepyan 
First plot is the one generated with UQ Analyze, while the second and third ones are generated with ALAMO and excel, respectively.

![uq_issue_parityplot](https://user-images.githubusercontent.com/24570008/41313975-5cf2c37c-6e59-11e8-9ae2-ce053c395790.png)
![uq_issue_alamoparity](https://user-images.githubusercontent.com/24570008/41313980-5e660e12-6e59-11e8-95b2-8754048fa026.png)
![image](https://user-images.githubusercontent.com/24570008/41314072-a11372c2-6e59-11e8-9d28-172ace6dfaa6.png)

**Comment by ou3llnl** [comment]
@MAZamarripa: We got the session and surrogate code. Can you send us the contents of the "Boiler_surrogate_180612110218_files" subdirectory in your working directory? Thanks!

**Comment by MAZamarripa** [comment]
[Boiler_surrogate_180612110218_files.zip](https://github.com/CCSI-Toolset/FOQUS/files/2141126/Boiler_surrogate_180612110218_files.zip)

**Comment by MAZamarripa** [comment]
I think the issue is in the user_regression file generator/parser (uq_output file). 
After runing alamo two files are generated (user plug-in and user regression/uq_output file). We had this issue before, it happens because the order of the variables/equations is incorrect (see, lines 61 to 117 in the attached file).
@ou3llnl @fsoepyan @sotorrio1 @ngbrenda 
[alamo_surrogate_uq_Boiler.zip](https://github.com/CCSI-Toolset/FOQUS/files/2145765/alamo_surrogate_uq_Boiler.zip)

**Comment by ou3llnl** [comment]
This what I get for output BOILER.2NDAIR
![image](https://user-images.githubusercontent.com/32141584/42065616-d2077d26-7af0-11e8-9a02-bcf483ee8712.png)

It seems the plot for others looks fairly linear though with a different slope than it should be. Are those plots correct?

**Comment by MAZamarripa** [comment]
Now I can say that the order is incorrect.
First, 2NDAir is a very simple model (5.6525999999993210565208 * X[0]), the order is incorrect after item X[1]. Is a ratio of the inlet fuel flow rate.

The in_labels list:
in_labels = [u'fuel_flow', u'twall_1', u'twall_10', u'twall_2', u'twall_3', u'twall_4', u'twall_5', u'twall_6', u'twall_7', u'twall_8', u'twall_9', u'twall_PH']

Observe the model for heat loss 1 (model in uq file and the model reported by ALAMO): You can observe that the third term in the model "49442.3141*X[2]" should be X[3] and not X[2]. Since, the Twall_2 is X[3] and the uq file is using the Twall_10 ("X[2]")
if oid == 17:
      g = lambda X: 
715309.18530072155408561 * X[0] - 100784.96900806584744714 * X[1] + 49442.314175000174145680 * X[2] + 19521.866475431204889901 * X[3] + 18101.918764524303696817 * X[4] + 1089.2628460945456936315 * X[5] + 1222.9030608759078404546 * X[6] + 630.67556595660346374643 * X[7] + 478.84896710702037125884 * X[8] + 578.77460885502443943551 * X[11] + 13856494.627940945327282 * math.log(X[0]) + 55338167.254907786846161 * math.log(X[1]) - 29269094.807519607245922 * math.log(X[2]) - 11767340.563981954008341 * math.log(X[3]) - 13330382.699841693043709 * math.log(X[4])
Alamo:
715309.18530072155408561 * Boiler_fuel_flow - 100784.96900806584744714 * Boiler_twall_1 + 49442.314175000174145680 * Boiler_twall_2 + 19521.866475431204889901 * Boiler_twall_3 + 18101.918764524303696817 * Boiler_twall_4 + 1089.2628460945456936315 * Boiler_twall_5 + 1222.9030608759078404546 * Boiler_twall_6 + 630.67556595660346374643 * Boiler_twall_7 + 478.84896710702037125884 * Boiler_twall_8 + 578.77460885502443943551 * Boiler_twall_PH + 13856494.627940945327282 * log(Boiler_fuel_flow) + 55338167.254907786846161 * log(Boiler_twall_1) - 29269094.807519607245922 * log(Boiler_twall_2) - 11767340.563981954008341 * log(Boiler_twall_3) - 13330382.699841693043709 * log(Boiler_twall_4)

**Comment by fsoepyan** [comment]
Answering Jeremy's (@ou3llnl) question:
- Yes, there is a recent correction in the OUU tab for the ordering of variables
- In the OUU tab, we used to have a problem where if we have variables x1, x2, ... x10, OUU would order these variables x1, x10, x2, ...
- But this problem has been resolved in the OUU tab

**Comment by ou3llnl** [comment]
@fsoepyan : Was this fix specific to OUU or would it also reflect in other parts of FOQUS?

**Comment by fsoepyan** [comment]
I think this fix is specific to OUU.

**Comment by ou3llnl** [comment]
@ngbrenda Since you wrote the alamo driver writer, we may need you to revisit it to make sure it reorders what comes out of alamo so it reflects the ordering in foqus
