### ISSUE TITLE
UQ PDF Selection Errors

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#225]
![distribution selection](https://user-images.githubusercontent.com/37089145/41368107-2c2bc004-6efe-11e8-8152-3bbd658ba620.PNG)
This error appears when Lognormal or Exponential PDFs are selected for a parameter distribution and the "Sampling Scheme" tab is then selected. The other PDFs don't show this error.

**Comment by CSRussell2319** [comment]
Probably tied to #226. I think this dialog should be updated to tell the user what they are doing wrong instead of displaying an exception.

**Comment by CSRussell2319** [comment]
Error fixed with help from @sotorrio1, but the dialog should still be updated so I'll keep this open.

**Comment by ksbeattie** [comment]
Closing this in deference to #232
