### ISSUE TITLE
FOQUS: Make error messages easier for user to understand

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#232]
In the long run, we would like to make most, if not all, the error messages generated by FOQUS easier for the user to understand.

**Comment by ksbeattie** [comment]
@CSRussell2319  says this is related to #225 and #226.

**Comment by sotorrio1** [comment]
Issue #67 also related to this

**Comment by ngbrenda** [comment]
For psuade-supported features, @ou3llnl will update our error message to prompt advanced users to check the psuade.log.

**Comment by ksbeattie** [comment]
Closing this as it isn't very specific.  The errors when Aspen fails should be in the Turbine messages column.
