### ISSUE TITLE
Simulation Resource: get-simulation and get-simulation-list

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#242]
The current simulation resource on AWS is not working and returns a "null" object, think this was deployed using old code not in GIT.   Change to basic HTTP authorization, and add the GET methods.
```
/simulation
/simulation/{GUID}
```

**Comment by boverhof** [comment]
/simulation is implemented:
`foqus_working_dir % curl -k --user $USERTOK https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/simulation/
[{"Name":"OUU","Application":"foqus","StagedInputs":[]},{"Name":"SimpleFlow","Application":"foqus","StagedInputs":[]},{"Name":"zzfoqus_BFB","Application":"foqus","StagedInputs":[]}]`

**Comment by ksbeattie** [comment]
@boverhof does this mean this issue is fixed?

**Comment by ksbeattie** [comment]
@boverhof will take another look at this.

**Comment by boverhof** [comment]
Currently getting unauthorized for GET on the \simulation\{resource}
```
% curl -k --user $USERTOK https://407osudx4l.execute-api.us-east-1.amazonaws.com/dev/simulation/zzfoqus_BFB
{"message":"Unauthorized"}
```

**Comment by ksbeattie** [comment]
@boverhof says this is partially done and can be closed.
