### ISSUE TITLE
FOQUS: Add icon that user can double-click to open FOQUS

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#244]
Currently, to open FOQUS, we need to type commands in the Anaconda prompt.

It would be great if during the installation process, a desktop icon can be created that allows the user to open FOQUS by double-clicking the icon.

**Comment by fsoepyan** [comment]
- I added a video in the CCSI2 Team YouTube page on how to open FOQUS.
- At least for me, opening FOQUS is simple enough.
- Do you still think this enhancement is necessary?
- If not, can we close this issue? (I'm moving this issue to "High" priority in the project board.)

**Comment by anujad95** [comment]
@fsoepyan i agree with you and this enhancement is not necessary for the time being
