### ISSUE TITLE
mock up of GUI for creating the input file for SDOE python code 

### ISSUE THREAD

**Issue by candcook** [CCSI-Toolset/FOQUS#246]
Mock up of GUI (with required inputs and structure) has been created. This will be sent to Brenda (end of week) for her team to start planning connection to FOQUS.

**Comment by ngbrenda** [comment]
The mock-up is a set of slides showing the control flow of @candcook and @atowfiq's SDOE scripts. We will incorporate into the FOQUS SDOE tab in due time.
