### ISSUE TITLE
UQ: The "Run Status" bar says there are errors even when the simulation is successful

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#249]
- I went to the UQ tab
- I generated the sample points
- I clicked "Launch"
- The green "Run Status" cell says that there are errors, even when the run is successful
- For example, I have 10 sample points, and only 2 sample points have errors, but the "Run Status" cell says there are 10 errors

**Comment by sotorrio1** [comment]
@fsoepyan what session are you loading? I'm following same steps with the Rosenbrock_no_vectors session file and I don't run into any issues...

**Comment by fsoepyan** [comment]
- I used UQ for an Aspen Plus simulation uploaded to Turbine
- The "Run Status" bar says there is only 1 error
- But the "graph.error" column shows that there is more than 1 error:

<img width="960" alt="uq_08_03_2018" src="https://user-images.githubusercontent.com/30811140/43660950-785d7046-972e-11e8-9c61-56eb7552f96f.png">

**Comment by ou3llnl** [comment]
Need either one of you to review #252 to see if it fixes this.

**Comment by sotorrio1** [comment]
I still don't get that error...

**Comment by fsoepyan** [comment]
Pull request #252 fixes this issue, and therefore, I will close this issue.
