### ISSUE TITLE
Surrogates: there is an issue with the "select all variables" button

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#25]
From JIRA:
- Reporter: Miguel Zamarripa (@MAZamarripa)
- Assignee: John Eslick (@eslickj)
- Original title: In surrogates module, ALAMO surrogate modeling tool there is an issue with the "select all variables" button
- Created: 23/Sep/16 6:29 AM
- Updated: 23/Sep/16 6:29 AM

Description:

the "select all variables" button must select all the variables and not the "status" and "graph.error".
Another option is to remove the status and graph.error from the list of possible output variables to generate surrogate models.

**Comment by ksbeattie** [comment]
@eslickj needs to look into this again if it is still an issue or not.

**Comment by ksbeattie** [comment]
@MAZamarripa, is this still happening?  Could you try to reproduce?

**Comment by MAZamarripa** [comment]
The button is working.
