### ISSUE TITLE
Pandas Versions

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#250]
There is a range of Pandas version, where if the version is too old or too new, FOQUS will not be able to work properly.

We should fix it for the newest version of Pandas.

**Comment by ksbeattie** [comment]
@fsoepyan says that pandas 2.3 is too new.

**Comment by ksbeattie** [comment]
@CSRussell2319 will look into which specific versions of pandas and matplotlib (see #227) we should use and make a pitch to the team for using those.

**Comment by CSRussell2319** [comment]
@fsoepyan please try pandas 0.21 and report back.

**Comment by fsoepyan** [comment]
- Pull request #256 has been accepted.
- This takes care of the issue, so I will close this issue.
