### ISSUE TITLE
UQ: Samples in UQ do not show up in Flowsheet and Surrogates tables

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#251]
- In the UQ tab, I would "Launch" the samples to obtain the values of the output variables for the sample points
- After FOQUS finishes this task, the values of the sample points do not appear in the Flowsheet table and the Surrogates table

**Comment by eslickj** [comment]
I did a quick test of this and it works for me.  I fixed the pandas issue, but unless the sample didn't appear after saving and reloading, I don't think this is related to issue #250.

@fsoepyan can you provide steps to reproduce this?

**Comment by fsoepyan** [comment]
- This issue is taken care of with pull request #256.
- I will close this issue.
