### ISSUE TITLE
Flowsheet: Some error message can be ignored and FOQUS will still run successfully

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#253]
- In the Flowsheet, I have multiple nodes connected with edges
- One of the nodes (Node A) is for an Excel file
- Node A is connected to Node B (also for an Excel file) with an edge
- All the inputs of Node A are specified in SimSinter
- But all of the outputs of Node A are calculated in FOQUS using the Python code
- The outputs of Node A = the inputs of Node B
- When I update the SimSinter file for Node A, I would delete the old file from Turbine, and re-upload the new file into Turbine
- When I select Node A, I would get this error message:

<img width="422" alt="error_08_07_2018" src="https://user-images.githubusercontent.com/30811140/43791902-18070efe-9a45-11e8-81f8-a33439c21ae1.png">

- But despite that, I can still run the simulation

**Comment by eslickj** [comment]
@fsoepyan, can you see if this is still an issue?  If not lets close it.  If it is still a problem I'll look into it more.

**Comment by ksbeattie** [comment]
@fsoepyan says he has not been able to reproduce this.
