### ISSUE TITLE
RuntimeError: No input in sd dict

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#254]
The FOQUS UI throws a runtime error when gathering the results of a session/job run.  Apparently the "input" field is missing and may be because the Turbine Web API is not returning it as expected or the GRAPH clone is not copying it...

`
Traceback (most recent call last):
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/main/mainWindow.py", line 1274, in checkSim
    self.stopSim()
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/gui/main/mainWindow.py", line 1336, in stopSim
    self.dat.flowsheet.loadValues(self.singleRun.res[0])
  File "/Users/boverhof/Documents/workspace.ccsi2/foqus-boverhof/foqus_lib/framework/graph/graph.py", line 335, in loadValues
    raise RuntimeError, 'No input in sd dict: %s' %str(sd)

RuntimeError: No input in sd dict: {u'graph': {u'error': 0}, 'session': 'd2430472-8405-4c3c-9352-b760e25ca5f4', 'Id': u'fdbca3c3-4620-4e53-a7c8-501f21e8fe74', 'resub': 0, u'BFB': {u'removalCO2': 0.8999964373466817, u'removalCO2_slack': 0, u'SHX.SteamFR': 37683.43278161038, u'slugam_slack': 0, u'GHXfg.HXIn.F': 135788.8395015208, u'slugrb_slack': 0, u'Cost_op_fixed': 54526718.57072218, u'BFBRGN.GasIn.F': 1357.0814214980398, u'Cost_ads': 34830765.96283022, u'Cost_steam_power': 179203.44430650023, u'SHX.RichIn.T': 83.99312572585319, u'SHX.CWFR': 26890.328479471482, u'slugab_slack': 0, u'Cost_op_cooling_water': 12577963.846287617, u'Cost_toc_sorb': 83874472.31479213, u'Cost_rgn': 16321781.413333291, u'status': 0, u'SHX.RichOut.T': 170, u'slugrt_slack': 0, u'Cost_toc': 2111440309.1504824, u'F_solids': 12681737.021801885, u'Cost_shx': 39020395.75661277, u'Cost_coe_obj': 138.85964658190665, u'Cost_aux_power': 23378.969592384507, u'Cost_op_var': 172437413.51951027, u'Cost_op_cooling_water_flow': 2927442.0442882474, u'SHX.LeanIn.T': 146.3820219819483, u'SHX.LeanOut.T': 70.57864346590641, u'Cost_steam_tot': 696035.1169336186, u'slugat_slack': 0, u'Cost_coe': 138.85964658190665}}

2018-08-07 12:51:59,464 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - Stopped all running consumers
`

**Comment by boverhof** [comment]
I hacked “graph.py” until I could get the simulation to run to completion.  I had to add a bunch of stuff to “self.res” and I’m wondering if something essential is missing in the “copyNode” or "copyGraph" function...

`
foqus-boverhof % git diff foqus_lib/framework/graph/graph.py
diff --git a/foqus_lib/framework/graph/graph.py b/foqus_lib/framework/graph/graph.py
index 53c0158..7de87b3 100644
--- a/foqus_lib/framework/graph/graph.py
+++ b/foqus_lib/framework/graph/graph.py
@@ -197,6 +197,8 @@ class Graph(threading.Thread):
             it could also be used to make a copy of the graph.
             The information can be loaded back in with loadDict()
         '''
+        logging.getLogger("foqus." + __name__).debug(
+                            "SD input: " + str(self.input))
         sd = {
             'errorStat': self.errorStat,
             'includeStatusOutput':self.includeStatusOutput,
@@ -328,16 +330,21 @@ class Graph(threading.Thread):
             to -1 (meaning not run yet).
         '''
         self.solTime = sd.get('solTime', 0)
-        self.input.loadValues(sd['input'])
+        input = sd.get('input') or sd.get('Input') # JRB: SLOP..
+        if input is None:
+            raise RuntimeError, 'No input in sd dict: %s' %str(sd)
+        self.input.loadValues(input)
         o = sd.get('output', None)
         if o:
             self.output.loadValues(sd['output'])
         self.setErrorCode(sd.get('graphError', -1))
         ne = sd.get('nodeError', {})
         tm = sd.get('turbineMessages', {})
-        for nkey in self.nodes:
-            self.nodes[nkey].calcError = ne.get(nkey, -1)
-            self.nodes[nkey].turbineMessages = tm.get(nkey, "")
+        logging.getLogger("foqus." + __name__ + ".loadValues").debug(
+            "NODES: " + str(self.nodes))
+        #for nkey in self.nodes:
+        #    self.nodes[nkey].calcError = ne.get(nkey, -1)
+        #    self.nodes[nkey].turbineMessages = tm.get(nkey, "")
         return sd
 
     def getCenter(self):
@@ -690,6 +697,7 @@ class Graph(threading.Thread):
                         # resubmitted
                         continue
                     jobRes = job.get('Output', None)
+                    logging.getLogger("foqus." + __name__ + '.solveListValTurbine').debug("JOB: " + str(job))
                     if jobRes is None:
                         jobErr = -3
                     else:
@@ -720,6 +728,20 @@ class Graph(threading.Thread):
                                 self.res_fin[i] = jobErr
                             # Add information to see if was resubmitted
                             self.res[i]['resub'] = self.res_re[i]
+                            # HACK: JRB
+                            self.res[i]['input'] = NodeVarList()
+                            self.res[i]['input'].addNode('BFB')
+                            self.res[i]['solTime'] = 100
+                            self.res[i]['graphError'] = 0
+                            self.res[i]['output'] = NodeVarList()
+                            self.res[i]['nodeSettings'] = NodeVarList()
+                            self.res[i]['nodeSettings'].addNode('setting')
+                            self.res[i]['nodeError'] = NodeVarList()
+                            self.res[i]['nodeError'].addNode('nodeError')
+                            #self.res[i]['nodeError'].addNode('BFB')
+                            self.res[i]['nodeError'].addVariable('nodeError', 'BFB')
+                            self.res[i]['turbineMessages'] = NodeVarList()
+                            #self.res[i]['turbineMessages'].addNode('turb')
                         with self.statLock:
                             self.status["finished"] += 1
                             self.status['unfinished'] -= 1
@@ -826,6 +848,8 @@ class Graph(threading.Thread):
                 # need to make a runList for single run
                 sd = self.saveValues()
                 self.runList = [sd['input']]
+                logging.getLogger("foqus." + __name__).debug(
+                    "runList=  " + str(self.runList))
             #make sure there are no numpy arrays in runList
             for job in self.runList:
                 for nkey in job:
`

**Comment by boverhof** [comment]
The problem boils down to the "foqus_worker.py" or "foqus_service.py" not filling out the "Output" object in the result response.  Some field names are incorrect or missing.  To fix the error above need to add "Output.input" dict.  Add an ASSERT in the code to make it clear this is an expected field rather than bombing way deep in the foqus code.
 


## Bad JSON ( foqus_service.py )
```
[ {
    "Id": "fdaf89da-6b94-4767-9b14-ae40a1d2174b",
    "Application": "foqus",
    "SessionId": "6a10efe8-c024-4ee4-8b91-fb8cb316ca43",
    "Input": {
      "test": {
        "x1": 1,
        "x2": 2
      },
      "graph": {}
    },
    "Reset": false,
    "Simulation": "zzfoqus_test_session",
    "Create": "2018-08-15T20:18:11.813Z",
    "setup": "2018-08-15T20:18:23.090Z",
    "Running": "2018-08-15T20:18:23.193Z",
    "success": "2018-08-15T20:18:23.263Z",
    "Output": {
      "test": {
        "y": 3
      },
      "graph": {
        "error": 0
      }
    }
  }]
```


## GOOD JSON (TurbineLite)

```
[{
    "Id": 2,
    "Guid": "f714da09-b763-4d52-962e-883b6014da7e",
    "Simulation": "zzfoqus_test_session",
    "State": "success",
    "Messages": null,
    "Input": {
      "test": {
        "x1": 1,
        "x2": 2
      },
      "graph": {}
    },
    "Output": {
      "nodeError": {
        "test": 0
      },
      "output": {
        "test": {
          "y": 3
        },
        "graph": {
          "error": 0
        }
      },
      "nodeSettings": {
        "test": {}
      },
      "input": {
        "test": {
          "x1": 1,
          "x2": 2
        },
        "graph": {}
      },
      "turbineMessages": {
        "test": ""
      },
      "graphError": 0,
      "solTime": 0
    },
    "Errors": [],
    "Status": 0,
    "Session": "45afa984-ad92-4140-95ea-0e3447e6a881",
    "Initialize": false,
    "Reset": false,
    "Visible": false,
    "Consumer": "4a233297-b17c-48bd-ba4a-d621f16f71f3",
    "Create": "2018-08-15T19:11:39.2130000",
    "Submit": "2018-08-15T19:11:39.5100000",
    "Setup": "2018-08-15T19:11:00.0000000",
    "Running": "2018-08-15T19:11:00.0000000",
    "Finished": "2018-08-15T19:11:00.0000000"
  }]

```

**Comment by ksbeattie** [comment]
@boverhof was there a commit or PR that fixed this issue?
