### ISSUE TITLE
Create a "how to install" video

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#259]
And feature that link (presumably on YouTube) in the release notes.

**Comment by fsoepyan** [comment]
- My plan is to get this done for the September release, which I assume will take place at the end of September.
- Does anyone have any suggestion for a software I can use to make the video?

**Comment by fsoepyan** [comment]
- I have recorded the FOQUS installation guide video, but the video is about 1 hour long
- My next step is to edit the video, so that instead of having 1 long video, we have a group of short videos for each section of the FOQUS installation
- Does anyone have any recommendations regarding a software I can use to edit videos?

**Comment by fsoepyan** [comment]
- I looked at the following website that @ngbrenda suggests for video editing software: https://www.techradar.com/news/best-video-editing-software-paid-and-free
- Is Lightworks (a free software that the website recommends) a good video editing software?

**Comment by fsoepyan** [comment]
- I am in the process of converting the 1-hour long video into shorter videos
- So far, we have 3 videos: Anaconda installation, Git Client installation, and FOQUS installation
- I used Lightworks as the video editing software
- For the first 2 videos, the Lightworks worked fine
- When I worked on the 3rd video, Lightworks was working slowly towards the end of my editing
- When I tried working on the 4th video, Lightworks was working very slowly
- Does anyone have any suggestion regarding other video editing softwares I can use in Windows?

**Comment by fsoepyan** [comment]
- I am currently using VSDC Free Video Editor as the video editing software
- So far, it proves to be a decent video editing software
- We now have 3 more videos: SimSinter and TurbineLite installation, PSUADE installation, and ALAMO installation

**Comment by fsoepyan** [comment]
We now have 2 more videos: NLopt installation, and R installation

**Comment by fsoepyan** [comment]
We now have 2 more videos: downloading the user's manual, and FOQUS settings

**Comment by fsoepyan** [comment]
- We have 10 videos so far
- I'm currently working on the 11th (and last) video, which shows a FOQUS example, and how to troubleshoot the problem with "no module named apibase"

**Comment by fsoepyan** [comment]
- We now have all 11 videos ready to go
- We have reduced the total time from 1 hour to 35 minutes
- Who will create a CCSI Google/YouTube account so that we can upload these videos?

**Comment by ksbeattie** [comment]
@fsoepyan will create a youtube account for this & share it with us.

**Comment by fsoepyan** [comment]
- The videos have been uploaded to YouTube
- The YouTube channel is: CCSI2 Team
- The videos can be accessed from this website/playlist: https://www.youtube.com/playlist?list=PLmBxveOxgaXkyrQP9CAgUu_ZPYsS4qCvd
- If the videos are acceptable, we can close this issue
