### ISSUE TITLE
Flowsheet/Optimization: import data issue

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#26]
From JIRA:
- Reporter: Miguel Zamarripa (@MAZamarripa)
- Assignee: John Eslick (@eslickj)
- Original title: import data issue
- Created: 23/Sep/16 6:25 AM
- Updated: 23/Sep/16 6:25 AM

Description:

Exporting data to clipboard and to cvs files is easy, but when you try to return this data the columns dont match. Some columns make the mismatch error, some of the columns are: Tags, initial, maximum time, settings, homotopy, etc.

**Comment by ngbrenda** [comment]
Since this is a flowsheet data issue, @eslickj is more suited to looking at this issue.

**Comment by ksbeattie** [comment]
@MAZamarripa could you try this again?  @eslickj says that this code has been re-written so this issue likely no longer exists.

**Comment by MAZamarripa** [comment]
@eslickj Yes this issue no longer exists.
