### ISSUE TITLE
UQ: Problem with loading samples in UQ model from CSV file

### ISSUE THREAD

**Issue by puttak** [CCSI-Toolset/FOQUS#263]
Hi,
I am getting error when i am trying load a csv file format data samples in UQ mode.

**Comment by fsoepyan** [comment]
Putta (@puttak), can you please provide a screenshot of your error, and a few short bullet points on how to reproduce the error?

**Comment by puttak** [comment]
![csv issue](https://user-images.githubusercontent.com/30050105/44367151-f6f67300-a49c-11e8-871b-02ac579500a5.jpg)

**Comment by sotorrio1** [comment]
@puttak Please test now and let me know if it is fixed so we can close the issue. Thanks!

**Comment by ksbeattie** [comment]
@fsoepyan will contact @puttak to see if he's still working on the project a/o can help confirm this.

**Comment by ksbeattie** [comment]
@puttak will confirm this

**Comment by ksbeattie** [comment]
@fsoepyan has reached out to him, @puttak is in Norway and said he could look at it.  @fsoepyan will try testing it himself to save time.

**Comment by fsoepyan** [comment]
- I opened the "Rosenbrock_no_vectors" example from under the "examples/UQ" folder
- I went to the UQ tab
- I created a CSV file, saved it, and selected "CSV (MS-DOS)" for the file type (following the suggestion of @CSRussell2319)
- I managed to upload the CSV file successfully (Thank you!)
- I will close this issue
