### ISSUE TITLE
UQ: Bayesian inference: inputting the mean and standard deviation

### ISSUE THREAD

**Issue by puttak** [CCSI-Toolset/FOQUS#264]
It asks the user to manual enter the mean and standard deviation for all the variables.
The user needs to copy paste one value at a time. 

When we are dealing with many variables and also say design of experiments it becomes really difficult to copy each single value manually.

It will really help the user if he can just copy and paste all the values in one instance.

**Comment by ou3llnl** [comment]
Will require a bit more research on how to access the clipboard in order to paste the values in.
