### ISSUE TITLE
UQ: We would like to be able to save input to Bayesian inference tab, so that it can be reused later

### ISSUE THREAD

**Issue by puttak** [CCSI-Toolset/FOQUS#265]
When we close the Bayesian inference tab all the information entered is lost. This tab has lot manual inputs to be given. 
So it will be easy for the user to use it if we can save the file same as foqus file to continue working afterwards.

**Comment by ou3llnl** [comment]
We have an idea how this could possibly be implemented. We currently keep a history of all analyses performed on each ensemble within UQ. We would implement a pull-down in the inference dialog that would have a list of all previous inference analyses run on the ensemble. When you select one, then the settings are populated from that analysis.

Would this work?
