### ISSUE TITLE
Automated Tests Close Too Early

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#271]
Some of the automated tests trigger Foqus to close before the Psuade code has finished running. The premature closing is implemented by design to make sure Foqus closes even if it hits a dialog box that would normally stop the program from progressing any further. In this instance Foqus is just waiting for Psuade to finish running and Foqus closes while Psuade continues to run in the background which prevents the next test from starting.

**Comment by ksbeattie** [comment]
Closed with PR #272
