### ISSUE TITLE
OUU Sample Problems Take a Long Time to Run

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#284]
I have three OUU tests (ouu_smoke_test_ex_3.py, ouu_smoke_test_ex_5.py, and ouu_smoke_test_ex_7.py) that each can take 20 min to run. These tests are based on three of the OUU example problems with matching numbers. Since the problems finish running without an issue I'm going to label this as an enhancement. The goal of this issue is to determine if these run times are too long and if so what can be done to optimize the OUU.

**Comment by sotorrio1** [comment]
These three problems take longer than the others because they use response surface (RS). I can talk to Charles about it, but this has being the case for any problem with RS.

**Comment by sotorrio1** [comment]
We will check with Charles Tong if there are OUU examples using response surface that take less time to run

**Comment by boverhof** [comment]
no progress, outdated
