### ISSUE TITLE
JIRA Issue: Edge editor (auto button isnt working)

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#29]
From JIRA:
- Reporter: Miguel Zamarripa (@MAZamarripa)
- Assignee: John Eslick (@eslickj)
- Original title: Edge editor (auto button isnt working)
- Created: 12/Jul/16 12:12 PM
- Updated: 29/Jul/16 12:40 PM

Description:

The edge editor allows the user to automatically select the variable connections by clicking the "Auto" button. But right now there is no action after clicking this button. (we have two options: either remove it, or fix it). 

I would prefer if we can fix it (it could be very useful when several variables need to be connected).

Chat history:

John Eslick added a comment - 29/Jul/16 12:40 PM 

Auto works on variables of the same name, connecting outputs or input in the "from" node to inputs in the "to" node. Do the variables you are trying to connect have the same name? I did a simple test and it's working for me. Can you attach the FOQUS session?

**Comment by ksbeattie** [comment]
@MAZamarripa closing due to age, let us know if this is still an issue.

**Comment by anujad95** [comment]
The issue still persists. I tried tutorial "Creating a Flowsheet with Linked Simulations" from the documentation. In step 26, the auto button is not working as expected. @eslickj

**Comment by ksbeattie** [comment]
@eslickj will take a look at this.

**Comment by eslickj** [comment]
What exactly is the auto button doing?  I don't have Aspen installed so I can't go through the tutorial.  I tried it out on another flowsheet and it worked.

**Comment by anujad95** [comment]
In the tutorial "Creating a Flowsheet with Linked Simulations", step 26 mentions the following:
_"For convenience, all of the variables that should be connected from the ACM model to the Excel spreadsheet have been given the same names in their SimSinter configuration files. To connect the variables click Auto in the Edge Editor. Auto connects variables of the same name."_
The tutorial consists of BFB (ACM Simulation) and cost (Excel calculations) nodes that are connected through an edge. The input and output variables of BFB are supposed to be connected to the input variables of cost node, corresponding to the same name. After checking the node editors individually, the variables to be connected in both nodes seem to be fine, as they are named the same, and total 46. However, when the auto button is clicked, the following connections are displayed in the edge editor:
![image](https://user-images.githubusercontent.com/47067166/58333683-f1eb9900-7e0b-11e9-9b59-0d98814e1c5e.png)
Although the "From" column consists of all 46 variables to be connected, the "To" column is populated by only one variable.

**Comment by fsoepyan** [comment]
Resolved with PR #510.
