### ISSUE TITLE
Missing fields in results from AWS.

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#295]
Occasionally results from AWS are missing information that FOQUS expects resulting in unhandled exceptions that can stop optimization or UQ runs.  At this point it is not clear under what circumstances this happens but there are several possibilities.

What should happen is that the FOQUS consumer should save the results of a run as json, regardless of whether the simulation failed and return it as the result.  This should have all the information FOQUS expects.

Here are some possible causes of this problem:

1) A bug in the FOQUS consumer causes the results to not be saved properly on some error conditions.
2) The FOQUS consumer could crash somehow and produce no results
3) Turbine may somehow loose contact with the consumer and assume there was an error
4) Turbine could be taking the results from the consumer and doing something with them that causes them not to be returned on some error conditions.
5) Network issues causing Turbine to report an error with no results
6) probably a million other things...

There are probably two things to do here:
1) Fix FOQUS so it doesn't fail catastrophically if it doesn't get what it expects
2) Look into the cases where results don't come back properly and see what can be done.  There are probably at least a few cases where things can fail in a way that you just can get the results in the expected format, and that's fine.

**Comment by ksbeattie** [comment]
Closing this as a dup of #297
