### ISSUE TITLE
Surrogates: add calculated columns

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#30]
From JIRA:
- Reporter: Miguel Zamarripa (@MAZamarripa)
- Assignee: John Eslick (@eslickj)
- Original title: add new setting (Transforms).
- Created: 27/Jun/16 1:23 PM
- Updated: 07/Jul/16 12:55 PM

Description:

This new setting helps to improve the quality of the models. It works to scale the output variables, transform data to find better fitting (exp and log). 

- Include a new column for each output variable adding the option to transform the data (zscale, exp, log).
- Changes: Each new transformation is added to the output variables information: 
noutputs (outputs + #transfunctions)
maxterms (add a column for each transfunction)
Ignore (add a column for each transfunction)
tolrelmetric (add a column for each transfunction)
tolmeanerror (add a column for each transfunction)
zlabels (add a name for each transfunction "not the same output")

- Include in the alamo input file ("before BEGIN_DATA"): 
- Example for 4 transformations:
Ntrans 4

BEGIN_TRANSFORMS
GasOutput*1000
log(GasOutput)
exp(GasOutput)
GasConcentration*1000
END_TRANSFORMS

- The output models and statistics are listed as output variables in the listing file (ALAMO.lst).

**Comment by ngbrenda** [comment]
I believe "calculated columns" are implemented under @eslickj's filtering feature. Please work with @eslickj to resolve.

**Comment by fsoepyan** [comment]
- For the "Surrogates", if you go to the "Data" tab, and click "Add/Edit Filters", a message box will appear.
- In the upper-right corner, there is a button for "New Calculated Column".
- With this new feature, I believe we can close this issue.
- Would anyone object to that?

**Comment by anujad95** [comment]
Has this new feature been tested?

**Comment by ksbeattie** [comment]
These columns do not yet exist, but @anujad95 will look into adding them.

**Comment by ksbeattie** [comment]
@anujad95 is working on this.
