### ISSUE TITLE
Flowsheet: include a color indicator for the node its being simulated

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#31]
From JIRA:
- Reporter: Miguel Zamarripa (@MAZamarripa)
- Assignee: John Eslick (@eslickj)
- Original title: include a color indicator for the node its being simulated
- Created: 10/May/16 2:23 PM
- Updated: 08/Jun/16 8:42 AM

Description:

When solving multiple node simulations, it could be useful to highlight which node its being simulated at the time.

**Comment by eslickj** [comment]
This would be cool but, for reasons, it's too difficult to implement.
