### ISSUE TITLE
Sorting Fails with an Operation

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#312]
If I attempt to sort flowsheet results with two conditions it will fail with an error for every operation except "NOT". I have tested the rules individually and they run without error. Below is the picture of the error. I have included screenshots of the error and a report of the output from my test.

![sort_error_1](https://user-images.githubusercontent.com/37089145/47174703-933acb80-d2ce-11e8-8b4c-a65b37b592b9.PNG)
![sort_error_2](https://user-images.githubusercontent.com/37089145/47174704-93d36200-d2ce-11e8-9ee8-d92dafe05fc4.PNG)
[AutoErrLog_fs.txt](https://github.com/CCSI-Toolset/FOQUS/files/2493089/AutoErrLog_fs.txt)

**Comment by eslickj** [comment]
This one is user error.  It's partly my fault though for writing this thing using reverse Polish notation.  The and pops two things off the stack and put one back on.  In the example screen shot, and is in the middle.  There is only one thing to on the stack at that point. 

One thing we could do to get around this is finish removing this filter system and use calculated columns to do it instead.  You could pick a calculated column that evaluates to True or False.  True is in False is out.  The syntax for calculated columns is just regular Python so it would be even more flexible and easier to understand.

**Comment by eslickj** [comment]
Change the way this works with PR #353.  That may get refined a bit, but I don't think we'll go back to this way of filtering.
