### ISSUE TITLE
MARS Throws Error with Inference smoke test

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#313]
The uq_inference smoke test throws an error when performing Bayesian inference with MARS or MARS with Bagging. It seems to continue running after the error is ignored though.

[AutoErrLog_uq_inference.txt](https://github.com/CCSI-Toolset/FOQUS/files/2493258/AutoErrLog_uq_inference.txt)
![uq_inference_mars_failure](https://user-images.githubusercontent.com/37089145/47177833-c719ef00-d2d6-11e8-9e4f-9c48b9617c81.PNG)

**Comment by sotorrio1** [comment]
@CSRussell2319 : 'marsInteractions' should be >2 and <numInputs. This error message happens when the interactions are less than 2 or greater than the number of input variables.

**Comment by CSRussell2319** [comment]
@sotorrio1: Does this mean that this is a user error and I need to adjust my inputs? If so I think this error message should be updated (#232).

**Comment by sotorrio1** [comment]
@CSRussell2319 : I don't know what inputs you're using but it looks like it. I'll try to update the error message

**Comment by CSRussell2319** [comment]
@sotorrio1: I'm using the rosenbrock_no_vectors example from the UQ examples in the smoke test. When I try to do it manually it seems to only produce that error some of the time and only seems to do it in expert mode. Since I don't see anything that would allow me to edit the number of 'marsinteractions' could you help me understand which variables need to change?

**Comment by sotorrio1** [comment]
@CSRussell2319: In the "Wizard" mode, the user chooses two possible options for MARS. 
- MARS --> MARS
- MARS --> MARS with Bagging

In the "Expert" mode is when the user can specify also the number of basis functions and the degree of interaction. In the "Wizard" mode those spin boxes are disabled.

**Comment by sotorrio1** [comment]
@CSRussell2319: If you go to foqus_lib.uq.gui.RSCombos.py, Lines 280-296 you can see the classes "MarsBasisSpinBox" and "MarsDegreeSpinBox" and what are the range values and the default values. It could be that your issue is related to using the default values when you only have 6 input variables.

**Comment by CSRussell2319** [comment]
@sotorrio1 Yeah, I'm not seeing a spin box in either. Would the defaults be different for wizard mode vs expert mode?

**Comment by sotorrio1** [comment]
@CSRussell2319 can you see the spin boxes while on Expert mode? I'm not sure about the defaults for wizard mode because that might be embedded in psuade.

**Comment by CSRussell2319** [comment]
@sotorrio1 I'm not sure which spin boxes you're referring to. I've attached an image of what I'm seeing in the inference window. There are very few options that I can change.

![mars error](https://user-images.githubusercontent.com/37089145/50162140-ce3f8800-029a-11e9-8c27-36fc0369d51b.PNG)

**Comment by sotorrio1** [comment]
If you scroll to the right in the "Output Settings" table, you should see two spin boxes right after the "Legendre Order" spin box.

**Comment by CSRussell2319** [comment]
@sotorrio1: Thanks, I didn't notice those before. It looks like the issue is that the spin box populates with the total number of inputs instead of the total number of _variable_ inputs, which means it throws an error when one is specified as fixed. I think several things should happen:
* Update the spinbox code to look at the total number of variable inputs
* Update the error box to tell the user why it's broken and what to do to fix it (where the option is) [#232]
* Hide boxes that aren't being used
* If there's an error with Mars interactions then it shouldn't run
  * Currently the inference will still run after the error

**Comment by sotorrio1** [comment]
@CSRussell2319 : Good catch with the total number of inputs vs the number of variable inputs. I will take a look at that and the rest of the stuff.

**Comment by ksbeattie** [comment]
@sotorrio1 needs to clone himself to be able to work on it.

**Comment by sotorrio1** [comment]
- PR #340 should take care of the spin box looking at the number of variable inputs. 
- boxes that aren't being used are already disabled. Depending on the combobox they become enable or not.

**Comment by ksbeattie** [comment]
Fixed with PR #340
