### ISSUE TITLE
Error with installing adobapi to run foqus simualtions

### ISSUE THREAD

**Issue by puttak** [CCSI-Toolset/FOQUS#315]
Hi, 
I have installed new version of foqus in windows 10 PC as per instructions and video made by Byron. When you want to run foqus, it says some error and Byron in the video showed to updated the adobapi. When i tried the same, it's not getting updated and i have following error message.

![adobapi error](https://user-images.githubusercontent.com/30050105/47650927-09b6b380-db82-11e8-9608-7e42c138b8a7.jpeg)

Regards,
Putta

**Comment by ksbeattie** [comment]
This looks like it might be a typo.  It's "adodbapi" not "adobapi".
