### ISSUE TITLE
SDoE: GUI design

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#316]
We are working on the GUI design for the SDoE module. Once the design matches LANL desired capabilities, we'll proceed to hook up the back-end functionalities.

**Comment by ksbeattie** [comment]
@sotorrio1, I'm adding this back to the In Progress column of the 2018 Nov release board just so we can keep it top of mind.  If it isn't completed with that release, that's fine, I just don't want to make sure we address any roadblocks, etc.

**Comment by sotorrio1** [comment]
@ksbeattie, that's fine 👍

**Comment by ksbeattie** [comment]
@sotorrio1 has a demo ready, still in progress...

**Comment by sotorrio1** [comment]
Just committed all my changes in PR #338. I'll close this issue since SDOE phase 1 is ready
