### ISSUE TITLE
Issues reshaping matrix in UQ (Python 3.x)

### ISSUE THREAD

**Issue by CSRussell2319** [CCSI-Toolset/FOQUS#325]
I have attached the error log files associated with this error. From my understanding there's a regex split function that is returning values such that there are an odd number of elements. This leads to a float instead of an int and the matrix can't be resized. This error is persistent throughout different UQ functions.

[AutoErrLog_uq_response_surface_validation.txt](https://github.com/CCSI-Toolset/FOQUS/files/2600984/AutoErrLog_uq_response_surface_validation.txt)
[AutoErrLog_uq_response_surface_visualization.txt](https://github.com/CCSI-Toolset/FOQUS/files/2600985/AutoErrLog_uq_response_surface_visualization.txt)
[AutoErrLog_uq_data_visualization.txt](https://github.com/CCSI-Toolset/FOQUS/files/2600987/AutoErrLog_uq_data_visualization.txt)
[AutoErrLog_uq_inference.txt](https://github.com/CCSI-Toolset/FOQUS/files/2600988/AutoErrLog_uq_inference.txt)

**Comment by sotorrio1** [comment]
@CSRussell2319 and @eslickj I'm not very familiar with Python 3 but I was wondering if you guys know if there has been any changes on the way the handle regex? Looking at the code it seems that the issue might be in foqus_lib.framework.uq.Plotter.py. I'll keep digging.

**Comment by sotorrio1** [comment]
@CSRussell2319 just committed a small change to the code in the py3 branch. Could you please re-test as soon as you can so I know if there are any errors left? Thanks!

**Comment by CSRussell2319** [comment]
@sotorrio1 yes, this fixes my issue

**Comment by sotorrio1** [comment]
Great, thanks!
