### ISSUE TITLE
Handling Turbine Job Status Error

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#333]
# Description
There are many possible error scenarios when jobs are submitted to Turbine for processing.  Some of these are correct ( failure to converge ), some the result of FOQUS killing a job, and some are bugs.  I'd like to maintain a list of errors and failures and decide on how to make the infrastructure handle them correctly.

## COM Failure
If FOQUS kills a job will be moved to "error".  Jobs hang for a variety of reasons.
### job output
``
{  "graphError" : { "N" : "1" },  "input" : { "M" : {      "BFB" : { "M" : {          "BFBadsB.Cr" : { "N" : "1" },          "BFBadsB.Dt" : { "N" : "11.897" },          "BFBadsB.dx" : { "N" : "0.0127" },          "BFBadsB.Lb" : { "N" : "2.085" },          "BFBadsM.Cr" : { "N" : "1" },          "BFBadsM.Dt" : { "N" : "15" },          "BFBadsM.dx" : { "N" : "0.06695" },          "BFBadsM.Lb" : { "N" : "1.972" },          "BFBadsT.Cr" : { "N" : "1" },          "BFBadsT.Dt" : { "N" : "15" },          "BFBadsT.dx" : { "N" : "0.06239700000000001" },          "BFBadsT.Lb" : { "N" : "2.2029999999999994" },          "BFBRGN.Cr" : { "N" : "1" },          "BFBRGN.Dt" : { "N" : "9.041" },          "BFBRGN.Lb" : { "N" : "8.886" },          "BFBRGNTop.Cr" : { "N" : "1" },          "BFBRGNTop.Dt" : { "N" : "9.195" },          "BFBRGNTop.Lb" : { "N" : "7.1926" },          "dp" : { "N" : "0.0001125" },          "fg_flow" : { "N" : "70263.9" },          "GHXfg.A_exch" : { "N" : "16358" },          "GHXfg.GasIn.P" : { "N" : "1.01325" },          "GHXfg.GasIn.T" : { "N" : "54" },          "Kd" : { "N" : "100" }        }      },      "graph" : { "M" : {        }      }    }  },  "nodeError" : { "M" : {      "BFB" : { "N" : "21" }    }  },  "nodeSettings" : { "M" : {      "BFB" : { "M" : {          "Allow Simulation Warnings" : { "BOOL" : true },          "homotopy" : { "N" : "0" },          "Initialize Model" : { "BOOL" : false },          "Max consumer reuse" : { "N" : "90" },          "Max Status Check Interval" : { "N" : "5" },          "Maximum Run Time (s)" : { "N" : "840" },          "Maximum Wait Time (s)" : { "N" : "1440" },          "Min Status Check Interval" : { "N" : "4" },          "MinStepSize" : { "N" : "0.001" },          "Override Turbine Configuration" : { "S" : "NULL" },          "printlevel" : { "N" : "0" },          "Reset" : { "BOOL" : false },          "Reset on Fail" : { "BOOL" : true },          "Retry" : { "BOOL" : false },          "RunMode" : { "S" : "Steady State" },          "Script" : { "S" : "NULL" },          "Snapshot" : { "S" : "NULL" },          "TimeSeries" : { "L" : [              { "N" : "0" }            ]          },          "TimeUnits" : { "S" : "Hours" },          "Visible" : { "BOOL" : false }        }      }    }  },  "output" : { "M" : {      "BFB" : { "M" : {          "BFBRGN.GasIn.F" : { "N" : "1357.0814214980398" },          "Cost_ads" : { "N" : "34830765.96283022" },          "Cost_aux_power" : { "N" : "23378.969592384507" },          "Cost_coe" : { "N" : "138.85964658190665" },          "Cost_coe_obj" : { "N" : "138.85964658190665" },          "Cost_op_cooling_water" : { "N" : "12577963.846287617" },          "Cost_op_cooling_water_flow" : { "N" : "2927442.0442882474" },          "Cost_op_fixed" : { "N" : "54526718.57072218" },          "Cost_op_var" : { "N" : "172437413.51951027" },          "Cost_rgn" : { "N" : "16321781.413333291" },          "Cost_shx" : { "N" : "39020395.75661277" },          "Cost_steam_power" : { "N" : "179203.44430650023" },          "Cost_steam_tot" : { "N" : "696035.1169336186" },          "Cost_toc" : { "N" : "2111440309.1504824" },          "Cost_toc_sorb" : { "N" : "83874472.31479213" },          "F_solids" : { "N" : "12681737.021801885" },          "GHXfg.HXIn.F" : { "N" : "135788.8395015208" },          "removalCO2" : { "N" : "0.8999964373466817" },          "removalCO2_slack" : { "N" : "0" },          "SHX.CWFR" : { "N" : "26890.328479471482" },          "SHX.LeanIn.T" : { "N" : "146.3820219819483" },          "SHX.LeanOut.T" : { "N" : "70.57864346590641" },          "SHX.RichIn.T" : { "N" : "83.99312572585319" },          "SHX.RichOut.T" : { "N" : "170" },          "SHX.SteamFR" : { "N" : "37683.43278161038" },          "slugab_slack" : { "N" : "0" },          "slugam_slack" : { "N" : "0" },          "slugat_slack" : { "N" : "0" },          "slugrb_slack" : { "N" : "0" },          "slugrt_slack" : { "N" : "0" },          "status" : { "N" : "0" }        }      },      "graph" : { "M" : {          "error" : { "N" : "1" }        }      }    }  },  "solTime" : { "N" : "200.44900012016296" },  "turbineMessages" : { "M" : {      "BFB" : { "S" : "[\"event=setup,consumer=cac2d091-dd8e-475b-8cd1-3d4d9135c249\", \"working directory setup finished\", \"Failed to open Simulation (1: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0300-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).\", \"Failed to open Simulation (2: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0300-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).\", \"Failed to open Simulation (3: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0300-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).\", \"Failed to open Simulation (4: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0300-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).\", \"event=error,consumer=cac2d091-dd8e-475b-8cd1-3d4d9135c249,msg=\\\"Failed to open Simulation (5: Could not open ACM: Retrieving the COM class factory for component with CLSID {FDE14674-8E3D-0300-878A-2E97C127D967} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).\\\"\"]" }    }  }}
``

**Comment by ksbeattie** [comment]
Obsolete.
