### ISSUE TITLE
Python 3 Turbine Client

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#334]
We need a Python 3 compatible version of Turbine Client.  Now that we put a lot of work into moving FOQUS to Python 3 I guess its too late to go back.  I hacked up something here that is just good enough to make FOQUS work, but not really tested.  I don't know if it would help or just make things harder.  https://github.com/eslickj/turb_client/tree/py3

**Comment by ksbeattie** [comment]
See: https://github.com/CCSI-Toolset/turb_client/issues/5

**Comment by ksbeattie** [comment]
@eslickj: @boverhof is going to grab your "not a fork" fork of turb_client and "merge" it into the main turb_client master.  This will allow us to get a python 3 version of turb_client and then a python 3 version of FOQUS.

Once that is done, @eslickj and @CSRussell2319's "not a fork" forks should probably be removed to avoid further confusion.

**Comment by eslickj** [comment]
https://github.com/CCSI-Toolset/turb_client/issues/5.  Should close this too.
