### ISSUE TITLE
UQ: Cannot handle string type variables

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#336]
- I tried running UQ for a Flowsheet involving multiple nodes
- After generating the samples, I clicked "Launch"
- I get these error message:

<img width="800" alt="dpe_uq_error_01_04_2019" src="https://user-images.githubusercontent.com/30811140/50844003-d8075900-1337-11e9-8498-fc29546a11a2.png">

<img width="800" alt="dpe_uq_error2_01_04_2019" src="https://user-images.githubusercontent.com/30811140/50844008-dd64a380-1337-11e9-9f3b-0ad36242c4cf.png">

- Then, FOQUS closes
- The one variable that I specify as "Variable" is not a string, and the rest of the variables are "Fixed"
- Is there something I can do so that the UQ tab can handle having a string type variable that is fixed?

**Comment by fsoepyan** [comment]
Before I clicked "Launch":
- I went to "Preview Samples"
- When I tried to get the "1-D Scatter" and "Distribution" graphs, I get an error message:

<img width="378" alt="uq_01_08_2019" src="https://user-images.githubusercontent.com/30811140/50845551-1ce0bf00-133b-11e9-8f2c-2721f09ca7ff.png">

- Below is the PSUADE message:

**********************************************************************
* Welcome to PSUADE (version 1.7.12)
**********************************************************************
PSUADE - A Problem Solving environment for 
Uncertainty Analysis and Design Exploration (1.7.12)
(for help, enter <help>)
======================================================================
psuade> readInput ERROR: fixed input format for input 2
syntax: fixed 1 X1 = 0.0
ERROR: file PREVIE~1 either not found or in wrong format.
psuade> ERROR: no data (load sample first).
psuade> psuade terminates ...

**Comment by fsoepyan** [comment]
- I think the reason we're seeing the error messages is because UQ cannot handle variables with spaces in their names
- For example, if you have a variable called "example x1", then converting it to "example_x1" should fix the issue
- I will test FOQUS, and I will keep you posted

**Comment by fsoepyan** [comment]
- I deleted the string type variable, and UQ managed to run (i.e., I can "Launch" the samples)
- I'm still keeping this issue open, as this fix may come in useful in the long run

**Comment by sotorrio1** [comment]
@fsoepyan I'm not sure I quite understand the issue. Do you have a session file I can use to reproduce this? Thanks!

**Comment by fsoepyan** [comment]
Currently, we do not have any applications where string type of variables are required in the FOQUS Flowsheet. Therefore, I will close this issue.

If we need to, we can reopen this issue in the future.
