### ISSUE TITLE
Fix the in-app documentation

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#344]
If the LaTeX generated manual could be hosted on a separate site (like https://www.acceleratecarboncapture.org/) then we could simplify the build/install instructions as the app could point to this location for in-app documentation.

**Comment by ksbeattie** [comment]
This in-app doc could point to either the Sphinx generated docs or the above site, depending on how/where we decide to host it.

Related to #375

**Comment by eslickj** [comment]
Removed in-app docs.  Will rely on online docs, or user can build a local copy, but view in a regular web browser.
