### ISSUE TITLE
Get Sphinx docs published

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#375]
Using the github.io site.

**Comment by fsoepyan** [comment]
Questions:
- What website do I need to go to in order to download/install Sphinx?
- After downloading the latest version of FOQUS from GitHub, is there anything I need to do to convert the tex files to Sphinx files?

**Comment by ksbeattie** [comment]
@fsoepyan, in the `docs/` dir, after doing the normal install steps (pip install, python setup.py) you should be able to run `make html` (on linux) or `make.bat html` (on Windows) to generate the documentation.  It will be built into a `build/html/` subdir of docs.  From there you can view those files in a web browser.

I'm still working on getting that done in a way so that they are viewable from everywhere...

**Comment by ksbeattie** [comment]
Notes on progress:
When using the `gh_pages` branch, then the entirely of the contents of that branch is published.  So all of the contents would need to be removed (except document sources) and then built into a dir structure that works.

At that point, I think creating an entirely separate repo for docs would be easier.

**Comment by fsoepyan** [comment]
@ksbeattie: Thank you! The make.bat html command works.

**Comment by ksbeattie** [comment]
I've got this working using GitHub's IO pages:

https://ccsi-toolset.github.io/FOQUS/

It's a manual process to update the docs, where I build in one clone of master, then copy the build/html/ tree into a different clone on the gh-pages branch.  Ugly, but working for now.
