### ISSUE TITLE
Requirements Problems

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#376]
I'm still having some problems with requirements. Specifically after installing FOQUS I often have to uninstall and reinstall adodbapi and python-dateutil.  After that things work right.

I'm not sure why these things happen, but for adodbapi, the only clue I have is that it is also included in pywin32, but a version with a bug.  The bug is fixed in a newer version of adodbapi, and I include that version in requirements.txt but it doesn't seem to help.  For now the only idea I have is to experiment with the installation order.  In the case of dateutil, it is installed by TurbineClient.  I tried including a specific version in the FOQUS requirements to possibly force it to be reinstalled, but it didn't help.  

The only idea I have it that some required packages are causing wrong or broken versions of these packages to be installed.  I don't really know how to solve that, but at least be aware that to use Turbine you may need to uninstall and reinstall these two packages.

**Comment by CSRussell2319** [comment]
Yes, I had the same issue yesterday when installing the Python 3 version of Foqus/Turbine. I needed to reinstall the "python-dateutil" package and I needed to install tqdm. Adodbapi was oddly okay on my machine.

**Comment by ksbeattie** [comment]
I just noticed that there were both a `py-dateutil` (version 2.2) package as well as a `python-dateutil` (version 2.5) installed after the "normal" install steps (`pip install -r requirements.txt`, `python setup.py develop`)

I did a `pip uninstall` on both the dateutils, then a `pip install python-dateutil` (which installed version 2.8) which seemed to satisfy the dateutil problem (but not others...)

**Comment by eslickj** [comment]
Could be addressed by https://github.com/CCSI-Toolset/turb_client/pull/8.  I was a little reckless in making the change, but I'm pretty sure that is the source of the problem.  I believe that py-dateutil and python-dateutil are the same thing just that at some version the name changed, so installing both will mess things up.  I'm going to remove the install for python-dateutil from requirements.txt.  It was an attempt to fix the problem that didn't work.

**Comment by eslickj** [comment]
Further fixed in PR #410.  Hopefully when these are merged, these issues will go away.

**Comment by ksbeattie** [comment]
@eslickj says this is closable
