### ISSUE TITLE
Documentation update for release

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#384]
The documentation needs to be updated for the Feb release
- [x] review of installation instructions (all) (see #387)
- [x] sorting and filtering (@jeslick or @fsoepyan )
- [x] Initial SDOE documentation

**Comment by fsoepyan** [comment]
- In the Install.md file, the code in Step 8 reads: pip install -r requirements.txt
- However, in the FOQUS folder downloaded from GitHub, the file name is: requirments.txt (one "e" is missing)
- Do we want to change the file name, or do we want to change the documentation in Install.md?

**Comment by ksbeattie** [comment]
We should rename to the file to the correct spelling: "requirements.txt".

**Comment by ksbeattie** [comment]
The command:
`conda create -n foqus -python=3`
Should be:
`conda create -n foqus python=3`
without the '-' before the 'python'

**Comment by fsoepyan** [comment]
We need to add the description for SDOE to docs\source\chapt_intro\index.rst

**Comment by ksbeattie** [comment]
@candcook & @atowfiq: See @fsoepyan suggestion above.  Editing the file docs/source/index.rst is the place where this would happen.

**Comment by eslickj** [comment]
I think I fixed the sorting and filtering a bit ago, so I'll check it off.

**Comment by sotorrio1** [comment]
I just approved and merged PR #418 so now the main repo has initial documentation for the SDOE module.

**Comment by eslickj** [comment]
I added the install instructions to the sphinx docs.  Once those are published, we can probably remove install.md and update the readme to point to the published sphinx docs.

**Comment by ksbeattie** [comment]
The docs are published now.  This should be the new (hopefully) permanent link for it:

https://foqus.readthedocs.io/en/latest/

**Comment by sotorrio1** [comment]
They look great!

**Comment by ksbeattie** [comment]
@perrenyang will review the install docs as part of setting up for AppVeyor

**Comment by ksbeattie** [comment]
@perrenyang says she's finished a successful walk-through of the new install instructions, so I'm closing this.
