### ISSUE TITLE
Improvements to generated foqus.bat file

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#388]
This is taken from a comment in PR #366 by @CSRussell2319:

The batch file seemed to be missing an ending quotation when I tried using it. Also, it might be better to use /K instead of /C since the user can't see any error messages from launching foqus if it closes automatically (I had an error about tqdm not being installed that I had to manually check since the cmd window closed before I could read the error). This could be done by creating an additional file labeled "Debug" that has the /K included. You removed the option to install turbine via ssh, which is needed for my corporate proxy to work. The batch file should be added to the git ignore list if it hasn't been already.

**Comment by ksbeattie** [comment]
@eslickj also needs to get the script to handle arguments.

@CSRussell2319 will try to show an example of how it didn't work if run within a conda environment.  That ending quotation mark seemed needed.

**Comment by eslickj** [comment]
Think the is taken care of in PR #410.  There was indeed a " missing.  I also added catching command like args and added a foqus_debug.bat that will hold the cmd window open even after FOQUS closes.
