### ISSUE TITLE
simulator20.exe ?

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#391]
There's a Windows executable checked in:
`examples/UQ/simulator20.exe`

We should either remove it, or if it's needed, it should be included as a separate download and not part of the source.

Given that it came in with commit 1cc755a from Jeremy with the log "Restore empty files", I'm going to guess this was a mistake and we should just remove it.

Anyone know anything more about this file?

**Comment by sotorrio1** [comment]
I don't know anything at all about that file, but I don't think it's being used in any of the UQ tutorial examples so I think it should be ok to remove it.

**Comment by ksbeattie** [comment]
Related to #392, @ngbrenda says to remove all of examples/UQ/* and they will refresh that with more up-to-date examples in a future PR.

**Comment by sotorrio1** [comment]
PR #405 takes care of this
