### ISSUE TITLE
DenPostSample.gz ?

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#392]
Is this still dir needed?

`examples/UQ/test_suite/Phoenix/DensityModel/`

Is has 5 files there:
```
-rw-r--r--  1 ksb  staff  2378205 Sep 25 12:21 DenPostSample.gz
-rw-r--r--  1 ksb  staff        0 Sep 25 12:21 SmallSample.psuade
-rw-r--r--  1 ksb  staff        0 Sep 25 12:21 densitySample.psuade
-rw-r--r--  1 ksb  staff        0 Sep 25 12:21 expdataDen
-rw-r--r--  1 ksb  staff        0 Sep 25 12:21 expdataDen.orig
```

The .gz file is corrupt and the others are empty!

The corruption could have come from when we brought things over from svn, binary files didn't do well with that transition.  I could try pulling it again...

**Comment by sotorrio1** [comment]
This happened 2 years ago so I have no clue. But if the files are empty, I guess removing the directory would be fine.

**Comment by ksbeattie** [comment]
@ngbrenda says that we can remove all Phoenix related work.

**Comment by sotorrio1** [comment]
PR #405 takes care of this
