### ISSUE TITLE
Delete unneeded branches

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#394]
@ksbeattie:

Can you please delete the "fsoepyan-patch1" and "fsoepyan-patch2" branches from the CCSI-Toolset/FOQUS repository?

I don't think we need those branches anymore, as the changes have been merged, but I don't have the rights to delete branches.

Thank you!

**Comment by ksbeattie** [comment]
Sure thing.  Done.

In the future, you should be able to delete your own branches by either clicking on the [branches](https://github.com/CCSI-Toolset/FOQUS/branches) link (at the top of the main repo page) or by clicking the "Delete Branch" button at the bottom of a PR that merged in changes from that branch.
