### ISSUE TITLE
Transpose Flowsheet Table

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#398]
@eslickj and I received a suggestion that if the Flowsheet table is transposed, where the rows show the variable names, and the columns show the numbers for each FOQUS run, reading the table would be easier.

**Comment by fsoepyan** [comment]
- There is an easy solution, which is to use the "Copy Data to Clipboard" feature in the Flowsheet table, pasting the data into Excel, then in Excel, we copy and do "Paste Special" and "Transpose".
- Would anyone object if we close this issue? (I'm moving this issue to "High" priority in the project board.)

**Comment by anujad95** [comment]
@fsoepyan, i agree with you, and have tried this. I think this issue can be closed.
