### ISSUE TITLE
Basic Data tab

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#408]
Is there anyone using the basic data tab at all? I was wondering if we should delete this tab completely. As you can see the GUI is all messed up and I was planning on fixing it but only if the module is relevant. As of now, basic data is basically SolventFit and there are a few group boxes and frames that are not even being used.

**Comment by fsoepyan** [comment]
I'm not using the Basic Data tab. The only time I used it was to test it.

**Comment by eslickj** [comment]
I can say I've never used it, and I'm not opposed to removing it.

**Comment by CSRussell2319** [comment]
Not using it. I only went through it to follow examples/test to find bugs. I don't think we officially have anyone supporting the feature either.

**Comment by sotorrio1** [comment]
That's what I was suspecting. We can discuss further during tomorrow's call, but I propose we get rid of the whole module.

**Comment by ksbeattie** [comment]
I'll bring this up to Mike & Ben.

**Comment by ksbeattie** [comment]
I've sent a note to Mike, Ben and John Shinn about this.  I'll let you all know what I hear.

Is it worth keeping it as an "entry-level" module for introducing new users to the tool?  That and maybe a place where simple "smoke tests" live?

Not necessarily trying to argue against removing it, just trying to think if there might still be some value in keeping it that is worth the effort to keep maintaining it.

**Comment by sotorrio1** [comment]
I didn't write the code so I'm not completely sure what this module does and if it's worth keeping it. Let me know what they say and we'll take it from there :)

**Comment by ksbeattie** [comment]
Mike's response is:

> From the below it seems to me that we should allow the surrogates capabilities to generalize the approaches currently in the basic data tab, albeit in a less specific way. I'm ok with the idea of deleting Basic Data in favor of surrogates, with two considerations: 1. That no stakeholder is doing critical work with basic data (I would imagine they aren't, but invite the team to weight in) 2. We consider preserving any residual capabilities in basic data that are "mathematically general" and not available in surrogates.

@sotorrio1 suggested changing a setting to make the tab disappear and will follow up with @ngbrenda on making we are not abandoning any functionality.

**Comment by sotorrio1** [comment]
PR #474

**Comment by ksbeattie** [comment]
Although PR #474 has been merged, removing the basic data tab, we'll close #176 and #207 but leave leave this issue open to revisit on whether to fix those issues for good, or remove the tab for good.

**Comment by ksbeattie** [comment]
@ksbeattie will follow up with Mike on that removing basic data does remove solventfit functionality (which was already broken).  Adding it back, and fixing it will require some effort.

**Comment by fsoepyan** [comment]
I talked with @eslickj, and according to @eslickj:
- The algorithm in the "Basic Data" tab is similar to the algorithm in the "Surrogates" tab.
- It's possible that the "Basic Data" tab is linked to the "Surrogates" tab.
- However, we both agree that no tab is linked to the "Basic Data" tab.
- At the moment, the code for "Basic Data" is still there, but the "Basic Data" tab is hidden.
- In the short run, this is fine.
- But maybe in the long run, once we can confirm that nobody uses "Basic Data", we can also delete the code for "Basic Data".

**Comment by ksbeattie** [comment]
@ksbeattie will follow up with Mike & Brenda on this.

**Comment by ksbeattie** [comment]
Closing this now, waiting for a future request to remove the code for this now-hidden tab.
