### ISSUE TITLE
Flowsheet: Disable most editing while optimization or simulation is running

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#41]
From JIRA:
- Reporter: John Eslick (@eslickj)
- Assignee: Megha Sandesh
- Original title: Disable most editing while optimization or simulation is running
- Created: 30/Oct/13 11:44 AM
- Updated: 13/Jan/16 8:44 AM

Description:

Changing a flowsheet or optimization settings while a problem is running could cause confusion or errors.  Need to disable editing most things while optimization or simulation is running.

**Comment by eslickj** [comment]
Any changes made to a flowsheet while a simulation is running are undone when the run finishes.  That's the solution we'll have to live with.
