### ISSUE TITLE
SSH to install from git repo

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#412]
Since moving dependencies out of setup.py into requirements.txt, we lost the option to install TurbineClient from github using ssh.  I'm not sure of the cleanest way to make this option available again.  Should we just add a requirements_ssh.txt?

**Comment by CSRussell2319** [comment]
Currently I have to manually install the turbine client. I'm not sure if that's an issue with the requirements.txt file or with the setup file being different. I still like the idea of having an ssh argument that can be added to the setup command that will choose which requirements file to use.

**Comment by eslickj** [comment]
Right now the instructions say to install requirements first so you do like

> pip install -r requirements.txt
> python setup.py develop

So there are no requirements options in setup.py any more.   It would just be the user deciding which requirements file to use.

**Comment by CSRussell2319** [comment]
Yes, when the swap was made to use the requirements.txt I didn't notice the instructions were updated. I had assumed the setup.py looked for the requirements.txt file and installed them before proceeding.

**Comment by eslickj** [comment]
Probably will be fixed with the Turbine Client pip install.

**Comment by CSRussell2319** [comment]
Is adding Turbine Client to pip part of an existing issue? If not I think this should remain open

**Comment by ksbeattie** [comment]
@CSRussell2319, it is: https://github.com/CCSI-Toolset/turb_client/issues/4
