### ISSUE TITLE
Turbine: TurbineLiteDB

### ISSUE THREAD

**Issue by johnbaca** [CCSI-Toolset/FOQUS#413]
##When running an uncertainty analysis of my node with a local flowsheet, I've been getting the error TurbineLiteDB is not defined and pops up an error message that shows python3 is unresponsive. Before I ran the uncertainty analysis, I went to setting to test the turbine, which came up with a notification of "The Turbine configuration is ok". Also used task manager to restart the TurbineWebAPIService, but continued to receive the same errors.

![image](https://user-images.githubusercontent.com/47044799/53358838-997d2c00-38ee-11e9-94bd-4916a901e7e4.png)

**Comment by eslickj** [comment]
Can you give me more of the log?  turbineLiteBD is part of FOQUS, but FOQUS will run without it if it fails, since it is a windows only thing.  Most likely there are some messages about it when FOQUS first starts.

We were having trouble with the adodbapi version, but I thought we had resolved it.  Could be another problem.

**Comment by johnbaca** [comment]
![error](https://user-images.githubusercontent.com/47044799/53505851-f3f2c580-3a71-11e9-8fff-fc8733ccddb3.JPG)

@eslickj here is the whole log for running it this morning.

**Comment by eslickj** [comment]
Yeah.  Just uninstall and reinstall adodbapi base.  You need the very latest version.  Pywin32 ships with a version that has this problem.  Requirements.txt should specify the right version.  I haven't been having this problem, but if you follow the install instructions and still have this problem let me know.

**Comment by johnbaca** [comment]
Uninstalling and re-installing adodbapi fixed the issue. Thank you

**Comment by ksbeattie** [comment]
@johnbaca sounds like we can close this now.  Feel free to re-open it if I've got that wrong.
