### ISSUE TITLE
Problem running Surrogates in Py3 FOQUS

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#420]
- I tried to generate an ALAMO surrogate model using the Py3 version of FOQUS (which I downloaded from the master branch)
- For the data, I used all of the results from my previous runs
- I selected the variables of interest
- I left most of the method settings as default
- When I ran ALAMO, FOQUS froze at this screen, and I had to close and re-open FOQUS:

<img width="800" alt="foqus_surrogates_03_05_2019" src="https://user-images.githubusercontent.com/30811140/53827515-50aa2080-3f49-11e9-8ee8-b17d4914dbfd.png">

**Comment by eslickj** [comment]
This is fixed, but for other reasons ACOSSO and BSS-ANOVA don't work.

**Comment by ksbeattie** [comment]
@eslickj, are those other reasons captured in an issue somewhere?  Or even just that they don't work?
