### ISSUE TITLE
 Problems installing updated version of FOQUS on my Mac

### ISSUE THREAD

**Issue by candcook** [CCSI-Toolset/FOQUS#427]
Chris came over to help me install a new version of FOQUS from Pedro's fork so I could see the latest version of the SDoE module. 
We followed the instructions and when we tried
foqus.py
we got the following error message:
![image](https://user-images.githubusercontent.com/24737485/53909028-e313f800-400d-11e9-85a2-f4286ce7aa80.png)

**Comment by sotorrio1** [comment]
@candcook & @CSRussell2319 I think this was fixed in the master branch by @eslickj 
I've just updated my fork with the current master repo. Sorry about that, you can try now

**Comment by sotorrio1** [comment]
I think @candcook and @CSRussell2319 solved this. Please confirm and close the issue. Thanks!

**Comment by eslickj** [comment]
The web stuff is totally removed, so its probably safe to close this, but if anything else comes up don't hesitate to reopen it or create a new issue.

**Comment by sotorrio1** [comment]
totally agree, this should be fixed.
