### ISSUE TITLE
Require git client?

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#435]
The installation instructions say we need a git client.  That may be true for installing Tubine Client off github, but if we get the non-github pip install, we can probably drop the git client requirement from the install instructions.  I'm actually not really sure if you need the git client now.  If we can lose that requirement before the release the install will seem a bit simpler.

**Comment by ksbeattie** [comment]
I agree we should drop that requirement.

This issue depends on: https://github.com/CCSI-Toolset/turb_client/issues/4

**Comment by CSRussell2319** [comment]
I agree with the exception that we need to have developer installation/setup instructions somewhere. By removing things like this I, or others in my position, need to explain how to properly use this repository with Git. Other than our developer meetings there is little discussion of how we want newcomers to make contributions (branches, forks, etc) or how we expect changes to be tested using automated testing.

**Comment by ksbeattie** [comment]
I'll remove this section from the install.rst doc.
