### ISSUE TITLE
Add instuctions for data filter entry

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#457]
It's almost impossible to figure out how to write a data filter without looking at the documentation.  I think we may want to add a frame to the dialog box that provides some basic instructions.

**Comment by anujad95** [comment]
Data Filters are present in the Flowsheet, Uncertainty, and Surrogates tab. Just to confirm, we should add data filter instructions to this dialog box in each of the modules?:
![image](https://user-images.githubusercontent.com/47067166/65781902-89def380-e11a-11e9-9135-885c7315ec16.png)
