### ISSUE TITLE
Problem opening FOQUS

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#463]
- I downloaded the latest version of FOQUS from GitHub on 4/5/19
- I typed the 4 codes shown in the installation guide: conda activate foqus, pip install -r requirements.txt, python setup.py develop, foqus.bat
- After typing foqus.bat, I got this error message:

![image](https://user-images.githubusercontent.com/30811140/55637924-13c58980-5794-11e9-9cb7-7814d0842a91.png)

**Comment by fsoepyan** [comment]
Status update: When I opened a previously-downloaded version of FOQUS (from 3/15/19), I had to type in pip install -r requirements.txt, python setup.py develop, and foqus.bat to successfully open FOQUS.

**Comment by eslickj** [comment]
This is same as issue #462
