### ISSUE TITLE
Parallel computing: AWS no longer supports node.js version 6.10

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#469]
AWS needs to be updated, and this work is in progress.

Initial work done in PR #512

**Comment by boverhof** [comment]
### Deployment with NodeJS 8.10
Make a few changes to the deployment configuration environment.  Was able to deploy out using NodeJS 8.10.  Initial testing has passed.

**Comment by ksbeattie** [comment]
@boverhof says more work needs to be done on the post-session-start.

**Comment by ksbeattie** [comment]
This is going to have to wait until after the upload error is resolved, due to priority, not dependency.

**Comment by boverhof** [comment]
Most of this work has been done, at least to the point where integration testing is currently being done.  There could be a few odds and ends to clean up, but generally this is done.
