### ISSUE TITLE
Split FOQUS UI and FOQUS Consumer?

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#472]
I think this issue is worth discussing, but due to the level of effort required it may not be feasible.

FOQUS consumer and FOQUS UI are now one thing. There are two ways to run FOQUS jobs. "Local," which means run FOQUS jobs in the same process as the UI, and "remote" which means send jobs to Turbine and those jobs will be run by a FOQUS consumer.

Ideally we should only have one path for running jobs. We should split the consumer out of the UI and only allow the "remote" style jobs. This is a bit of work, but it should be pretty straight forward for Windows. There are two main problems with this approach 1) for jobs that run very fast, having the jobs run in separate consumer is much much slower, and 2) TurbineLite only exists for Windows and if you want to run simulations on your machine and not some remote Windows machine, you'd need TurbineLite to manage jobs for local consumers.

The benifit, of this this is that it makes things a lot simpler and things like different parallel simulation workflows would be a lot easier to implement. Although there is nothing really complicated about this, it is a lot of work. I may also require a new corss-platform TurbineLite, and that would need the same REST interface and Turbine Gateway.

This is sort of related to #461

**Comment by ksbeattie** [comment]
It's hard to know the value of the trade-offs here without better knowledge on how this would impact users.

**Comment by ksbeattie** [comment]
@candcook, @eslickj is feeling that this is probably more effort than it's work or we have bandwidth for, so we're going to close this issue.
