### ISSUE TITLE
LBNL CIT/DevOps Server

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#476]
# summary
Configure new server for CIT and DevOps tasks.
## Operating System
CentOS 7.6

**Comment by ksbeattie** [comment]
@boverhof is working on building out a test OVRT system at NERSC, after which this one will get installed.

**Comment by boverhof** [comment]
OVIRT 4.3 is running

https://keystone.lbl.gov

fife is the backend node where glusterfs and VMs via libvirt/kvm are running.
