### ISSUE TITLE
Running foqusPSUADEClient.py raises issues with python version

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#482]
When running OUU, FOQUS calls the foqusPSUADEClient.py script that takes two arguments; an input file and an output file. 

When running on Windows the user needs to make sure the register keys are in accordance with the documentation updated through @fsoepyan PR #480 

When running on iOS there is no such thing as register keys. I've found that when running a bash script iOS is ignoring the conda environment you're running on; but if we add the following line of code to the beginning of the script, it works:

#!/anaconda3/envs/foqus/bin/python

The problem here is that the user needs to name the environment 'foqus' so this line of code works. If the user decides not to follow the installation instructions and name the environment slightly different, it will fail. 

This issue is more like asking for help/ideas on how to handle this in a generic way.

**Comment by ksbeattie** [comment]
A few ideas to investigate:
- Change the #! line to `#!/usr/bin/env python` which will use the python found on the current's envronment's $PATH
- Make sure PATH has the correct bin on it.

**Comment by sotorrio1** [comment]
Just double checked and the line `#!/usr/bin/env python` works. I'll create a PR to update this

**Comment by sotorrio1** [comment]
PR #490 should take care of this. Once the PR is approved and merged I will close this issue.

**Comment by eslickj** [comment]
On the windows side, I have a suggestion contained in PR #493

**Comment by ksbeattie** [comment]
@sotorrio1 will work on a similar change, as @eslickj used above, for OUU without changes to the registry for the next release.

**Comment by ksbeattie** [comment]
@sotorrio1 will get to this soon.

**Comment by sotorrio1** [comment]
PR #575 should take care of this

**Comment by fsoepyan** [comment]
PR #575 has been merged, so I will close this issue.
