### ISSUE TITLE
Additional Step in Parameter Estimation Tutorial Manual required

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#483]
In the Parameter Estimation Tutorial documentation, after Step 13, an additional step of adding ‘ydata’ as an input variable within the model node is required. This needs to be done in order to get 'ydata' as a variable within the 'Optimization' variables display window, and implement Step 16.

**Comment by anujad95** [comment]
The commit: “Update parameter_est.rst” takes care of Issue #483

**Comment by ksbeattie** [comment]
I believe @anujad95 is referring to commit 53f9bab70afc5fad34414204231d8e65077e0c88 which came in (somewhat unintentionally) with PR #499.
