### ISSUE TITLE
UQ Tutorial 1 Sample Design

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#484]
“Simulation Ensemble creation and execution” tutorial: In accordance with step 11.2, “Simulation Ensemble Added” figure in step 17 must display ‘Sample Deign’ as ‘Latin Hypercube’. Instead, it displays ‘Monte Carlo’  
![image](https://user-images.githubusercontent.com/47067166/58028295-69f25000-7ae8-11e9-9a0f-5aca8ba35561.png)

**Comment by sotorrio1** [comment]
I can update the screenshot in the documentation.

**Comment by ksbeattie** [comment]
@anujad95 will do this

**Comment by sotorrio1** [comment]
@anujad95 did your PR #499 take care of this issue?

**Comment by ksbeattie** [comment]
Yes, it's fixed.
