### ISSUE TITLE
UQ Tutorial 1 different result obtained

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#486]
In the UQ tutorial “Simulation Ensemble creation and execution”, when implemented in Foqus, the statistical inference values ie: Sample Mean, Std Dev etc, along with the Probability Distribution bar plot for Uncertainty Analysis slightly differ from the tutorial manual. 
![image](https://user-images.githubusercontent.com/47067166/58108750-65966780-7bba-11e9-8321-9c9282e3e655.png)
_(Uncertainty Analysis Result (Step 18.4): Tutorial Manual)_ 

![image](https://user-images.githubusercontent.com/47067166/58108848-8f4f8e80-7bba-11e9-9243-2acf3cdddc07.png)
_(Uncertainty Analysis Result: Software Implementation)_

**Comment by fsoepyan** [comment]
- Were these samples randomly generated using the distributions of the uncertain parameters?
- If so, then the variations in the plots would be expected.

**Comment by anujad95** [comment]
The samples were generated using the Latin Hypercube sampling scheme, in which case, there may be a possibility of variation in statistics. So, i would like to confirm if the result image in the documentation needs to be updated.

**Comment by ksbeattie** [comment]
@sotorrio1 will take a look at this.

**Comment by sotorrio1** [comment]
After reviewing the first UQ tutorial in the FOQUS documentation, I think the screenshots are from different runs that @ou3llnl and/or @ngbrenda did. If you follow the instructions and take a close look to the screenshots, they are not consistent. 

- Step 9 tells the user to change the type of X2 to "Fixed" and enter the value 5 into the default column. Later in step 17 you can see that column "Rosenbrock.x2" in the "Inspection/Deletion/Output Value Modification" table is not a fixed value of 5. 

- Step 10 tells the user to select "Latin Hypercube" as sampling scheme and 500 as the number of samples. Later in step 17 you can see in the "Ensemble Info" table that the sample design used was "Monte Carlo" and the sample size 1000. Same in step 18-2, the ensemble summary within the simulation ensemble analysis dialog shows Monte Carlo as the sample design and size 1000. 

For all those reasons, @anujad95 is not getting the same answer that the image in step 18-4. 

If we want consistency within the screenshots and the instructions in the tutorial, we need to update those screenshots to match what the instructions are telling the user to do.

**Comment by sotorrio1** [comment]
PR #501 takes care of this issue
