### ISSUE TITLE
Add instructions on how to load CSV samples into UQ

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#487]
- If the instructions are not in the user's manual yet, we need to add the instructions on how to load a CSV sample file into UQ.
- Doing this would be helpful for people who are interested in automatically running a set of input conditions in FOQUS.
- By doing this, maybe we can also delete some of the Flowsheet Data Table functions that are broken, and take care of #456.

**Comment by ksbeattie** [comment]
@fsoepyan will add some documentation on this.
