### ISSUE TITLE
Different Interface for "Filtering" tab within UQ Module

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#489]
In the Reference Documentation for UQ, the "Filtering Tab" image after (15) does not match the actual software setup interface. 
![image](https://user-images.githubusercontent.com/47067166/58113735-3553c680-7bc4-11e9-8cea-4f0dedcb872d.png)
_(Filtering Tab-Reference Documentation)_

![image](https://user-images.githubusercontent.com/47067166/58118129-3853b480-7bce-11e9-84e1-11fb8f2572eb.png)
_(Filtering Tab-Software)_

Recommendation: According to the actual software setup, the the Filtering Tab image, along with the description in (16),(17),(18) in the UQ Reference Documentation must be changed as follows:
![image](https://user-images.githubusercontent.com/47067166/58118190-55888300-7bce-11e9-8e99-2b81fbf6a8c5.png)

![image](https://user-images.githubusercontent.com/47067166/58118272-7f41aa00-7bce-11e9-9450-5f700bc47c30.png)

16. Click on Add/Edit Filters, in the Flowsheet Results window within the "Filtering Tab"
17.1. Within the Filter Dialog Box, Click on "New Filter" to add a filter
17.2. Enter a filter expression in python format. Variables can be dragged into the expression, from the "Columns", click Done. 
18. Select a "Current Filter" after which the the filtered ensemble can be saved by clicking on " Save as New Ensemble"

Taking this forward, Step 4 in Data Manipulation-Filtering tutorial must be replaced by the following:
![image](https://user-images.githubusercontent.com/47067166/58118753-87e6b000-7bcf-11e9-9f71-14dfed42aa39.png)

![image](https://user-images.githubusercontent.com/47067166/58118872-c67c6a80-7bcf-11e9-9aae-bdf3d58f789e.png)
4. Filtering the loaded simulation ensemble based on output values is performed. 
   1. Click on "New Filter", and create a filter named "f1"
   2. Add the Filter Expression c("output.status") == 0, since the user should keep only the          samples in which the output parameter status is “0.”
   3. Click "Done"
   4. Select 'f1' as the " Current Filter" in the Flowsheet Result window within "Filtering Tab"
   5. Once the Filtering is complete, click on "Save as New Ensemble" and a new row should be added to the simulation table

**Comment by sotorrio1** [comment]
@anujad95 Thank you. We updated the filtering capability to the same filtering @eslickj uses in the Surrogates tab a while ago but never got to update the documentation.

**Comment by anujad95** [comment]
No worries. So, i would like to ask if the documentation can be updated accordingly.

**Comment by sotorrio1** [comment]
@anujad95 of course, thanks for creating the issue so it helps as a reminder to update the docs :)

**Comment by anujad95** [comment]
Sure, no problem! the surrogate modeling ALAMO tutorial also needs to be updated from step 27 through 29. The following filter dialog box works for implementing the filter:
![image](https://user-images.githubusercontent.com/47067166/58124727-e1a1a700-7bdc-11e9-8613-ad780e0a5166.png)

**Comment by sotorrio1** [comment]
@fsoepyan and @eslickj are in charge of the surrogates tab. I'm the go-to person for UQ, OUU and SDOE

**Comment by ksbeattie** [comment]
@anujad95 will tackle this on too.

**Comment by anujad95** [comment]
This issue is taken care of by the following commits:
1.	Update alamo.rst 
2.	Update reference.rst
3.	Update data.rst
