### ISSUE TITLE
Clarity on types of input uncertain parameters required: UQ Tutorial 4

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#492]
In the UQ Tutorial Manual on Response Surface Based Mixed Analysis, Mixed Epistemic-Aleatory Uncertainty Analysis, the following step is mentioned:
"In the input table, designate the parameter Type (“Epistemic”, “Aleatory” or “Fixed”) and the corresponding information for each input. Once complete, click Analyze."
![image](https://user-images.githubusercontent.com/47067166/58177960-4f98ad80-7c73-11e9-9bce-372207c6d512.png)

This is followed by a result plot of multiple CDF's:
![image](https://user-images.githubusercontent.com/47067166/58177293-1d3a8080-7c72-11e9-93a7-690e562a1fc8.png)

Although a similar plot is obtained in the software when at least one of the uncertain parameters is epistemic, in the above plot displayed in tutorial manual, clarity on the type of input uncertain parameters is required, to know the specific case it corresponds to.

**Comment by sotorrio1** [comment]
Since I didn't create this specific screenshot is hard to tell which inputs are epistemic.

**Comment by anujad95** [comment]
Sure, we can do that. Would you suggest updating the documentation accordingly?

**Comment by sotorrio1** [comment]
Personally, I don't think it's a big deal and users can play around choosing the epistemic inputs they want; but if we want to have a consistent tutorial, we can pick two or three epistemic inputs and change the two screenshots in the documentation to show which inputs are epistemic and how the new plot looks like.

**Comment by anujad95** [comment]
Sure, i can make the required changes in the manual to ensure that we have a consistent tutorial.

**Comment by sotorrio1** [comment]
@anujad95 Thanks! I appreciate that :)

**Comment by anujad95** [comment]
The commit: “Update rs.rst” takes care of Issue #492
