### ISSUE TITLE
Create videos on how to use FOQUS

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#506]
We would like to create videos on how to use FOQUS, which would be helpful for future users in the long run.

These videos may include:

FOQUS basics (@fsoepyan): (I plan on using a simple Python function/model in the Flowsheet.)
- How to open FOQUS (@fsoepyan)
- [x] Recording
- [x] Editing and upload
- How to setup and run the Flowsheet (@fsoepyan)
- [x] Recording
- [x] Editing and upload
- How to automatically run a set of input conditions in FOQUS (@fsoepyan)
- [x] Recording
- [x] Editing and upload
- How to connect multiple models via an edge in Flowsheet (@fsoepyan)
- [x] Recording
- [x] Editing and upload
- How tear streams work when we have iterative simulations in the Flowsheet (@fsoepyan)
- [x] Recording
- [x] Editing and upload

FOQUS usage: (For these videos, I think using simple examples should be fine.)
- How to upload an Excel model into SimSinter and Turbine, and run the model in Flowsheet (@fsoepyan)
- [x] Recording
- [x] Editing and upload
- How to upload an Aspen Plus model into SimSinter and Turbine, and run the model in Flowsheet (@fsoepyan)
- [x] Recording
- [x] Editing and upload
- How to upload an ACM model into SimSinter and Turbine, and run the model in Flowsheet
- [x] Recording
- [x] Editing and upload
- How to use Optimization
- [x] Recording
- [x] Editing and upload
- How to use UQ
- [x] Recording
- [x] Editing and upload
- How to use OUU using the OUU tab
- [x] Recording
- [x] Editing and upload
- How to use OUU using the Optimization tab
- [x] Recording
- [x] Editing and upload
- How to use Surrogates
- [x] Recording
- [x] Editing and upload
- How to use SDOE (@sotorrio1 & @candcook)
- [ ] Recording
- [ ] Editing and upload

**Comment by fsoepyan** [comment]
I am currently in the process of editing the video on how to upload an Excel file into SimSinter and Turbine, and how to run the Flowsheet for that Excel file.

**Comment by fsoepyan** [comment]
- To record and edit the videos, I have been using VSDC Free Video Editor.
- You can download this software from: http://www.videosoftdev.com/free-video-editor

**Comment by candcook** [comment]
Thanks Pedro … I will have to check on what the restrictions are for doing this here at LANL. They generally are a bit nervous about us recording things :-)

Thanks,
Christine

**Comment by sotorrio1** [comment]
@candcook same here, we also have to ask what the guidelines are for something like this.

**Comment by fsoepyan** [comment]
I am currently creating the outline for the FOQUS basics videos.

**Comment by fsoepyan** [comment]
I completed the outline for the FOQUS basics videos, and my next step is to record the videos.

**Comment by fsoepyan** [comment]
- The recording of all 5 of the FOQUS basics videos is complete.
- The next step is to edit these videos, and upload the videos to YouTube.

**Comment by fsoepyan** [comment]
I have recorded all the videos I wanted to record for this GitHub issue. The NETL Multimedia team is in the process of editing these videos:
- The 5 FOQUS Basics videos with a due date of Aug. 22
- I will send them the 8 FOQUS Usage videos soon

**Comment by candcook** [comment]
Hi,

What software did you use for this? I am planning on making some videos for the SDoE module.

Thanks,
Christine

**Comment by fsoepyan** [comment]
@candcook: The software I used for the recording was VSDC Free Video Editor. You can download this software from: http://www.videosoftdev.com/free-video-editor
You can also use this software for video editing.

**Comment by fsoepyan** [comment]
The NETL Multimedia team is in the process of editing the FOQUS videos:
- The 5 FOQUS Basics videos, with a due date of Aug. 22
- The 8 FOQUS Usage videos, with a due date of Sept. 20

**Comment by fsoepyan** [comment]
- The NETL Multimedia team has finished editing the videos.
- My next step is to watch the videos, and make or request additional edits, if needed.
- If everything looks good, I will upload the videos to YouTube.

**Comment by fsoepyan** [comment]
Status update:
- I requested NETL Multimedia to do additional editing on the videos.
- I already received the new edited videos.
- I am now in the process of adding the finishing touches to these videos, and I will upload the videos one by one.

**Comment by fsoepyan** [comment]
I have one video left to upload: the ACM video.

**Comment by fsoepyan** [comment]
I have uploaded all the videos that I recorded, so I will close this issue, and open another issue for creating a video on how to perform SDOE in FOQUS.
