### ISSUE TITLE
FOQUS Documentation

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#51]
We need to figure out what to do about documentation.  Currently the manual, which is very large, is done in LaTeX.  Most people probably won't have what they need to build the docs.  The primary way for getting FOQUS will be straight from github, so I'm not sure if there is a straight forward way for us to build the docs to be available on github, other than having someone build them and check them in.

I hate to suggest this, but should we convert the docs to something like sphinx?  At least we know that the users should be able to build the docs maybe as part of the install.  I'm not sure what's best.  @ksbeattie any ideas?

**Comment by ksbeattie** [comment]
I will work on getting Jenkins building this for the June release.

There doens't appear to be the will and time to move away from LaTeX.

**Comment by ksbeattie** [comment]
This is was fixed with 831757bb2a9a14459e421fc9c60c8881473d7164
