### ISSUE TITLE
Tool Validation with more examples

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#511]
According to the documentation, the Foqus tool has been implemented for a few cases which include simple node simulations, flowsheet with linked simulations (BFB & Cost optimization setup), recycle, etc. As the tool is being developed further with new, improved features, it might be worth to validate it simultaneously with more complex examples, & different types of carbon capture systems like solvent based (MEA) & membrane based ones. We can use the process models developed within the ProcessModels_bundle of the CCSI toolset. After implementing these, supported with concrete problem statements, we can include some of them as part of the tutorial manual/validation section. This would help in making the tool more convincing to the user, and a more extensive demonstration of its capability. Please let me know your thoughts/suggestions on this.

**Comment by ksbeattie** [comment]
@jmorgan29 will update the MEA_ssm model, see [MEA_ssm #6](https://github.com/CCSI-Toolset/MEA_ssm/issues/6) then he and @anujad95 will work on adding an example and documentation to FOQUS

**Comment by fsoepyan** [comment]
I think the example problems in the user's manual is fine, as the purpose of these examples is to get the user familiar with FOQUS.

But to motivate the user to use FOQUS, I think including the list of publications where FOQUS has been used will be a good first step.

So far, I have compiled this list of publications:

Chen, Y., Eslick, J.C., Grossmann, I.E., Miller, D.C., 2015. Simultaneous process optimization and heat integration based on rigorous process simulations. Computers and Chemical Engineering 81, 180–199.

Gao, Q., Miller, D.C., 2015. Optimization of amine-based solid sorbent chemistry for post-combustion carbon capture. Paper presented at: 2015 International Pittsburgh Coal Conference; 5–8 October 2015; Pittsburgh, PA, USA.

Ma, J., Mahapatra, P., Zitney, S.E., Biegler, L.T., Miller, D.C., 2016. D-RM Builder: A software tool for generating fast and accurate nonlinear dynamic reduced models from high-fidelity models. Computers and Chemical Engineering 94, 60–74.

Miller, D.C., Agarwal, D., Bhattacharyya, D., Boverhof, J., Chen, Y., Eslick, J., Leek, J., Ma, J., Mahapatra, P., Ng, B., Sahinidis, N.V., Tong, C., Zitney, S.E., 2017. Innovative computational tools and models for the design, optimization and control of carbon capture processes, in: Papadopoulos, A.I., Seferlis, P. (Eds.), Process Systems and Materials for CO2 Capture: Modelling, Design, Control and Integration. John Wiley & Sons Ltd, Chichester, UK, pp. 311–342.

Soepyan, F.B., Anderson-Cook, C.M., Morgan, J.C., Tong, C.H., Bhattacharyya, D., Omell, B.P., Matuszewski, M.S., Bhat, K.S., Zamarripa, M.A., Eslick, J.C., Kress, J.D., Gattiker, J.R., Russell, C.S., Ng, B., Ou, J.C., Miller, D.C., 2018. Sequential Design of Experiments to Maximize Learning from Carbon Capture Pilot Plant Testing. In: Eden, M.R., Ierapetritou, M.G., Towler, G.P. (Editors), 13th International Symposium on Process Systems Engineering (PSE 2018). Elsevier, Amsterdam, pp. 283-288.

- Can anyone please let me know your thoughts regarding this suggestion?
- If you agree that making this list is a good first step, then where in the FOQUS GitHub page and/or documentation should we include this list?

**Comment by anujad95** [comment]
Thank you for your suggestion @fsoepyan. This would be a good first step to begin with. In my opinion, we need a different section within the documentation: "Motivational Examples" where we can firstly give an overview of the different application based examples for which foqus has been used in the publications, followed by the list that you have provided. It may be worth to implement more examples apart from these, simultaneously, in order to further validate the tool. Kindly let me know your suggestions.

**Comment by ksbeattie** [comment]
@anujad95 will work on an PR in the MEA_ssm repo for bringing in updates for running on Aspen 10.

**Comment by ksbeattie** [comment]
in progress...

**Comment by anujad95** [comment]
It might be worth to have tutorial examples within each module section to be arranged in such a way that uniformity is maintained. For this, we may want to have a single process model being evaluated using all modules, to simplify the understanding of FOQUS workflow for users. Currently, the examples within each module in the tutorial manual are mostly different from each other. This makes the documentation structure slightly disintegrated in terms of examples. Any suggestions or comments on this?

**Comment by anujad95** [comment]
@fsoepyan I think its a good idea to provide users, a list of publications where FOQUS has been used. I shall include this list in the documentation.
