### ISSUE TITLE
SinterConfigGUI Image Update

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#519]
The GUI Image: _SinterConfigGUI Simulation Meta-Data with Data Completed_ in the Aspen Plus SimSinter Tutorial manual needs to be updated.

Old image:
![image](https://user-images.githubusercontent.com/47067166/59439137-b452ae00-8dc2-11e9-957a-fe601c3e5ed1.png)

Current GUI Image:
![image](https://user-images.githubusercontent.com/47067166/59439228-dd733e80-8dc2-11e9-9ee8-d0872c000ea2.png)

**Comment by fsoepyan** [comment]
PR #520 has been merged, so I will close this issue.
