### ISSUE TITLE
lack of online document interface.

### ISSUE THREAD

**Issue by TheHuangs** [CCSI-Toolset/FOQUS#521]
It's hard for the user to find the website of the online document. I recommend adding this https://foqus.readthedocs.io/en/latest/ website on the first page of this repository.

**Comment by fsoepyan** [comment]
- If you go to the FOQUS GitHub page (https://github.com/ccsi-toolset/foqus), the "README" has a section called "Documentation and User's Manual".
- The link to the documentation can be found by clicking the word "here" in the second line ("The documentation for FOQUS (including the user's manual) can be accessed by clicking here.").

**Comment by ksbeattie** [comment]
@TheHuangs, thanks for input.

The very first link on the readme (the [![Documentation Status](https://readthedocs.org/projects/foqus/badge/?version=latest)](https://foqus.readthedocs.io/en/latest/?badge=latest)) points to the documentation link you mention.  But I agree that may not be entirely clear to new users.

So, I've open a PR (#525) with some changes that hopefully make it clearer where the documentation lives.

**Comment by ksbeattie** [comment]
Hopefully with my changes in #525, this is better.
