### ISSUE TITLE
Whether Pyomo modles can be treated as a node as the same as excel? 

### ISSUE THREAD

**Issue by TheHuangs** [CCSI-Toolset/FOQUS#523]
As the title mentioned.

**Comment by anujad95** [comment]
From what i have observed, currently FOQUS does not have a separate Python Plugin that can allow importing python/pyomo codes directly. This functionality is going to be added in the tool soon. However, for the time being, you may want to try entering the entire python script of the pyomo model in the "node script" of a node added in the FOQUS flowsheet. This might work. I tried a very simple equation solving example just to check if pyomo can be imported within the node script, and it worked. I tried to implement an optimization example too. I shall keep you informed about how it works.

**Comment by TheHuangs** [comment]
@anujad95 , I hope you can provide an example of how to do this.  some screenshots may help. Thanks

**Comment by anujad95** [comment]
Sure. I shall send you the screenshots once the optimization model works. I need to check a few solver installations in my machine before getting the result. 
To give an idea about it for now, in my opinion, it can work as follows for a pyomo concrete model:
Firstly, create a node in FOQUS flowsheet. Open the Node Editor. Model type: None
1. Add the model parameters as "Input" variables within the Node Editor, Variables Tab, with their values
2. Add the model variables as "Output" variables within the Node Editor, Variables Tab
3. Enter the pyomo model script (with all imports mentioned) within the "Node Script" Tab, which involves the model parameters with the syntax of Foqus node input variables ie: x["param_name"]. After the "model solve" statement, within the Node Script, assign the model variable values to the node output variables as:
 _f["var1"] = m.var1.value_
Run the node.
You may want to try this. It might work. I shall send you the screenshots by tomorrow.

**Comment by TheHuangs** [comment]
@anujad95 , I have tested your method, it seems that variables in "input" table are treated as parameters in the pyomo model, thus these input variables cannot be optimized.  in the following example, I define a input variable xx with a bound of (0,1) and an output yy.
`import pyomo.environ as pe
from pyomo.environ import (ConcreteModel, SolverFactory, TransformationFactory,
                           Param,NonNegativeReals,PercentFraction,RangeSet,
                           PositiveReals,Set,PositiveIntegers,Constraint, 
                           maximize, Objective,Var,Expression,minimize,value,
                           Binary,Reals)
model = ConcreteModel()
model.y= Var(initialize =1,domain=Reals) 
model.Eq_1=Constraint(expr=model.y==x["xx"]**2)
model.Eq_obj =Objective(expr=model.y,sense=minimize)
solver = SolverFactory('gams',solver_io='shell')
results = solver.solve(model,tee=3, tmpdir='E:\Softwares\TEMPFILE',keepfiles=1,
solver="conopt",add_options=['option reslim=30;'],symbolic_solver_labels=1)
f["yy"]=model.y.value`
The problem is how to define input variable xx as a variable in pyomo model.

**Comment by anujad95** [comment]
Every "input variable" in the node editor of FOQUS takes a specific value when that node is run within the Flowsheet tab. Hence, in case of solving a pyomo model, these "input variables" would be "constant parameters" of the model, and cannot be treated as "decision variables". So, "xx" in your case, will have to be defined as another pyomo variable within the nodescript. I would like to ask your exact requirements for using pyomo models within FOQUS, so that we can try working on it.

**Comment by TheHuangs** [comment]
I think treating input as parameter have already resolved my problem.  Thank you.
