### ISSUE TITLE
ALAMO Stop button not working well

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#535]
In case we want to terminate the ALAMO modeling within FOQUS, it takes a very long time for the iterations to stop. Is there a way to improve this?

**Comment by ksbeattie** [comment]
This lag in time happens because the model is not going to notice that the stop button has been pressed until the currently executing model completes.  @anujad95, @eslickj and @boverhof will explore ideas on how to improve this.

-

**Comment by eslickj** [comment]
We had a few ideas on this.
1. Document current behavior better
2. As a work around and to better pin down what needs done, use task manager to kill Aspen and document what processes need to be killed.
3. Write a small script to kill Aspen (and other).
4. Try to have FOQUS send a rest kill command to consumer (should usually work but not %100)
5. Integrate method to directly kill Aspen (or similar).

**Comment by anujad95** [comment]
I have tried to use the methods killTurbineJobs() and stopAllConsumers() separately, followed by process.kill(), when the user presses the stop button. However, this does not seem to work. Any suggestions?

**Comment by ksbeattie** [comment]
@anujad95 will work with @eslickj on this.

**Comment by anujad95** [comment]
I had a discussion with @eslickj regarding this. It seems that the "stop" button within the surrogate tab is not hooked up properly within the base code. I shall look into this. In the meanwhile, users can kill aspen, and alamo process directly from the task manager to stop surrogate building. This is working fine.

**Comment by anujad95** [comment]
I made changes to the gui base code surrogateFrame.py, to connect the ALAMO stop button properly for terminating the runs. I tested it with an adaptive sampling example that takes a while to converge, and tried to press the stop button during the runs. Although it takes some time to actually stop the surrogate building, a user termination message is displayed in FOQUS.
