### ISSUE TITLE
UQ: I can't analyze my UQ ensemble

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#545]
- I have a Flowsheet.
- I generated 100 samples in UQ.
- I launched the samples, and it was successful.
- When I tried to analyze the samples, I got this error message:

![image](https://user-images.githubusercontent.com/30811140/62320173-9245e580-b46d-11e9-8850-6c77b2898a89.png)

**Comment by sotorrio1** [comment]
It looks like 'scipy.misc.comb' is deprecated in scipy 1.0.0 and they recommend to use 'scipy.special.comb' instead. Let me create a PR with the change and you can test it :)

**Comment by fsoepyan** [comment]
Thank you!

**Comment by fsoepyan** [comment]
This issue has been fixed with PR #547.

**Comment by fsoepyan** [comment]
- I managed to open the Analysis menu page in UQ.
- However, when I tried to do the "Uncertainty Analysis" for the "Ensemble Data", I got this error message:

![image](https://user-images.githubusercontent.com/30811140/62391307-722c2a00-b532-11e9-8260-5316bb535a9f.png)

**Comment by sotorrio1** [comment]
could you save the ensemble and send it to me?

**Comment by sotorrio1** [comment]
It looks like the SampleData method 'writeToPsuade' wasn't writing out the variables marked as 'Fixed'. That's why the two ensembles with all inputs as variables were working and not the one with two variables and two fixed inputs. I'll open a PR and you can test it.

**Comment by fsoepyan** [comment]
PR #548 fixed this issue. Thank you!

**Comment by anujad95** [comment]
For some reason this doesn't seem to work. I shall look into it.

**Comment by sotorrio1** [comment]
@anujad95 is this happening all the time or this is the case when you save your session and load it again?

**Comment by anujad95** [comment]
This happens when i save the session and load it again

**Comment by sotorrio1** [comment]
Then this is more an issue with saving the session than with UQ itself. UQ capabilities all work fine as far as I can tell.

**Comment by anujad95** [comment]
Yes, i went through the uq codes and they seem to be fine. I shall check the issue with saving sessions.

**Comment by ksbeattie** [comment]
@anujad95 and @sotorrio1 are working on this.

**Comment by sotorrio1** [comment]
Issue fixed with PR #654 already merged.
