### ISSUE TITLE
OUU: Problem running OUU for an Aspen Plus model

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#546]
- I tried running OUU for an Aspen Plus model.
- When I clicked "Run", I got this error message:

![image](https://user-images.githubusercontent.com/30811140/62383991-40f62e80-b51f-11e9-8dc2-75d5787c147a.png)

**Comment by jmorgan29** [comment]
I have been looking into the OUU module lately in preparation for a project and I got the same error when trying to run an example that I made up:

![OUU_error](https://user-images.githubusercontent.com/11306727/62385508-481f3b80-b523-11e9-9b12-93b6161a2287.png)



I thought it could have been a mistake in my problem setup, but it is a very simple example in which I am trying to minimize f(x) = a*x^2 + b*x + c , in which x is the decision variable and [a,b,c] are uncertain parameters with discrete values.

**Comment by fsoepyan** [comment]
- I am currently re-running my example problem, except this time, I changed "Choose Flowsheet Node" from "aspen" to "Full flowsheet".
- So far, it seems to be working.
- @jmorgan29: Can you please let me know if this also works for you?

**Comment by sotorrio1** [comment]
I can take a look at this. If using the full flowsheet works, do so in the meantime while I try to fix this issue. Thanks!

**Comment by jmorgan29** [comment]
@fsoepyan, I just ran my example with the 'Full flowsheet' option and got the result that I was expecting to see.

**Comment by sotorrio1** [comment]
It looks like when a single node is selected FOQUS is failing to pass the model information correctly to the UQ model. When the full flowsheet is selected this issue is not happening. I'm working on debugging it.

**Comment by sotorrio1** [comment]
PR #566 should take care of this.

**Comment by sotorrio1** [comment]
PR #568 merged and issue fixed. Closing this
