### ISSUE TITLE
Custom Python Objective Function Option

### ISSUE THREAD

**Issue by jmorgan29** [CCSI-Toolset/FOQUS#550]
In the optimization tab, there are two options for entering 'Objective/Constraints': 'Simple Python Expression' and 'Custom Python'. Upon selecting 'Custom Python' the user is directed to create a function called 'objfunc' and is provided an example of the correct syntax. Upon writing this function and running the optimization problem, the following error results, suggesting that the user defined function is not recognizable:

['Traceback (most recent call last):\n', '  File "c:\\users\\jmorgan\\desktop\\foqus-snobfit\\foqus_lib\\framework\\optimizer\\optimization.py", line 76, in run\n    self.optimize()\n', '  File "c:\\users\\jmorgan\\desktop\\foqus-snobfit\\foqus_lib\\framework\\optimizer\\Snobfit.py", line 271, in optimize\n    self.prob.prep(self) #get problem ready for solving\n', '  File "c:\\users\\jmorgan\\desktop\\foqus-snobfit\\foqus_lib\\framework\\optimizer\\problem.py", line 346, in prep\n    self.custObjFunc = objfunc\n', "NameError: name 'objfunc' is not defined\n"]

This issue has been confirmed for multiple examples. I have successfully used the 'Custom Python' option in previous projects, although not since the upgrade of FOQUS to Python 3.

**Comment by anujad95** [comment]
Yes, this issue is valid. I have reproduced the error on my machine. I am looking at the source code, and shall try to get it sorted out soon.

**Comment by anujad95** [comment]
The issue is resolved through PR # 555
