### ISSUE TITLE
Optimization: Objective function for performing OUU in the Optimization tab

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#551]
- I tried using the Optimization tab to perform OUU
- I typed in this objective functions:

![image](https://user-images.githubusercontent.com/30811140/62649671-4094d380-b923-11e9-8329-92a5bef32e30.png)

- The OUU failed, and this is the error message I got:

![image](https://user-images.githubusercontent.com/30811140/62649997-daf51700-b923-11e9-8371-6c9aeef230dd.png)

- However, when I changed the objective function to:

sum(ff.my_node.z for ff in f) / len(f)

- The OUU works

**Comment by ksbeattie** [comment]
@eslickj will take another look at this...

**Comment by fsoepyan** [comment]
- I tried to perform the tutorial for the Parameter Estimation, which involves optimization with "Sample" variables: https://foqus.readthedocs.io/en/latest/chapt_opt/tutorial/parameter_est.html
- When I typed the objective function like in the manual, I got errors, where the output in the optimization graph shows the "value for failure" number specified in the "Objective Function".
- This was the objective function I typed: sum([(f[i]['model']['y'] - x[i]['model']['ydata'])**2 for i in range(len(x))])

**Comment by fsoepyan** [comment]
- From my observation, modifying the objective function to the new notation (sum(ff.my_node.z for ff in f) / len(f)) works for the output variable.
- However, can anyone please let me know what the notation is for an input variable?

**Comment by ksbeattie** [comment]
@eslickj will take another look at this

**Comment by anujad95** [comment]
@fsoepyan i am trying the parameter estimation tutorial, and checking the correct notation of input variables for such problems. Your notation for output variables is working. fine.

**Comment by fsoepyan** [comment]
@anujad95: Can you please type in your notation for the objective function and constraints as a GitHub comment?

**Comment by anujad95** [comment]
Yes, once it works, i will type the syntax as a comment here.

**Comment by anujad95** [comment]
The correct syntax for the parameter estimation tutorial objective function is sum([(ff.model.y - xx.model.ydata)**2 for (ff,xx) in zip(f,x)]). It works fine now with the correct progression of objective function value.

**Comment by anujad95** [comment]
@fsoepyan did you get a chance to check if this is working for you?

**Comment by fsoepyan** [comment]
@anujad95: Thank you. I tested the code for the objective function and it works.

**Comment by ksbeattie** [comment]
@eslickj would like to take a look a this before closing it.

**Comment by ksbeattie** [comment]
@eslickj says he will get to this, but it may take a few weeks.
