### ISSUE TITLE
Record node error in a file during runs

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#552]
When running a simulation, it would be easier to diagnose a node error if the error is saved in a file for the user to see.

**Comment by ksbeattie** [comment]
Is there a console in the GUI somewhere that a (curious) user could use to view detailed activity for status, warning, errors, etc.?  This might be too much to tackle all at once, but I'm thinking of something like the activity window in some other apps.  That output could just automatically be written to a file for reference afterwards.

**Comment by anujad95** [comment]
Should we save the complete flowsheet error in another file, instead of individual node errors?

**Comment by anujad95** [comment]
Is this issue similar to # 232 ? In that case, we can combine them and provide the user an easily readable error message specific to a particular node, or the flowsheet in general, within the log viewer section in FOQUS.

**Comment by anujad95** [comment]
#232

**Comment by ksbeattie** [comment]
@fsoepyan feels these are distinct issues.

**Comment by ksbeattie** [comment]
Closing this as the errors should show up in the log file.
