### ISSUE TITLE
Manual: Change f["node"]["variable"] notation to f.node.variable notation in optimization

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#553]
For the optimization section in the user's manual, we should change the f["node"]["variable"] notation to the f.node.variable notation, as the latter notation is easier and shorter to type in.

**Comment by fsoepyan** [comment]
- PR #560 takes care of the notation for the optimization portion of the tutorial.
- But for the OUU done in Optimization tab part of the tutorial, should we also change the notation from f[i]["node"]["variable "] to the new one from #551?
- The one from #551 is: sum(ff.node.variable for ff in f) / len(f)

**Comment by ksbeattie** [comment]
@fsoepyan will follow up with @eslickj on this.

**Comment by fsoepyan** [comment]
- As I mentioned, this issue has been taken care of for the optimization portion.
- However, my question is for the case of running OUU in the Optimization tab: Do we want to stick to the old notation, or do we want to switch to the new notation from #551?
- I'm fine with either option.

**Comment by fsoepyan** [comment]
This issue is dependent on #551.
