### ISSUE TITLE
Resolution Problems with Fixed Height Boxes

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#567]
In a few places FOQUS uses fixed height widgets, and depending on screen resolution they may look too tall or too short to see all the text.  We should do something related to text height, or portion of the main window height.

**Comment by anujad95** [comment]
Is there a way we can adjust the main window, and boxes/widget height with the screen resolution in a better way? Is there a part of the source code that relates the GUI size to the screen resolution?

**Comment by eslickj** [comment]
There isn't any part of the code that does that now.  It's something we'll have to figure out.  There are better ways I'm sure., but nothing implemented now.

**Comment by anujad95** [comment]
Ok, i'll try to figure it out. Thanks
