### ISSUE TITLE
Documentation: The "Solvent Fit" chapter

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#569]
- We no longer have the "Basic Data" tab in FOQUS.
- Do we want to keep the "Solvent Fit" chapter in the user's manual, or should we delete this chapter?
- Note: Solvent Fit requires the use of the Basic Data tab.

**Comment by ksbeattie** [comment]
Unless we are going to restore and fix the basic data tab, we should take this out.  As painful as that might be...

**Comment by fsoepyan** [comment]
Because PR #582 has been merged, I will close this issue.
