### ISSUE TITLE
pytest-qt UI Testing?

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#573]
In addition to to the GUI scripting stuff we have for testing, I found this https://pytest-qt.readthedocs.io/en/latest/intro.html.  I've been starting to look at it for another project, but it could be useful for FOQUS.  Automated GUI testing still looks pretty sketchy, but hopefully we can do something good.

Related to PR #572

**Comment by anujad95** [comment]
How should we get started with this?

**Comment by ksbeattie** [comment]
@anujad95, try writing a very simple test, like just opening, then closing the app.

I think there is something like that, using an older qui testing framework under test/system_test/  We are currently running it in AppVeyor automatically with the commands:

    mkdir gui_testing
    python foqus.py -s test/system_test/ui_test_01.py --working_dir gui_testing

**Comment by boverhof** [comment]
I started exploring creating high level integration tests via pytest-qt, and it seems complex but hopefully doable.  I've done this kind of thing with Selenium and web interfaces. 

The idea being we could implement a test scenario for each `example` we have documented for FOQUS, then we would have some assurance that our published examples are working.

@ksbeattie do you think this is doable?

**Comment by ksbeattie** [comment]
I very much like this idea.  This sounds like a job for @lbianchi-lbl !
