### ISSUE TITLE
Optimization: Put the optimum solution as the last row in Flowsheet Table

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#579]
It would be convenient for the user if after running the optimization, the optimum solution appears as the last row in the NLOpt set in the Flowsheet table.

**Comment by anujad95** [comment]
A modification would be to display the actual trend of DFO solvers in the objective function plot window, instead of plotting the next lowest value, and report the iteration in which the optimum solution is obtained.

**Comment by ksbeattie** [comment]
This could be closed/solved by #593

**Comment by fsoepyan** [comment]
With #593 and #644 being closed and merged, can we close this issue?

**Comment by anujad95** [comment]
Yes, this issue can be closed
