### ISSUE TITLE
OUU: recourse variables remain constant

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#58]
When I run OUU, the recourse variables remain constant from start to finish. Furthermore, the value of each recourse variable is the average of its minimum and maximum values.

I have attached an Excel file that tabulates the OUU results for a problem John (@eslickj), Miguel (@MAZamarripa) and I are working on.

In the Excel file, the decision variables (Z1) are highlighted blue, the recourse variables (Z2) are highlighted green, the uncertain variables (Z4) are highlighted orange, and the two outputs of interest are highlighted yellow. I did the OUU with 10 samples generated using Latin hypercube sampling, assuming all uncertain variables have uniform distributions.

[OUU_Tab_11.03.2017.xlsx](https://github.com/CCSI-Toolset/foqus/files/1442411/OUU_Tab_11.03.2017.xlsx)

**Comment by ou3llnl** [comment]
@eslickj : Was there a change with recording the flowsheet table values?

**Comment by ou3llnl** [comment]
Oh, the values recording is actually issue #146

**Comment by fsoepyan** [comment]
Brenda (@ngbrenda), in a lot of our applications, when we need to do OUU on a process in Aspen , we handle recourse variables by doing the 2nd stage optimization in Aspen.

I guess we can close this issue?
