### ISSUE TITLE
Vector variables: Can FOQUS still handle vector type variables?

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#580]
- I think in the past, FOQUS can handle vector type variables in the Flowsheet?
- Does FOQUS still have this capability?

**Comment by ksbeattie** [comment]
Looks like vector vars were remove way back in #85

**Comment by ksbeattie** [comment]
@omellben is asking what it will take to return this functionality...

**Comment by anujad95** [comment]
I have started discussing this with @eslickj, and will go through the existing SimSinter documentation first to check whether this functionality is already available, and needs to be re-introduced in the GUI.

**Comment by ksbeattie** [comment]
@anujad95 has a plan on this after talking to @eslickj about it, needs to vet that plan with other developers before implementing it.  Will arrange a meeting on that plan in the next week or 2.

**Comment by anujad95** [comment]
I have continued working on this with @eslickj . Currently vector variables can be created in the flowsheet node, and python models containing vectors can be solved in the nodescript. However, we need to work on some extended base code modifications for ensuring that it does not affect other FOQUS modules.

**Comment by anujad95** [comment]
PR #876 takes care of this issue for Python and Aspen models.
