### ISSUE TITLE
Heat Integration: GAMS file

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#581]
This is a dumb question, but when we download FOQUS from GitHub, does the GAMS code for the heat integration also get downloaded automatically?

**Comment by eslickj** [comment]
Yes, but you still need to install GAMS.  The GAMS code is included as data files and gets copied automatically to where you need it when you run heat integration.

**Comment by fsoepyan** [comment]
@eslickj: Thank you, that answers my question. As long as the user doesn't need to type in a set of codes in GAMS, then this is fine.
