### ISSUE TITLE
Additional Optimization Plot

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#593]
As an enhancement, an additional plot of objective value v/s iteration can be included in FOQUS, that displays the actual objective value at iterations after regular time intervals, instead of plotting just the "best so far" objective values. This would help the user understand the actual progress and behavior of the optimization solver.

**Comment by anujad95** [comment]
This will also be followed by displaying the iteration number corresponding to the optimal solution, in the message window, after the solver converges, so that the user can access it accordingly from the flowsheet result table. 
This issue is a modification of #579

**Comment by ksbeattie** [comment]
fixed in #644
