### ISSUE TITLE
Fix broken references in sphinx docs

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#605]
As started in PR #595, there are several broken references in the docs that need to be cleaned up.

Specifically, the references to the `ap:psuadefiles` and other references mentioned in more detail [here](https://github.com/CCSI-Toolset/FOQUS/pull/595#issuecomment-540383329)

**Comment by sotorrio1** [comment]
Related to issue #720 and possible fix with PR #721

**Comment by ksbeattie** [comment]
Closed with #720
