### ISSUE TITLE
Fix unit_test test

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#607]
After PR #606, @eslickj, could you now get these to work with pytest?  They currently aren't getting run by pytest because the .py files aren't named correctly.  If you rename them to be `_test.py` rather than `Test.py` they should then get picked up and run.  But, of course the tests are failing, which is beyond my understanding to properly fix them.

**Comment by anujad95** [comment]
Is this issue resolved?

**Comment by eslickj** [comment]
Not that I know of.  At least I didn't do anything to resolve it.

**Comment by ksbeattie** [comment]
The files I'm talking about here are in `foqus_lib/unit_test/`

**Comment by ksbeattie** [comment]
Closed by #647
