### ISSUE TITLE
Upgrade PyQt5 version to 5.13?

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#608]
During automated tests in AppVeyor, where `python=3` version was specified, I've discovered that `python 3.8` is out now, which this issue isn't about per se, but it revealed that `PyQt5 5.9` is **not** supported in `python 3.8` whereas PyQt5 versions: `5.10.1, 5.11.2, 5.11.3, 5.12, 5.12.1, 5.12.2, 5.12.3, 5.13.0, 5.13.1` are.

The safe workaround for now is to specify python=3.7 but this raises the question of us moving to a newer more supported version of PyQt5.

I did a quick and very simple check of trying PyQt5 version up to 5.13 and it worked.  This was a very simple test of just starting the gui and another of running the basic gui test:
```
mkdir gui_testing
python foqus.py -s test/system_test/ui_test_01.py --working_dir gui_testing
```

So, do we want to move to PyQt5 5.13?

btw, this also appears to remove the need to include `sip` in the requirement.txt file.  Perhaps there are other packages in there that could also be removed?

**Comment by sotorrio1** [comment]
It seems to be the right move

**Comment by ksbeattie** [comment]
I'll look into changing the requirements.txt file, though we need to figure out how best to help those who have been working in their anaconda base environment and how to reset it.  Perhaps this is how to do it: https://stackoverflow.com/questions/41914139/how-to-reset-anaconda-root-environment

**Comment by ksbeattie** [comment]
After reviewing that link, I think it's best to just not bother trying to reset the base env (short of un/reinstalling all of Anaconda) and just start using new conda envs.

**Comment by ksbeattie** [comment]
See #616 for fixing the python version to use, for other reasons too.
