### ISSUE TITLE
Heat Integration: Automatic Identication of Heat Sources and Sinks

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#63]
We would like for FOQUS to be able to identify heat sources and sinks without using variables tags. Unfortunately, an automatic search of heat sources and sinks may be difficult. We may be able to select the heat integration variables during the preparation of the JSON file in SimSinter. This process could be done easily for Aspen Plus, but may be difficult for Aspen Custom Modeler.

**Comment by ksbeattie** [comment]
Closing this given the low priority and lack of likelihood anyone wants it in the near future.
