### ISSUE TITLE
Blue Screen of Death

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#630]
# Description
When testing on AWS with Windows 2008 server I have been getting unexpected shutdowns after a couple hours.  Think may have something to do with CPU driver.  The example below job 125 finished successfully, 126 was running and suddenly the computer reboots.  

I've experienced blue screens years ago but used to get a warning about CPU overheating.

# Detail
FOQUS_Worker2008.2 | i-01b1b406ab32a43d9 | m5.large | us-east-1a

# Bugcheck unexpected reboot 10/13/2019 12:15AM GMT
<img width="1335" alt="Screen Shot 2019-11-12 at 9 00 45 PM" src="https://user-images.githubusercontent.com/738295/68735533-e004da80-0592-11ea-8c51-6f7d31b7705f.png">

<img width="770" alt="Screen Shot 2019-11-12 at 9 02 21 PM" src="https://user-images.githubusercontent.com/738295/68735628-29edc080-0593-11ea-8a2c-25ee38113ff5.png">

# CPU Graph

<img width="915" alt="Screen Shot 2019-11-12 at 9 28 12 PM" src="https://user-images.githubusercontent.com/738295/68735736-66b9b780-0593-11ea-8df5-9ffd31e084e4.png">

# Refs
https://forums.aws.amazon.com/thread.jspa?threadID=151853

**Comment by boverhof** [comment]
# Windows 2016 Server

- Ran FOQUS Local Optimization twice, results were ~identical.  Both runs took about 7 hours and the CPU characteristics are captured in screen shot.
- No blue screen of death
- https://github.com/CCSI-Toolset/FOQUS_Sessions/blob/master/examples/test_files/OUU_Remote_Turbine_BFB/BFB_OUU_08_20_2019-Windows2016-Local-5.foqus

![Uploading Screen Shot 2019-11-15 at 10.46.53 AM.png…]()

**Comment by ksbeattie** [comment]
@boverhof says he's trying out Window 2016 and will close this if it works there.
