### ISSUE TITLE
Node with Turbine Model Fails Only on First Attempt

### ISSUE THREAD

**Issue by jmorgan29** [CCSI-Toolset/FOQUS#634]
This is an ongoing issue that has started happening recently. Although it does not have a major affect on my ability to work with FOQUS/Turbine, I wanted to draw attention to it as it may confuse and/or frustrate a new user of FOQUS. 

I uploaded a new model containing an Aspen Plus file to Turbine, created a node for the model, and run the node. The node fails with Code 7 (Turbine simulation error).  However, after making no changes, I click the run button once again and the simulation runs successfully. Basically, the model only fails on the first run attempt. I have attached an excerpt from the FOQUS log that shows how to model is ran twice with the same set of input values, while failing on the first run and succeeding on the second.

[Excerpt from FOQUS Log.txt](https://github.com/CCSI-Toolset/FOQUS/files/3860805/Excerpt.from.FOQUS.Log.txt)

**Comment by ksbeattie** [comment]
This looks similar (if not a dup) to: https://github.com/CCSI-Toolset/turb_sci_gate/issues/18

**Comment by boverhof** [comment]
This is fixed with new release of TurbineLite
