### ISSUE TITLE
Surrogate model validation not working in UQ

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#642]
After a surrogate model is generated from a particular UQ Ensemble using ALAMO, a file named "alamo_surrogate_uq" is generated, that is meant for "response surface validation" Further, this python file, containing the surrogate model, can be loaded into the validation section within the "analyze" tab of UQ Ensemble, to obtain the actual vs predicted validation plot. However, this is not working due to an error in the base code.

![image](https://user-images.githubusercontent.com/47067166/69501827-a73ffc00-0ed6-11ea-9fd0-f52008a0b002.png)

**Comment by sotorrio1** [comment]
PR #643 already merged.
