### ISSUE TITLE
BFB Optimization Testing

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#650]
# Description
Updates to OUU flowsheet to deal with issue #639 have been made by @fsoepyan.   Now we need to test this flowsheet on different platforms and report and analyze the results, and fix problems like no "AspenProperties" available on AspenTech v10.

# Flowsheet to test
https://github.com/fsoepyan/FOQUS/tree/new-bfb-ouu/examples/test_files/OUU_Remote_Turbine_BFB

**Comment by boverhof** [comment]
# Description
## Platform
- Windows 2016 server
- Amazon AWS m5.large
- AspenTech v10
- AWS SLM Server

## Results
- https://github.com/CCSI-Toolset/FOQUS_Sessions/blob/master/examples/test_files/OUU_Remote_Turbine_BFB/BFB_OUU_11_27_2019-Windows2016-Local-5.1.foqus

<img width="1144" alt="Screen Shot 2019-12-03 at 9 46 58 AM" src="https://user-images.githubusercontent.com/738295/70077335-71c19f80-15b5-11ea-9ef9-0accb21196db.png">

**Comment by boverhof** [comment]
@anujad95 can you look at the above session file and accompanying log file and evaluate whether:
- the Optimization ran correctly or had problems?
- The AWS run took about twice as long as Byron's run.  Why?

**Comment by anujad95** [comment]
Yes, i will look at the optimization results and check if there are any issues first. Currently we don't have access to AWS VM from NETL. It would be helpful if you could please try to give us access. Thanks.

**Comment by anujad95** [comment]
I have tried to run the BFB optimization problem on the following platform:

Windows 10 Pro 2019
AspenTech v10
Dudley SLM Server (Commuted License)

The optimization runs till a point when the Aspen Properties License Error shows up. I interrupted the runs and took a screenshot of the solver progress. In terms of solution, it seems to be fine, and matches with the previous screenshot uploads. 

![BFB-OUU-Result](https://user-images.githubusercontent.com/47067166/71287985-c5631580-2337-11ea-81c3-8872a5cf0095.png)

**Comment by boverhof** [comment]
Installed Patch from AspenTech on AWS Windows 2016 m5.large instance and AspenProperties problem didn't occur.

Ran successfully optimization 
- Time elapsed 12:42:00 hours
- Results 
![Uploading Screen Shot 2019-12-21 at 12.54.31 PM.png…]()

**Comment by boverhof** [comment]
@anujad95  Patch for reference
 https://esupport.aspentech.com/apex/S_SoftwareDeliveryDetail?id=a0e4P00000GSp0yQAD
