### ISSUE TITLE
Documentation for SDoE with updates for new capability

### ISSUE THREAD

**Issue by candcook** [CCSI-Toolset/FOQUS#653]
Revise the documentation to reflect new version of SDoE with NUSF capability

**Comment by sotorrio1** [comment]
@candcook is there a difference between this issue and #651 ?

**Comment by candcook** [comment]
No these are the same. Sorry for any confusion.

Thanks,
Christine

**Comment by sotorrio1** [comment]
PR #655 takes care of this
