### ISSUE TITLE
FOQUS pypi package too large

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#660]
I thought I'd try to see if I could create a pypi package for FOQUS.  It seems I can, but I can't then upload it because it is over their 60MB is size limit (it's 78MB).

I could ask for an increase (they'll want an explanation), but before that I thought I see if there is a way that we could get under the 60MB file size limit.  

I know that there are several duplicate large files found in #168 but I gave up on trying to address that.  Any thoughts on if we could re-open that idea?  I think we could then get under the 60MB size limit.

**Comment by anujad95** [comment]
I shall look into the duplicate files and we can try to get it under the 60MB size limit.

**Comment by eslickj** [comment]
I think in the long run the solution is to move examples out to a separate repo.  We have some big example files and installing them with pip may not make a lot of sense.  I think we had a similar problem in IDAES (although not size related) which led to the creation of an examples repo.

**Comment by ksbeattie** [comment]
Closing this now that PR #700 is merged, though I'm sure we haven't heard the end of this problem.  Ideally moving the example out into their own repo will be the final fix.
