### ISSUE TITLE
FOQUS Aspen Version Declaration

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#670]
# Description
Need to declare which versions of AspenTech we are supporting or recommending.  This should happen somewhere in our documentation. 

# Proposal
I think FOQUS works with AspenTech v8.4 to AspenTech v10.  We should recommend AspenTech v10, which also requires an update patch from Aspen to operate correctly with any simulation a that uses AspenProperties.  See reference below for more information concerning the patch.

# References
#650

**Comment by ksbeattie** [comment]
@fsoepyan will take a pass at adding this into into the SimSinter section of the documentation.

**Comment by fsoepyan** [comment]
PR #691 is made to address this issue.

**Comment by ksbeattie** [comment]
@boverhof can you close this if you feel PR #691 addressed this sufficiently?
