### ISSUE TITLE
Warning message while opening FOQUS

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#672]
I am getting a warning message while opening FOQUS due to some internal updates:

C:\Users\deshpana\AppData\Local\Continuum\anaconda3\envs\foqus\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)

**Comment by ksbeattie** [comment]
I chased this down to a problem in mlrose.  I've opened a PR in that project, which I believe will fix it: https://github.com/gkhayes/mlrose/pull/50

**Comment by ksbeattie** [comment]
@sotorrio1 will look into the possibility of replacing mlrose with mlrose-hiive.
