### ISSUE TITLE
Problem after creating new environment

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#679]
- I created a new environment in Anaconda called foqus_test
- I used the 2019 December release version of FOQUS
- I did pip install -r requirements.txt
- Then, I did python setup.py develop
- I managed to open FOQUS successfully
- However, when I tried to open a file, I got this error:

![image](https://user-images.githubusercontent.com/30811140/73482989-b6c34180-436c-11ea-8520-ddb2c397c4f0.png)

**Comment by mpenkuhn** [comment]
It seems to be related with the pandas 1.0.0 release of January 30, 2020 which introduced some [incompatible API changes](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html#backwards-incompatible-api-changes) in the pandas DataFrame. 
However, I was able to get back to working state by downgrading to pandas 0.25.3. Probably it should be added as a version constraint to the requirements file.

**Comment by fsoepyan** [comment]
This issue is resolved with PR #681.

**Comment by ksbeattie** [comment]
@mpenkuhn, thank you for the pointer.  We've created a new 3.4.1 patch release to address this issue.
