### ISSUE TITLE
Keyboard Friendliness

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#68]
We would like to make FOQUS more keyboard-friendly, because it will help in automated testing.

**Comment by CSRussell2319** [comment]
Is automated testing the only reason for this change? If so I think we can close this as the automated tests run fine without keyboard support.

**Comment by fsoepyan** [comment]
- @CSRussell2319, the answer to your question is no.
- The reason we'd like to improve the keyboard friendliness is also for the users of FOQUS.
- For example, if possible, we would like to be able to switch from one tab to another tab by using the keyboard; or we would like to be able to select multiple cells from the tables in the Flowsheet Node Editor.

**Comment by fsoepyan** [comment]
- With or without the keyboard friendliness, FOQUS runs fine.
- Would anyone object if we close this issue? (Since we are close to closing this issue, I will move this issue to a "High" priority in the project board.)

**Comment by anujad95** [comment]
I think we can close this issue.
