### ISSUE TITLE
UQ Analyze RS Validation 

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#683]
The parity plot for a user provided surrogate model, in the RS validation section of UQ, does not work properly if the number of surrogate model input and output variables don't match the simulation variables.

**Comment by ksbeattie** [comment]
@anujad95 is working on this.

**Comment by sotorrio1** [comment]
@anujad95 PR was approved, isn't this one fixed?

**Comment by anujad95** [comment]
Yes this issue is fixed. It can be closed now.
