### ISSUE TITLE
Flowsheet: Node Inputs and Outputs Dropdown Menus

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#69]
For the node inputs and outputs, we would like to modify the rows such that items in drop-down menus (such as the number type) are not changing whenever the cursor is above the menu and the mouse wheel is turned. One possible solution is to have a check box that locks the variables, just like the one in the edge editor.

**Comment by fsoepyan** [comment]
- To resolve this issue, when the user is looking at the node inputs and outputs in Node Editor, all the user needs to remember is not to scroll using the scroll wheel when the mouse cursor is above the variable type (float, int, str).
- Using the "Page Up" and "Page Down" button in the keyboard is another solution.
- Would anyone object if we close this issue? (Because we are close to closing this issue, I will move this issue to "High" priority in the project board.)

**Comment by anujad95** [comment]
Yes, this is a relevant issue, and the solution to this mentioned by @fsoepyan makes sense. We can close this issue if everyone agrees.
