### ISSUE TITLE
Surrogates: plot RS validation after training

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#70]
We would like to improve the presentation of the results from ALAMO by having FOQUS create a parity plot of the original y-value vs. the predicted y-value after the ALAMO model is generated.

**Comment by ksbeattie** [comment]
@eslickj is going to take a whack at this, if it's as easy as it looks...

**Comment by eslickj** [comment]
Won't fix.  Don't have time to add anaysis tools in the surrogates section.
