### ISSUE TITLE
SDOE plotting not working

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#706]
Found out that SDOE plotting wasn't working properly. Issue has to do with the wrong name for the facecolor argument.

**Comment by atowfiq** [comment]
Tested SDOE plotting. USF (uniform space filling) seems to be working fine for everything including the plotting. However, the NUSF (non uniform space filling) failed to perform while "Test SDOE" clicked. Both the screen shots and error messages attached below. Plotting for NUSF couldn't be tested. Failed before reaching there. 

![screenshot_SDOE_NUSF](https://user-images.githubusercontent.com/9701325/80264940-1a4ec980-8653-11ea-8a24-38960d2c5992.png)
![error_SDOE_NUSF](https://user-images.githubusercontent.com/9701325/80264949-1de25080-8653-11ea-9ee9-4b859e9e799d.png)

**Comment by sotorrio1** [comment]
@atowfiq I might have found an issue with the **'Include?'** column in NUSF. Could you try running this same example with everything the same but also checking the boxes for **'Steam Flow'** and **'CO2 Captured'**? At least that way you can check the plotting also works for NUSF and I'll open a separate issue for the include feature. Thanks!
