### ISSUE TITLE
'Load All Samples from a Single File' Option in Uncertainty Tab

### ISSUE THREAD

**Issue by jmorgan29** [CCSI-Toolset/FOQUS#708]
When running an uncertainty ensemble in FOQUS, there is an option for loading the input variable values from an external file. As explained in the documentation, a csv file in the following format should be used:

![csv_format](https://user-images.githubusercontent.com/11306727/79129050-85a2bc80-7d72-11ea-8831-3edd3ce5a132.jpg)

In this example, the flowsheet has a node called '1' with input variables 'A_tot_flow', 'B_X_CO2', and 'C_T' and the user has to specify the names of the node and variable in the csv file.

However, in previous releases of FOQUS (as recently as 3.4.1), the same ensemble could be uploaded using a txt file in PSUADE format:

![txt_format](https://user-images.githubusercontent.com/11306727/79130016-44131100-7d74-11ea-924d-7a7b8943c520.jpg)

This format can be more convenient to use, particularly for models with a large number of input variables, since the user only needs to place the variables in the correct order rather than label them by name.

When attempting to upload the same file using FOQUS 3.5, the following error results:

"File does not have the correct format! Please consult the users manual about the format."

Although this functionality works as stated in the documentation (using the csv file of specified format), I wanted to create this issue to determine whether the capability of using the PSUADE format was removed or unintentionally broken.

**Comment by anujad95** [comment]
I'll look into this and try to fix it.
