### ISSUE TITLE
Autosave FOQUS Sessions

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#713]
It would be helpful to have this feature, to ensure that if FOQUS shuts down unexpectedly, UQ ensemble simulations, or optimization, surrogate building runs get saved automatically. It will be convenient and time saving for the users.

**Comment by eslickj** [comment]
We have this at least partly implemented in some places like optimization.  I think I had a feature where UQ would be able to pick up where it left off (at least on the cloud).  We need to take a closer look at what's there and how best to complete this.  For UQ it may be best to run in "remote" mode even locally.  That would potentially activate the feature to allow you to pick up where you left off.

**Comment by ksbeattie** [comment]
Doesn't look like this is going to be done anytime soon, so closing for now.
