### ISSUE TITLE
SDoE: issue with the 'Include' capability in NUSF

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#714]
There is an issue when trying to generate a NUSF design and the include capability.

**Comment by atowfiq** [comment]
The plotting is working for both USF and NUSF. However NUSF has separate issue (nothing to do with plotting) which will be addressed as a different issue.

**Comment by ksbeattie** [comment]
@ngbrenda is working on this.

**Comment by ksbeattie** [comment]
@ngbrenda, will get to it!

**Comment by ngbrenda** [comment]
@ksbeattie I rewrote the usf and nusf code using pandas operations, so it should fix this and other column-related bugs. 

@sotorrio1: I committed to your branch. If you may test and merge, that'd be great. Thanks.

**Comment by ksbeattie** [comment]
@ngbrenda & @sotorrio1, any ETA on that PR?

**Comment by sotorrio1** [comment]
hey @ksbeattie, finishing some testing and will create the PR ASAP. Soooorry!

**Comment by ksbeattie** [comment]
Will be fixed in #756
