### ISSUE TITLE
FOQUS Workers instance-id

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#719]
# Description
FOQUS Workers publish keepalives to SNS periodically.  Only at startup time does a Worker ask for its `instance-id`, and occasionally this AWS Web service isn't responsive.  Not having the instance-id doesn't break anything but it makes problem solving and tracking more difficult.

# TODO
Add instance-id checks in FOQUS Worker.  If empty string, pull from AWS Web service again, add to SNS publish keep alive messages and results should show up in AWS DynamoDB.

# Output and Details
```
(py2) joshuas-mbp:workspace.ccsi2 boverhof$ aws_foqus_cloud.sh status
"byron","running",
"byron","running",
"byron","running",
"byron","running","i-07ef3c2979535a63e"
"byron","running","i-0849e211a72664281"
"byron","terminate",
"byron","terminate",
"byron","terminate",
"byron","terminate",
"byron","terminate",
"byron","terminate",
"byron","terminate",
"byron","terminate",
"byron","terminate",
"byron","terminate",
QUEUE: https://queue.amazonaws.com/387057575688/FOQUS-Gateway-FOQUSJobSubmitQueue-G8M3IVDEJM3N
LENGTH: 9
(py2) joshuas-mbp:workspace.ccsi2 boverhof$ aws_foqus_cloud.sh consumer_jobs
"i-07ef3c2979535a63e","12e5552b-f095-4a6b-b9bc-99b5d5a792b7","byron","running"
"i-0849e211a72664281","6e1271d2-5072-429c-9dd5-b9bd758fc98e","byron","running"
,"2aa0c0a1-4500-47ae-9ccb-4a5301da70aa","byron","running"
,"4168df8b-fb76-41b6-aae4-12a1c7624119","byron","running"
,"71a085d9-ed05-46d2-a970-f634b805013e","byron","running"
(py2) joshuas-mbp:workspace.ccsi2 boverhof$
```

**Comment by ksbeattie** [comment]
Should get to this with the AMI/Notification work.

**Comment by boverhof** [comment]
Fixed.
- If FOQUS Service can't discover the metadata an exception is thrown and the Windows service will exit.
- the Windows Service is configured to restart on unexpected error.
