### ISSUE TITLE
File Format Documentation Missing

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#720]
The file format documentation referenced in different sections of the UQ chapter is being missing for a while. It would be good to have it back in the online documentation as a reference for users to know what is the right format in each situation.

**Comment by ksbeattie** [comment]
Is this related to #605?  The `ap:psuadefiles` parts?

**Comment by sotorrio1** [comment]
oh my god, you're right! Totally forgot about that issue. Yeah, with the addition of this section and a few edits I've made, I think I fixed all the broken references you mentioned in that issue
