### ISSUE TITLE
FOQUS Cloud Aspen v8.4

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#727]
# Description
Request for Aspen v8.4 support on the FOQUS Cloud.  Will require creating a new AMI and a means of selecting v8.4 or v10 ( currently the only available version ).

**Comment by boverhof** [comment]
### Base AMI
- Windows_Server-2016-English-Full-Base-2020.05.13 (ami-0cc5ea3dde5301489)

### Anaconda 3
- Anaconda3-2020.02-Windows-x86_64

**Comment by fsoepyan** [comment]
I don't think this capability is needed. Therefore, I will close the issue.
