### ISSUE TITLE
unable to generate sample using LATIN HYPERCUBE

### ISSUE THREAD

**Issue by ishanf91** [CCSI-Toolset/FOQUS#733]
I created a node in the flowsheet tab, provided input parameters and respective details.
Then to create the candidate set I followed the following steps:
Uncertainty tab -> Add new -> use flowsheet -> sampling scheme -> select latin hypercube -> generate samples.

it is supposed to generate the number of samples requested but I do not see any samples generated..

I have installed PSUADE and location of the files is correct as checked from the settings tab.

**Comment by anujad95** [comment]
@ishanf91 could you please share screenshots of how you have set up the problem?

**Comment by ishanf91** [comment]
Please see the attached ppt.

**Comment by sotorrio1** [comment]
@anujad95 isn't this fixed? If so, we should close the issue.

**Comment by anujad95** [comment]
Yes this issue can be closed.
