### ISSUE TITLE
MATLAB

### ISSUE THREAD

**Issue by MDCA960418** [CCSI-Toolset/FOQUS#734]
Hello,

Can a MATLAB model be incorporated into SimSinter? 

Thank you.

**Comment by anujad95** [comment]
MATLAB files cannot be directly loaded in simsinter. However, the results from the model can be transferred to an excel file, which can be loaded in simsinter, and then be used to interface with other models in FOQUS. It would be helpful to get some basic details about the problem that needs to be solved.

**Comment by MDCA960418** [comment]
That helps, thank you!
