### ISSUE TITLE
Data Filtering

### ISSUE THREAD

**Issue by MDCA960418** [CCSI-Toolset/FOQUS#754]
Hello,

I am unable to filter my output data given the following expression, which should be valid as per the manual

![image](https://user-images.githubusercontent.com/66323673/85313583-42597e00-b486-11ea-87c9-572ac1164503.png)

Thanks.

**Comment by anujad95** [comment]
Could you please share details of how you implemented the filter? Some screenshots would help.

**Comment by anujad95** [comment]
When you click on Add/Edit Filters, drag output.graph.error from the "columns" and drop it in the filter expression space. Check if this works.

**Comment by MDCA960418** [comment]
@anujad95 That works, thank you. Also, what would be the appropriate syntax for filtering between a range of values? I'm using the following expressions, but they are not accepted by FOQUS.

![image](https://user-images.githubusercontent.com/66323673/85334839-ea347300-b4a9-11ea-9bd8-c30ac7cb4a76.png)
![image](https://user-images.githubusercontent.com/66323673/85334916-12bc6d00-b4aa-11ea-99f2-29bb0b541f87.png)

**Comment by anujad95** [comment]
output.graph.error either takes the value 0 (successful simulation) or 1 (failed simulation) depending on whether or not the simulation associated with the input values has converged. So, a range will not be applicable here.
However, for any other non-binary output variable, say 'y', the following syntax works to implement a range based filter:
np.logical_and(c("output.test.y")>=10,c("output.test.y")<=50)

**Comment by MDCA960418** [comment]
Awesome! Thanks.
