### ISSUE TITLE
NUSF slowed down

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#766]
After the latest re-factoring NUSF handles more Pandas data frames rather than numpy arrays; and that's slowing things down.

**Comment by sotorrio1** [comment]
Already ran a profiler through the code to figure out what's slowing things down and what can be improved to speed things up.

**Comment by ksbeattie** [comment]
This has been temporarily fixed, so we'll keep this issue, but push it to the Dec release.

@sotorrio1 has ideas on a better "hybrid" approach using a subset of csv columns provided, or a mix between using numpy vs pandas.
