### ISSUE TITLE
Turbine Upload Error

### ISSUE THREAD

**Issue by MDCA960418** [CCSI-Toolset/FOQUS#768]
When uploading SinSinter file into Turbine it gives me the following error

![image](https://user-images.githubusercontent.com/66323673/87322436-69422780-c4fb-11ea-8792-f2b7fba6d1e9.png)

**Comment by ksbeattie** [comment]
@MDCA960418 can you give us some more details about your env?  Like what version of turbine is installed?

@boverhof, could you follow up with him on this?

**Comment by MDCA960418** [comment]
I was trying to upload an AspenPlus file into Turbine. The turbine version is the latest one (released on December 2019).

I think the issue was that I was updating my AspenPlus File while I still had the same file open in FOQUS and then trying to re-save it in SinSimter. I even tried uploading different AspenPlus files and the same error would show up, I fixed it by deleting the turbine file that corresponded to the original file that was giving the error. 

I basically followed the same troubleshooting procedure as given in issue #381 by @fsoepyan in the comment section. However, I think it will be worth documenting a procedure for whenever the user is trying to update the Aspen Model and what should be the chronological order of actions to ensure the model works as intended in FOQUS. 

Thanks!
