### ISSUE TITLE
FOQUS Cloud simultaneous user improvements

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#770]
# Description
In the FOQUS Cloud all flowsheet run requests go on a single queue that is FIFO.  For multiple simultaneous users this is non-optimal.  Also the Aspen Engine on a FOQUS Worker is often reused between runs allowing the jobs to run much quicker.  If the simulation is changed the FOQUS Worker must re-initialize, thus two users with different simulations could force the FOQUS Worker to reload a simulation over and over again while serving their requests.

# Proposed 
Investigate solutions to utilize per user job queues, or possibly fan-out AWS SNS pub sub.  Each user should have dedicated EC2/FOQUS Workers.

The `UserData` for each EC2 instance could be used to mark them for a particular user or even specify the job queue.  Possibly each queue generated programmatically using a `username` suffix, and a programmatically generated Autoscaling group..

# Detail:  New Deployment 

Currently all flowsheet requests (ie. jobs ) are pushed onto a single queue.  All FOQUS workers pop jobs off that queue.  

A better solution would be for each user to have their own queue and dedicated FOQUS workers.  Mostly the FOQUS cloud has been engineered to accommodate this change, however, there are a few deployment changes that need to be worked out.  

I think the FOQUS Workers are already capable of handling this.  When they start up they are configured to a `queue` by using the “instance data”, which is provided by the cloud init stack to each VM that starts up.

The cloud side is where most of the changes are required.  When jobs are submitted the AWS Lambda `post-session-start` function is invoked by a HTTP POST to the session/uuid resource.  This causes all the jobs to be published as `submitted` to an AWS SNS ( pub sub ) Topic.  Currently only one job queue is listening to this topic.  First, this would need to change and a queue should be created for every user, each listens to this topic for requests that specify their `username`.  This is a fan out pattern.

Each user job queue would need to have an associated Autoscaling configuring.  This is where the magic of `instance` data is specified.  I think that’s all that needs to be done, and AFAIK at this moment it’s all deployment configuration stuff and very little needs to change in the FOQUS code base.

In order to pursue this I will have to make an entirely new deployment, with all new resources.  I don’t want to touch the existing FOQUS cloud.  I’m guessing I’ll need a week (ie. 40 hours) of time to do this.  I currently work 4 days a week on this project so I’m thinking it will take me September and October to deploy.

**Comment by ksbeattie** [comment]
This will happen after #800

**Comment by boverhof** [comment]
This was done in 2023.
