### ISSUE TITLE
Addressing usability study findings

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#772]
After Sarah completes her usability study for SDoE, we will need to address any changes she recommends/suggests according to her findings.

**Comment by ksbeattie** [comment]
Sarah says she should have some design suggestions for us in mid-Aug

**Comment by ksbeattie** [comment]
@sotorrio1 says he's in the process of getting changes from the LANL team to address the simpler/light-weight/easier/quick solutions for this Sept release.

**Comment by ksbeattie** [comment]
PR #823 above addresses the "quick" solutions.  This issue will stay to track any of the more involved GUI improvements.
