### ISSUE TITLE
pylint errors in: foqus_lib/framework/ouu/testOUU.py

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#779]
A couple of errors found by pylint: 

```
************* Module foqus_lib.framework.ouu.testOUU
foqus_lib/framework/ouu/testOUU.py:33:0: E1128: Assigning result of a function call, where the function returns None (assignment-from-none)
foqus_lib/framework/ouu/testOUU.py:33:10: E1120: No value for argument 'outputsAsDerivative' in unbound method call (no-value-for-parameter)
foqus_lib/framework/ouu/testOUU.py:33:10: E1120: No value for argument 'xtable' in unbound method call (no-value-for-parameter)
foqus_lib/framework/ouu/testOUU.py:33:10: E1120: No value for argument 'phi' in unbound method call (no-value-for-parameter)
```

This file should also be renamed to `test_OUU.py` so that pytest will find it.  Of course, the tests inside will need to succeed - which hopefully can be done at the same time as making pylint happy.  To run pytest on it (from the top dir):

    pytest foqus_lib/framework/ouu/

Part of #600

**Comment by sotorrio1** [comment]
This file is actually pretty outdated (ouu function has change quite a bit since). I'm going to delete this file and hopefully in the near future use it as a base for OUU testing.
