### ISSUE TITLE
FOQUS Cloud MEA Aspen Test

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#782]
# Description
Running the current [MEA](https://github.com/CCSI-Toolset/MEA_ssm/releases) on the FOQUS Cloud results in an error.

# Diagnosis
 The AspenPlus run fails because the DLL is corrupt.  Either the wrong file is being specified, or something in the upload process is corrupting it.

# References
Get DLL from the release page:
- https://github.com/CCSI-Toolset/MEA_ssm/releases

**Comment by anujad95** [comment]
Josh uploaded the DLL file to the simulation directory on the AWS Cloud since all workers (VM’s) grab the simulation from there. The simulation completes successfully now.
