### ISSUE TITLE
Remote turbine robustness testing & documentation

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#783]
An extension of the amazon cloud turbine setup documentation could be useful for the users, in terms of knowing what is expected while running simulation, UQ ensembles, and optimization on cloud. Mainly, some remarks can be made on the overhead time for the VM's to start, and possible time saving for all the simulation/optimization runs as compared to local turbine. 

This could also possibly serve as a motivation for using the UQ and optimization capabilities in FOQUS for complex models which take a long time to converge.

**Comment by boverhof** [comment]
The following issue will address some of the concerns #801
