### ISSUE TITLE
pylint errors in foqus_lib/gui

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#790]
Part of the ongoing effort to address #600.

## False positives

- `foqus_lib/gui/common/InputPriorTable.py:138:16: E1136: Value 'combobox.currentIndexChanged' is unsubscriptable (unsubscriptable-object)`
  - PyQt overloaded signals cause false positives in pylint: see also https://github.com/PyCQA/pylint/issues/3140
  - Also found in:
    - `foqus_lib/gui/uq/RSCombos.py:126:8 `
    - `foqus_lib/gui/uq/RSCombos.py:167:8 `
    - `foqus_lib/gui/uq/RSCombos.py:172:26`
    - `foqus_lib/gui/uq/RSCombos.py:173:12`
    - `foqus_lib/gui/uq/RSCombos.py:206:26`
    - `foqus_lib/gui/uq/RSCombos.py:207:12`
    - `foqus_lib/gui/uq/RSCombos.py:222:8 `
    - `foqus_lib/gui/uq/RSCombos.py:263:26`
    - `foqus_lib/gui/uq/RSCombos.py:264:12`
- `foqus_lib/gui/model/dmfUploadDialog.py:14:4: E0401: Unable to import 'dmf_lib.dmf_browser' (import-error)` and all other errors in `foqus_lib.gui.model.dmfUploadDialog`
  - All import statements are in an import guard (`try: import X; except: ...`), so possible import errors seem to be already accounted for

## Need more investigation

- `foqus_lib/gui/sdoe/sdoeSetupFrame.py:124:83: E0602: Undefined variable 'row' (undefined-variable)`
  - Signal is connected to lambda with a single parameter `data`, but calls method `changeDataInSimTable()` with `data, row`
  - Also found in: `foqus_lib/gui/uq/uqSetupFrame.py:381:83`
- `foqus_lib/gui/sdoe/sdoeAnalysisDialog.py:21:0: E0102: class already defined line 7 (function-redefined)`
  - The local definition of `sdoeAnalysisDialog` shadows the one imported on L7 from `.sdoeSetupFrame`
- `foqus_lib/gui/ouu/foqusPSUADEClient.py:56:12: E1101: Instance of 'int' has no 'extend' member (no-member)`, `foqus_lib/gui/ouu/foqusPSUADEClient.py:61:19: E1133: Non-iterable value row is used in an iterating context (not-an-iterable)`
  - This should be a false positive: the correct data format is set later in the code, but the initial value has a different shape
  - Possible solution: prefill `inData` at L33 with a list-of-lists rather than a list, i.e. `inData = nSamp * [[0]]`
- `foqus_lib/gui/heatIntegration/heatIntegrationFrame.py:15:8: E0602: Undefined variable 'heatIntObject' (undefined-variable)` and `foqus_lib/gui/heatIntegration/heatIntegrationFrame.py:15:35: E0602: Undefined variable 'hratEdit' (undefined-variable)`
- `foqus_lib/gui/uq/SimSetup.py:718:11: E1120: No value for argument 'session' in constructor call (no-value-for-parameter)`
- `foqus_lib/gui/ouu/ouuSetupFrame.py:945:16: E1128: Assigning result of a function call, where the function returns None (assignment-from-none)`

## Notes

- Is there a convention for PyQt imports, i.e. mostly `from PyQt5 import QtWidgets; QtWidgets.QMessageBox(...)` vs `from PyQt5.QtWidgets import QMessageBox; QMessageBox(...)`?

**Comment by sotorrio1** [comment]
@lbianchi-lbl I'll try to take care of all the issues related to UQ, OUU, SDOE and PSUADE. Thanks!
