### ISSUE TITLE
FOQUS Cloud: Optimization and UQ on cloud

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#800]
# Description

Run optimization and UQ on the cloud. That way you can easily start up multiple optimzation or UQ runs in parallel and don't need to keep your machine running. This should be fairly easy to implement. Instead of just single flowsheet runs, we can allow optimization and UQ model. You can download the FOQUS session when it's done for the results. We can probably save the session periodically while it's running so you can check progress.

# Detail
Will require an `optimization` descriptor ( JSON ) that can be submitted to the FOQUS Cloud.

**Comment by eslickj** [comment]
I'll try to take a look at this in the next 2 weeks.

**Comment by ksbeattie** [comment]
This has now shifted to Milestone [EY22.4.1.D](https://github.com/CCSI-Toolset/FOQUS/milestone/23)
