### ISSUE TITLE
FOQUS UI and Cloud User Notifications/Feedback 

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#801]
# Description

Currently the FOQUS UI doesn't provide much feedback to the user about the status of the cloud and jobs.  There are Log messages going to the debug screen, but likely need notifications going to the FOQUS UI about events concerning users.

# Events
1) Cloud start up:  VMs initializing etc
2) Flowsheet progress
3) ...

# Solution
- User-centric Activity Window

# GIT 
- https://github.com/boverhof/FOQUS/tree/foqus_cloud_notifications

# Configuration
- Add a `Notification` section in `turbine.cfg`
```
(py3.9) joshuas-mbp:workspace.ccsi2 boverhof$ cat foqus_working_dir/turbine.cfg 
[Consumer]
url = https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/consumer/

[Job]
url = https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/job/

[Simulation]
url = https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/simulation/

[Session]
url = https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/session/

[Application]
url = https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/application/

[Notification]
url = wss://du6p1udafi.execute-api.us-east-1.amazonaws.com/Development

[Authentication]
username = ****
password = *****
```

**Comment by ksbeattie** [comment]
In progress...

**Comment by boverhof** [comment]
# Web Socket Help Browser
- commit https://github.com/CCSI-Toolset/FOQUS/commit/99b25c593f4e6e87218fd4564cf776f709aec738
##  Help Browser
- File: foqus_lib/gui/help/helpBrowser_UI.ui
- Added a new tab widget where notifications will be published from a web socket
## AWS API Gateway Web Socket Application
- Published a Web Socket application that pushes out notifications to all registered clients

**Comment by boverhof** [comment]
# WebSocket 
## status command
Provides a view of the current status of EC2, AutoScaling group, and SQS ( job queue ).
### Command
```
> (py3) joshuas-mbp:foqus-boverhof boverhof$ wscat --auth $USERCRED  -c $WSS_URL
> {"action":"status"}
....

```
### SQS
```
$ jq '.sqs.Attributes' /tmp/test.json 
```
```json
{
  "VisibilityTimeout": "30",
  "MaximumMessageSize": "262144",
  "MessageRetentionPeriod": "345600",
  "ApproximateNumberOfMessages": "0",
  "ApproximateNumberOfMessagesNotVisible": "0",
  "ApproximateNumberOfMessagesDelayed": "0",
  "DelaySeconds": "0",
  "ReceiveMessageWaitTimeSeconds": "0"
}
```
### AutoScaling Group
```
$ jq '.autoscale.AutoScalingGroups[0] | {AutoScalingGroupName,MinSize,MaxSize,DesiredCapacity} ' /tmp/test.json 
```
```json
{
  "AutoScalingGroupName": "FOQUS_Workers_AutoScale_v1",
  "MinSize": 0,
  "MaxSize": 5,
  "DesiredCapacity": 0
}
```
### EC2 instances
```
f$ jq '.ec2.Reservations[].Instances[] | { InstanceType, Platform, State, Tags }' /tmp/test.json 
```
```json
{
  "InstanceType": "t2.micro",
  "Platform": "windows",
  "State": {
    "Code": 16,
    "Name": "running"
  },
  "Tags": [
    {
      "Key": "Name",
      "Value": "SLM License Server"
    }
  ]
}
```

**Comment by boverhof** [comment]
![Screen Shot 2020-12-11 at 10 47 22 AM](https://user-images.githubusercontent.com/738295/101942481-6cbb0700-3b9e-11eb-8c95-b1c619f2f389.png)

**Comment by boverhof** [comment]
![Screen Shot 2020-12-11 at 11 09 11 AM](https://user-images.githubusercontent.com/738295/101945216-bc033680-3ba2-11eb-923c-67056ae654ae.png)

**Comment by boverhof** [comment]
The next thing to do is add an output for `Consumers`, which are FOQUS Worker that have registered with the FOQUS Cloud and are ready to start work.  And possibly dump all active jobs..

![Screen Shot 2020-12-11 at 11 15 50 AM](https://user-images.githubusercontent.com/738295/101945470-1ef4cd80-3ba3-11eb-9f59-d71b614f3ec4.png)

**Comment by boverhof** [comment]
#859
