### ISSUE TITLE
pylint errors in foqus_lib/framework/optimizer/SM_Optimizer.py

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#805]
Parts of the efforts towards #600.

- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L364` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L364)) Undefined variable 'Var'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L369` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L369)) Undefined variable 'Var'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L395` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L395)) Undefined variable 'Objective'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L397` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L397)) Undefined variable 'ConstraintList'
- [ ]  `foqus_lib.framework.optimizer.SM_Optimizer:L428` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L428)) Undefined variable 'Warmstart'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L469` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L469)) Undefined variable 'value'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L499` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L499)) Undefined variable 'value'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L507` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L507)) Undefined variable 'value'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L513` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L513)) Undefined variable 'Var'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L540` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L540)) Undefined variable 'value'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L553` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L553)) Undefined variable 'Var'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L877` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L877)) Undefined variable 'ConstraintList'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L913` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L913)) Undefined variable 'value'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L943` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L943)) Undefined variable 'value'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L948` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L948)) Undefined variable 'Var'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L967` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L967)) Undefined variable 'value'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L982` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L982)) Undefined variable 'Var'
- [x]  `foqus_lib.framework.optimizer.SM_Optimizer:L1114` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/optimizer/SM_Optimizer.py#L1114)) Undefined variable 'value'

The errors seem to be due to the wildcard import from `pyomo.environ` on L48.

**Comment by ksbeattie** [comment]
Try following [these doc/install](https://foqus.readthedocs.io/en/stable/chapt_sm_optimizer/reference/SM_based_optimizer_introduction.html#additional-python-packages-required) steps to make sure the plugin still works after pylint changes.

**Comment by lbianchi-lbl** [comment]
These should be addressed by #806, which itself is almost complete except for `Warmstart` (see https://github.com/CCSI-Toolset/FOQUS/pull/806#issuecomment-694569296).
