### ISSUE TITLE
pylint errors in foqus_lib/framework/uq/Plotter.py

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#811]
Parts of the efforts towards #600.

- [ ]  `foqus_lib.framework.uq.Plotter:L45` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/uq/Plotter.py#L45)) Undefined variable 'can_exit'
- [x]  `foqus_lib.framework.uq.Plotter:L680` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/uq/Plotter.py#L680)) Module 'matplotlib.cm' has no 'jet' member
- [x]  `foqus_lib.framework.uq.Plotter:L699` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/uq/Plotter.py#L699)) Module 'matplotlib.cm' has no 'jet' member

Concerning the last two, it could be that the `jet` colormap has been removed from matplotlib.

**Comment by sotorrio1** [comment]
The first one; I don't think the method closeEvent is being used at all so I might delete it. 
For the last two, I found the issue and will be creating a PR with the fix shortly.
