### ISSUE TITLE
pylint errors in foqus_lib/framework/sim/turbineConfiguration.py

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#812]
Parts of the efforts towards #600.

- [x]  `foqus_lib.framework.sim.turbineConfiguration:L995` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/sim/turbineConfiguration.py#L995)) No value for argument 'jobID' in method call
- [x]  `foqus_lib.framework.sim.turbineConfiguration:L1004` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/sim/turbineConfiguration.py#L1004)) Too many arguments for format string
- [x]  `foqus_lib.framework.sim.turbineConfiguration:L1007` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/sim/turbineConfiguration.py#L1007)) Undefined variable 'jobid'
- [x]  `foqus_lib.framework.sim.turbineConfiguration:L1010` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/sim/turbineConfiguration.py#L1010)) Undefined variable 'jobid'
- [ ]  `foqus_lib.framework.sim.turbineConfiguration:L1229` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/sim/turbineConfiguration.py#L1229)) Undefined variable 'sinterConfigPath'
- [ ]  `foqus_lib.framework.sim.turbineConfiguration:L1236` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/sim/turbineConfiguration.py#L1236)) Undefined variable 'sinterConfigPath'
- [x]  `foqus_lib.framework.sim.turbineConfiguration:L1454` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/sim/turbineConfiguration.py#L1454)) errList is not callable

**Comment by lbianchi-lbl** [comment]
Just as a heads-up, the last error in the list ("errList is not callable") might be a pylint false positive. I'll look into that.

**Comment by ksbeattie** [comment]
@boverhof these all look pretty simple to fix.  Can you take a look?
