### ISSUE TITLE
pylint errors in foqus_lib/framework/uq/LocalExecutionModule.py

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#813]
Part of the efforts towards #600.

- [x]  `foqus_lib.framework.uq.LocalExecutionModule:L652` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/uq/LocalExecutionModule.py#L652)) Too many arguments for format string
- [x]  `foqus_lib.framework.uq.LocalExecutionModule:L669` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/uq/LocalExecutionModule.py#L669)) Too many arguments for format string
- [ ]  `foqus_lib.framework.uq.LocalExecutionModule:L942` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/framework/uq/LocalExecutionModule.py#L942)) Class 'LocalExecutionModule' has no 'getNumFinishedRuns' member

**Comment by sotorrio1** [comment]
Found a fix for the first two, still trying to figure out what that line of code in the third one does (I don't think it does anything...)
