### ISSUE TITLE
pylint errors in foqus_lib/gui/heatIntegration/HeatIntegrationFrame.py

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#817]
Part of the efforts towards #600.

- [ ]  `foqus_lib.gui.heatIntegration.heatIntegrationFrame:L15` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/gui/heatIntegration/heatIntegrationFrame.py#L15)) Undefined variable 'heatIntObject'
- [ ]  `foqus_lib.gui.heatIntegration.heatIntegrationFrame:L15` ([link](https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/gui/heatIntegration/heatIntegrationFrame.py#L15)) Undefined variable 'hratEdit'

This seems to be a genuine error, in the sense that neither of these variable appear to be defined anywhere in the scope, but there could be less obvious ways through which these variables are defined that I'm missing; I'm not familiar with e.g. the way `PyQt5.uic.loadUiType()` works, which might or might not be related to these variables.

**Comment by ksbeattie** [comment]
@lbianchi-lbl will make an ulgy fix for this hidden and otherwise broken module.

@anujad95 a/o @eslickj will talk to Mike about the future of this HeatIntegration feature: either remove or find a maintainer.
