### ISSUE TITLE
Improve plug-in visibility, documentation and configuration

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#818]
The list of possible plug-ins, what is required for them to be available, how to install their requirements and their documentation could be improved.  Possible ideas are:

- Re-work installation of optional components to list plug-ins in a table with a column for requirements.
- Add to the UI have the list of plug-ins there with check-boxes for which ones are activated, save that to the foqus.cfg, and check for the required modules and display informative messages if they are missing.

Ideally this will also help with testing, manual and automated, of these plugins.

**Comment by ksbeattie** [comment]
Somewhat related to #908

**Comment by boverhof** [comment]
no progress, outdated
