### ISSUE TITLE
Issue when plotting a new design with historical runs included

### ISSUE THREAD

**Issue by Daison2102** [CCSI-Toolset/FOQUS#829]
Issues when reproducing Examples USF-2 in the Sequential Design of Experiments.

This issue is related to plotting a new design with the historical runs included. For the example USF-2, I used the attached files, the “SDOE_Ex1_Candidates.csv” file as candidate file and the “usf_d8_n10000_Label+X1+X2.csv” as history file. The options for the SDOE were: Uniform Space Filling, Minimax, Min Design Size = Max Design Size = 8, Label Column = index and X1, X2 = inputs.
After the SDOE module created the design, I tried to plot the new design along with the historical data by selecting the View option in the Created Designs Table, and then selecting Plot SDOE. The issue below arises in the terminal at this point.  The same issue arises when reproducing example Example USF-3.

Traceback (most recent call last):
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\gui\sdoe\sdoePreview.py", line 118, in plotSdoe
    plot_utils.plot(fname, scatterLabel, hname=hname, show=show, nusf=nusf)
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\sdoe\plot_utils.py", line 149, in plot
    df, hf = load_data(fname, hname)
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\sdoe\plot_utils.py", line 40, in load_data
    assert (names == list(hf))
AssertionError

- **Files**

[files.zip](https://github.com/CCSI-Toolset/FOQUS/files/5343632/files.zip)

![Issue when plotting a new design with historical runs included](https://user-images.githubusercontent.com/32642037/95384252-5355c000-08ba-11eb-86ab-7828db9c1208.png)

**Comment by sotorrio1** [comment]
This issue and issue #828   should get fixed with PR #831

**Comment by Daison2102** [comment]
Fixed
