### ISSUE TITLE
Appveyor does not fail when errors occur during PyPI package build test

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#842]
A change in how packages are found in the `setup.py` build process was introduced in PR #832. This causes the `cloud` directory, which contains a file that has a syntax error, to be included in the build.

This error should have been caught by the Appveyor test on `setup.py build`, thus blocking PR #832 from getting merged. The Appveyor log does show the error, but the error wasn't detected or propagated to the Appveyor build result status.

This only affects building the package, so installing the package (which most likely is all that's needed for non-maintainers) should not be affected. Nonetheless, this is a false negative that the testing pipeline failed to catch, and it should be addressed.

**Comment by ksbeattie** [comment]
Closing as these errors will be caught by pylint and/or other testing

**Comment by lbianchi-lbl** [comment]
@ksbeattie It seems the step that's failing is `python setup.py install` (see e.g. [here](https://ci.appveyor.com/project/ksbeattie/foqus/builds/36122206#L225)).

I think that the error with the long filenames does not happen for the earlier`pip install -r requirements-dev.txt` (exiting successfully [here](https://ci.appveyor.com/project/ksbeattie/foqus/builds/36122206#L222)) because `requirements-dev.txt` installs the FOQUS package in editable mode, which links the directory to the `site-packages` installation destination, unlike `setup.py install`, which copies the source directory and its contents there, and therefore I believe is the step where the files with too long names are accessed for the first time by Python code (`setuptools`) in the Appveyor tests.
