### ISSUE TITLE
Turbine Connection Error

### ISSUE THREAD

**Issue by MDCA960418** [CCSI-Toolset/FOQUS#848]
Hello,

I get the following error when uploading an Aspen model to Turbine (latest version December 2019 release). 

![image](https://user-images.githubusercontent.com/66323673/98619980-546f7800-22d2-11eb-8a55-c92124f7922c.png)

I tested the Turbine connection in the settings tab to troubleshoot, and it gives the following message.

![image](https://user-images.githubusercontent.com/66323673/98620085-939dc900-22d2-11eb-8863-c153d5a65d80.png)

**Comment by MDCA960418** [comment]
Hello @boverhof,

When would it be possible to look at this issue?

Thanks.

**Comment by boverhof** [comment]
@MDCA960418 

First, I'll need some details about what you've done.

- Operating System/Version
- FOQUS Installation:
what directions are you following?
did you download and install FOQUS and TurbineLite  or did you use "pip" to do this?

If you didn't install TurbineLite you should follow these directions:

https://foqus.readthedocs.io/en/stable/chapt_install/install_optional.html

Under `Install Turbine and SimSinter (Windows Only)`

**Comment by MDCA960418** [comment]
- Version is FOQUS 3.5.1
-I installed it a while ago, never had this issue with Turbine. Previously, I was able to upload models with no issue.
-I downloaded FOQUS and then installed TurbineLite

**Comment by boverhof** [comment]
open the `window services` and see if the TurbineWebAPI is running.  If it is not, start it.

<img width="1317" alt="Screen Shot 2020-11-12 at 2 03 48 PM" src="https://user-images.githubusercontent.com/738295/99001730-354e3180-24f0-11eb-8183-a4dbb558a1a6.png">

**Comment by boverhof** [comment]
If the service starts up correctly you should be able to use a web browser ( below chrome ) with the TurbineWebAPI:

<img width="1092" alt="Screen Shot 2020-11-12 at 2 16 18 PM" src="https://user-images.githubusercontent.com/738295/99002729-bfe36080-24f1-11eb-9a89-e6e6b8f486cb.png">

**Comment by MDCA960418** [comment]
I tried that, but it seems like I am unable to start it

![image](https://user-images.githubusercontent.com/66323673/99002849-1e690880-250b-11eb-96c7-70460eda5a42.png)

**Comment by boverhof** [comment]
Open up `event viewer` and look under `Windows Logs` and `Application`.  There should be an error entry 

![Uploading Screen Shot 2020-11-12 at 2.20.49 PM.png…]()

**Comment by MDCA960418** [comment]
It is showing a lot of warnings

![image](https://user-images.githubusercontent.com/66323673/99004581-596c3b80-250d-11eb-8908-916222754a86.png)

**Comment by boverhof** [comment]
The latest record was from `11/09/2020`, I'm not seeing Windows service up there.  If you `start` it there should be an event log in there from the attempt.  Please send me the one under `Application Error` from last week.  Try looking under `Security` too.


When is the last time you rebooted the computer?

**Comment by MDCA960418** [comment]
Last reboot was October 6th.

![image](https://user-images.githubusercontent.com/66323673/99008006-55dbb300-2513-11eb-9da0-dc9ea8f79f57.png)

**Comment by boverhof** [comment]
Reboot the computer and see if the TurbineWebAPI comes up.  

I assume things are greyed out for you because you're not logged in as an Administrator.  But I'm not too sure.

**Comment by MDCA960418** [comment]
The issue has been resolved, Turbine connection works now. However, it is worth mentioning that when running a simulation and a failed run is detected, FOQUS gives the following message:

![image](https://user-images.githubusercontent.com/66323673/99079339-d17a4600-258d-11eb-8f5f-94fb71c39cb3.png)

The simulation won't continue unless the user clicks ok on that window. Then, the simulation has to be stopped and started so it can continue. That is the reason why I was having some Application Errors in the Event Properties window.

Many thanks for your help @boverhof

**Comment by MDCA960418** [comment]
Hello @boverhof!

I am experiencing issues with finding my models in Turbine. I tested the turbine connection and it works fine. I also rebooted the computer twice, but the same issue persists. Please, see snapshot below.

![image](https://user-images.githubusercontent.com/66323673/101064553-1e848300-3562-11eb-9e18-a46f06580472.png)

**Comment by ksbeattie** [comment]
@MDCA960418, I'm going to close this issue and we can proceed with your last comment in #854.  ok?
