### ISSUE TITLE
FOQUS UQ Tutorial problem

### ISSUE THREAD

**Issue by wvuecust** [CCSI-Toolset/FOQUS#853]
I tried to open the FOQUS example of UQ Tutorial_5, but the filtered file can not be load successfully. 
The error shows as follows
 File "c:\users\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\gui\main\mainWindow.py", line 1068, in loadData
    self.dat.load(fileName)
  File "c:\users\anaconda3\envs\ccsi-foqus\lib\site-packages\foqus_lib\framework\session\session.py", line 507, in load
    sd = json.load(f, object_pairs_hook=collections.OrderedDict)
  File "c:\users\anaconda3\envs\ccsi-foqus\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\users\anaconda3\envs\ccsi-foqus\lib\json\__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "c:\users\anaconda3\envs\ccsi-foqus\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\anaconda3\envs\ccsi-foqus\lib\json\decoder.py", line 355, in raw_decode
    **raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

**Comment by sotorrio1** [comment]
@wvuecust I can't reproduce your error. Would you mind giving me a better description of what you did? Step-by-step. Here is mine:

1. Open FOQUS
2. Go to UQ tab
3. Click "Load From File..." button
4. Go to examples/tutorial_files/UQ/Tutorial_5/
5. Select the only file in there "lptau5k_10inputs_4outputs.filtered"
6. Click "Open"

And the file loads fine (see screenshot below)
<img width="1439" alt="Screen Shot 2020-12-03 at 9 25 28 AM" src="https://user-images.githubusercontent.com/33531919/101065026-81b5eb80-3549-11eb-802f-7e744a274bcb.png">

**Comment by wvuecust** [comment]
> @wvuecust I can't reproduce your error. Would you mind giving me a better description of what you did? Step-by-step. Here is mine:
> 
> 1. Open FOQUS
> 2. Go to UQ tab
> 3. Click "Load From File..." button
> 4. Go to examples/tutorial_files/UQ/Tutorial_5/
> 5. Select the only file in there "lptau5k_10inputs_4outputs.filtered"
> 6. Click "Open"
> 
> And the file loads fine (see screenshot below)
> <img alt="Screen Shot 2020-12-03 at 9 25 28 AM" width="1439" src="https://user-images.githubusercontent.com/33531919/101065026-81b5eb80-3549-11eb-802f-7e744a274bcb.png">

Thanks a lot. Problem solved.
Initially, I tried to open it from session, that doesn't work.
