### ISSUE TITLE
Turbine Error

### ISSUE THREAD

**Issue by MDCA960418** [CCSI-Toolset/FOQUS#854]
Hello @ksbeattie 

I am experiencing issues with finding my models in Turbine. I tested the turbine connection and it works fine. I also rebooted the computer twice, but the same issue persists. Please, see snapshot below.

![image](https://user-images.githubusercontent.com/66323673/101064553-1e848300-3562-11eb-9e18-a46f06580472.png)

**Comment by boverhof** [comment]
This looks like the configuration file `turbine.cfg` is missing.

**Comment by MDCA960418** [comment]
The debug window does not show anything, only output is given for the log viewer.

The configuration for both, local and remote turbine are working.

![image](https://user-images.githubusercontent.com/66323673/101552031-1e302180-3980-11eb-8bda-96b53d7cb3f0.png)

**Comment by boverhof** [comment]
You probably need to turn on logging.  When I do a "test" of the gateway it shows all the REST API calls.
```
2020-12-10 08:50:26,469 - DEBUG - foqus.foqus_lib.framework.sim.turbineConfiguration - turbine configuration application url="https://b7x9ucxadg.execute-api.us-east-1.amazonaws.com/development/application/"
```

![Screen Shot 2020-12-10 at 8 47 30 AM](https://user-images.githubusercontent.com/738295/101803068-fd251900-3ac4-11eb-9502-a996bfde9018.png)

**Comment by boverhof** [comment]
You should be able to take the URL for the Simulation resource and view it.

The base URL is:
   `http://localhost:8000/TurbineLite/Simulation` 

That should return a JSON array of all the simulations.  You can put that in a web browser and check.

**Comment by MDCA960418** [comment]
@boverhof 

I pasted the link into web browser and I got the following

![image](https://user-images.githubusercontent.com/66323673/101959038-91c96d00-3bd2-11eb-9a39-06a58852f513.png)

**Comment by boverhof** [comment]
# Diagnosis
From the traceback it appears like this is failing on a ORM method on the TurbineLite database.  All it is trying to do is a for loop on a query for all the simulations in your database and this is not working.  

My guess is one of your simulation entries doesn't match the expected entries, like it's missing a name field, or maybe the name has special characters in it.  Something along those lines.

There is a Turbine debug but likely all it will show you is:

` C:\Program Files (x86)\Turbine\Lite\Logs\TurbineWebAPIService.log`
```
GET Session List
Turbine.Lite.Web.Resources.Contracts.DataMarshall: GetSessions
SimulationResource: get all simulations
DataMarshall.GetSimulations: Simulation
```

# Try
- Stop the TurbineWeb service
- Rename the database
- Restart the TurbineWeb service
- Try again

If you can please send me the database file so I can figure out what is going wrong.



<img width="893" alt="Screen Shot 2020-12-14 at 10 56 48 AM" src="https://user-images.githubusercontent.com/738295/102124391-10a1ee00-3dfd-11eb-86ba-fb1bed06a127.png">

<img width="986" alt="Screen Shot 2020-12-14 at 10 57 31 AM" src="https://user-images.githubusercontent.com/738295/102124410-1566a200-3dfd-11eb-95cc-25340d64445e.png">

<img width="906" alt="Screen Shot 2020-12-14 at 10 57 48 AM" src="https://user-images.githubusercontent.com/738295/102124422-17c8fc00-3dfd-11eb-9e10-498915f6f3d9.png">

**Comment by MDCA960418** [comment]
@boverhof I can't stop Turbine Web Service because I do not have the admin rights.

**Comment by LNemetz** [comment]
@boverhof I'm working with @MDCA960418 on this. I tried renaming the database but the same error occurred. 
I can't upload the file as it's to large, even compressed as a zip folder, how can I send you the database file?

**Comment by anujad95** [comment]
@MDCA960418 just to confirm, you get this error while loading a new json file in turbine right? Also, is this a recent issue, and were you able to upload models in turbine before this? You may want to check what can be seen after the "simulation name" dropdown is clicked within "add/update turbine model", and let us know. Also, please check that the json file and turbine simulation names do not contain spaces/special characters.

**Comment by MDCA960418** [comment]
Hello @anujad95,

Yes, the error shows up when loading a json file into Turbine. When clicking on the dropdown menu of 'simulation name', nothing comes up, that should not happen as I have other models. This is the first time this issue happens, I have had other problems with Turbine before, but they were solved by rebooting the computer. In this case, that has not helped. 

The json file I was trying to upload had an underscore on it but no spaces, I don't know if that is the issue. I have uploaded models with underscores on it before and it worked fine.

**Comment by anujad95** [comment]
Underscores are fine. You can try to remove the TurbineLite Database after shutting down the TurbineWebAPI in control panel services and restart it. The Database must have been corrupted for some reason. @boverhof i think this had worked earlier when we tried to solve a similar issue.

**Comment by MDCA960418** [comment]
We are unable to shutdown or stop turbine from running, because we don't have the administration rights.
