### ISSUE TITLE
UQ: observation file load for bayesian inference under expert mode 

### ISSUE THREAD

**Issue by wvuecust** [CCSI-Toolset/FOQUS#855]
I tried to load observation file for bayesian inference under expert mode. 
The observations include two design variables and  one output variable.
It shows the attached warning for the design variable violating the max/min bound. In fact, the specified design variable max/min bound in both UQ and flowsheet is much larger than here the warning value.
Also, I change the flowsheet max/min bound for each variable (input and design). But the problem is not solved yet.
![捕获](https://user-images.githubusercontent.com/75398270/101215106-36840180-364b-11eb-9f7d-70203d7e90d6.JPG)

**Comment by sotorrio1** [comment]
@wvuecust Could you provide the .foqus session file you're using and a description of the steps you're following? Also a copy of the observation file would be useful. Thanks!

**Comment by wvuecust** [comment]
Thanks for your quick response.
Attached are my .foqus file and the observation file.
Step 1, choose any Ensemble to analyze
Step 2, under expert mode, go to bayesian inference
Step 3, Set 'log_tr' as output, and  'stress' and 'temp' as design
Step 4, load observation file
Since the response surface part works, the above-mentioned procedure
doesn't include it.
I look forward to hearing your feedback.
Thanks and regards,



Wang, Yifan
Department of Chemical and Biomedical Engineering
West Virginia University
Morgantown, WV26506, United States
Email: yw0001@mix.wvu.edu <xnhe@mix.wvu.edu>

**Comment by sotorrio1** [comment]
@wvuecust would you mind sending the attachments to sotorrio1@llnl.gov; I didn't get any attachments in here. Thanks!

**Comment by wvuecust** [comment]
Thanks for your reply.
Actually I solved the problem.
I just gave the new min/max for the variable in the flowsheet, and deleted
the old ensemble data, *then regenerated* the ensemble data.
Anyway, thank you so much for your help.

Wang, Yifan
Department of Chemical and Biomedical Engineering
West Virginia University
Morgantown, WV26506, United States
Email: yw0001@mix.wvu.edu <xnhe@mix.wvu.edu>

**Comment by sotorrio1** [comment]
@wvuecust no problem. Thank you for using FOQUS and reporting all these issues.
