### ISSUE TITLE
Creating a psuade-lite conda package

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#856]
Creating a lighter version of psuade (psuade-lite) in a conda package so it makes life easier for users and maintainers not having to build psuade from source to install it.

**Comment by lbianchi-lbl** [comment]
Currently testing compilation of psuade-lite with the conda-build tools needed to create a Conda package:

- [x] Linux 
- [ ] macOS
- [x] Windows

**Comment by sotorrio1** [comment]
code review process is done. I will provide the GitHub repository as soon as I create it. This psuade-lite version is needed for the newest capability, ODoE (PR #868)

**Comment by lbianchi-lbl** [comment]
Closing this as completed:

- psuade-lite repository on github: https://github.com/LLNL/psuade-lite
- psuade-lite Conda package: https://anaconda.org/CCSI-Toolset/psuade-lite
