### ISSUE TITLE
FOQUS:  Update Functions with typing

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#858]
# Description
One of the major difficulties of working on the FOQUS code base is the lack of clarity in how to properly use methods and functions.  Adding typing and asserts would help a lot and I propose as programmers work on this code base they should be adding typing and asserts.

# Example
```
class WebSocketApp(object):
    def __init__(self, url:str, widget:QTextBrowser, config:TurbineConfiguration):
        assert type(widget) is QTextBrowser, type(widget)
        assert type(config) is TurbineConfiguration, type(config)
```

**Comment by boverhof** [comment]
Potentially use a typing decorator
https://pypi.org/project/typecheck-decorator/

**Comment by ksbeattie** [comment]
MyPy is a good place to start:
http://mypy-lang.org/
https://mypy.readthedocs.io/en/stable/

**Comment by ksbeattie** [comment]
This is an on-going effort, so I'm closing this open-ended issue in preference to more specific issues.
