### ISSUE TITLE
SimSinter Issue: Cannot Upload Excel File

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#869]
When I tried to upload an Excel file to SimSinter, I received the following error message:

![image](https://user-images.githubusercontent.com/30811140/105772943-951d7b80-5f28-11eb-81f3-6c61aed3ee98.png)

**Comment by ksbeattie** [comment]
Is MS Excel installed on that system?  If so, which version?

**Comment by fsoepyan** [comment]
I have Microsoft Excel for Microsoft 365.

**Comment by ksbeattie** [comment]
@fsoepyan, Microsoft 365 isn't supported by SimSinter.

@boverhof, will look for or update our documentation on what versions are and not known to work.

**Comment by boverhof** [comment]
https://github.com/CCSI-Toolset/SimSinter/blob/master/docs/SimSinter%20InstallationGuide.pdf

It appears the documentation says MS Excel 2010 or newer, 365 is a MS Cloud offering that we haven't investigated integrating.

**Comment by fsoepyan** [comment]
I think the reason I was having the issue is because the Microsoft 365 license I was using was close to expiring.

But when I start using the Microsoft 365 license that I have under AristoSys, LLC, I managed to upload an Excel file to SimSinter.

In conclusion, the user can upload an Excel file to SimSinter when using Microsoft 365, as long as the user has a Microsoft 365 account for Excel.

I consider this issue to be resolved, and I will close this issue.
