### ISSUE TITLE
User Issue:  Staged Input HTTP 500 PUT Failure

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#870]
# Description
HTTP 500 Error on uploading staged in simulation file

# Detail

Hello everyone,

I recently tried to add new variables to a Json file for a new set of ensembles to run.  However, no matter what I do I get these same errors anytime I try to add any updated json file to turbine, regardless of whether it was working earlier:

pastedImage.png
and

2021-01-21 19:54:43,027 - ERROR - turbine.commands.requests_base - upload failed: {'_content': b'{"Code":101,"Description":"Bad Data Format","Detail":"Failed to Update Simulation v2_redo input CCSI_MEAModel.apw: An error occurred while updating the entries. See the inner exception for details.,    at System.Data.Entity.Internal.InternalContext.SaveChanges()\\u000d\\u000a   at Turbine.Lite.Web.Resources.Contracts.ProducerSimulationContract.UpdateInput(String inputFileName, Byte[] data, String content_type) in c:\\\\Users\\\\boverhof\\\\Documents\\\\Visual Studio 2012\\\\Projects\\\\turb_sci_gate\\\\Master\\\\Turbine.Lite.Web.Resources\\\\Contracts\\\\ProducerSimulationContract.cs:line 284\\u000d\\u000a   at Turbine.Lite.Web.Resources.SimulationResource.UpdateStagedInputFile(String nameOrID, String inputName, Stream data) in c:\\\\Users\\\\boverhof\\\\Documents\\\\Visual Studio 2012\\\\Projects\\\\turb_sci_gate\\\\Master\\\\Turbine.Lite.Web.Resources\\\\SimulationResource.cs:line 309. InnerException: An error occurred while updating the entries. See the inner exception for details. StackTrace:    at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()\\u000d\\u000a   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\\u000d\\u000a   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)\\u000d\\u000a   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)\\u000d\\u000a   at System.Data.Entity.Internal.InternalContext.SaveChanges()"}', '_content_consumed': True, '_next': None, 'status_code': 500, 'headers': {'Content-Length': '1649', 'Content-Type': 'application/json; charset=utf-8', 'Server': 'Microsoft-HTTPAPI/2.0', 'Date': 'Fri, 22 Jan 2021 02:54:42 GMT'}, 'raw': <urllib3.response.HTTPResponse object at 0x000001A71284F988>, 'url': 'http://localhost:8000/TurbineLite/simulation/v2_redo/input/CCSI_MEAModel.apw', 'encoding': 'utf-8', 'history': [], 'reason': 'Internal Server Error', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=348292), 'request': <PreparedRequest [PUT]>, 'connection': <requests.adapters.HTTPAdapter object at 0x000001A715CC42C8>}

The second error sounds like a data format error, but I don't know what specifically.  One likely cause of this problem was that I saved a file while foqus was frozen, which may have messed something up.  Let me know if any of this makes sense and what I could do to fix it.

Thank you,

Kamron

**Comment by boverhof** [comment]
### Please provide the size of the TurbineLite database and the Log file contents.
Database:  
```C:\Program Files (x86)\Turbine\Lite\Data\TurbineCompactDatabase.sdf```
LOG: 
```C:\Program Files (x86)\Turbine\Lite\Logs\TurbineWebAPIService.log```


### From Firefox/Chrome/etc navigate and provide the resource.

Simulation Root Resource

```http://localhost:8000/TurbineLite/simulation/```

Try to navigate to the Simulation Resource 

```http://localhost:8000/TurbineLite/simulation/v2_redo```

Then attempt to navigate to the input:

```http://localhost:8000/TurbineLite/simulation/v2_redo/input/CCSI_MEAModel.apw```



![Screen Shot 2021-01-26 at 1 23 47 PM](https://user-images.githubusercontent.com/738295/105907867-5811c180-5fda-11eb-944f-ea5093ae6677.png)

**Comment by kbrink21** [comment]
The database file size is 261248 kB
The log file size is 2117 kB

**http://localhost:8000/TurbineLite/simulation/ has this:**


  |  
-- | --
0 |  
Application | "AspenPlus"
Id | "286b2ca4-346b-4dd9-bb86-8c7634c525fe"
Name | "CCSI_MEAModel"
StagedInputs |  
0 |  
Id | "2526c777-ffdf-46b1-8264-ddb5af79bbe3"
MD5Sum | ""
Name | "aspenfile"
1 |  
Id | "5526df2e-9751-4c68-90af-b9e7feedd50f"
MD5Sum | "34FBC36624D9E5FDE2695F5442C2F78D0A8384E1"
Name | "CCSI_MEAModel_NCCC.apw"
2 |  
Id | "840c2dc9-32c8-432c-a49e-67cdaa64fb2d"
MD5Sum | "14B38A441EABB5E824EBEF5BDB25D9C05842343B"
Name | "ccsi10.dll"
3 |  
Id | "92a2f041-e6b8-46b8-b73e-ea8af44b3417"
MD5Sum | "70EA406A4CF3B372756DFDD45C953B21853EEC07"
Name | "CCSI_MEAModel.apw"
4 |  
Id | "b9a93254-e211-4460-b7bc-fb020591afa3"
MD5Sum | "F2277F3172A3676F685809A6EB9A5F98EFA56E5A"
Name | "configuration"
5 |  
Id | "c7083b42-ba2a-41fb-a653-5704d8e70142"
MD5Sum | "1D10F7DDCBEA2E7B8D7DD33C41A41F3BF8FE780B"
Name | "CCSI_MEAModel_NCCC.bkp"
6 |  
Id | "cf062d4d-6abe-4099-bed6-7de4fe1b03a8"
MD5Sum | "5D49D4F8E4D033DFCD325254EDBC12C314A42FDB"
Name | "ccsi10-corrected.dll"
7 |  
Id | "cfa86917-284f-4bfa-9128-89e99fe437a7"
MD5Sum | "18EFECBD135FBBECB75BDCF145112BDF114D6E8F"
Name | "ccsi.opt"
8 |  
Id | "f73d9897-5dd5-4e14-acf4-fedcac57e18c"
MD5Sum | "A4CB56CED86FEC9EB07A65C045E25584A149122B"
Name | "ccsi-corrected.opt"
1 |  
Application | "AspenPlus"
Id | "37061870-3f3f-4181-a9b2-6163fd230b78"
Name | "CCSI_MEAModel_not_old"
StagedInputs |  
0 |  
Id | "30837776-b2b8-472e-84b5-a073152dba92"
MD5Sum | "65C90C2E0AAC67E351D4436DDE5B9C3A36BE40A9"
Name | "configuration"
1 |  
Id | "6913af97-19e2-4a2e-9573-ceb340d72a75"
MD5Sum | ""
Name | "aspenfile"
2 |  
Application | "AspenPlus"
Id | "907e525b-765b-430c-9961-86bd25e635f7"
Name | "CCSIMEA_Model_Validation"
StagedInputs |  
0 |  
Id | "06199419-a200-4a8b-a205-4adcab804102"
MD5Sum | ""
Name | "aspenfile"
1 |  
Id | "28fc50c6-975b-4c62-8751-c62d684ab8a7"
MD5Sum | "A4CB56CED86FEC9EB07A65C045E25584A149122B"
Name | "ccsi-corrected.opt"
2 |  
Id | "29d17260-d967-4711-a3fe-0bad58b21ce4"
MD5Sum | "DAD3EFA95379E6F069F5798D723BA35034A41D46"
Name | "CCSI_MEAModel_NCCC.bkp"
3 |  
Id | "5c192398-4af9-41ec-8111-010126b51e1f"
MD5Sum | "5D49D4F8E4D033DFCD325254EDBC12C314A42FDB"
Name | "ccsi10-corrected.dll"
4 |  
Id | "9a2598cc-4afc-4dbb-9735-01a7154b7a70"
MD5Sum | "57B81F67982B7A5443FE483CC8A18C5E7F661CCA"
Name | "configuration"
3 |  
Application | "AspenPlus"
Id | "80e9c742-8f1c-4d13-9c08-2ae6c4f308d8"
Name | "delme"
StagedInputs |  
0 |  
Id | "45321e63-f8d7-45fe-9117-e5b20ddbf3ac"
MD5Sum | ""
Name | "aspenfile"
1 |  
Id | "6a3df5d3-c078-473d-bc91-df8ab4058c5d"
MD5Sum | "EB360E4FA63583EB95BF4F1CD187867DEE8098EA"
Name | "CCSI_MEAModel.apw"
2 |  
Id | "6d5f02bf-8bd4-49fb-b589-6cf7b14c993c"
MD5Sum | "E831F336DF2E651BC145B6A7CE59730ADE9AFA20"
Name | "configuration"
4 |  
Application | "AspenPlus"
Id | "de768ced-f35a-49a6-a688-f7c517d2df5a"
Name | "hypercube_old"
StagedInputs |  
0 |  
Id | "06c25f49-a8e1-42c1-9ebf-2623b0d92e8c"
MD5Sum | "18EFECBD135FBBECB75BDCF145112BDF114D6E8F"
Name | "ccsi.opt"
1 |  
Id | "1415743e-903a-4c26-a631-0559a227e4a6"
MD5Sum | "DA56D310346EF59661F83A1EB8EBBC50E09FA861"
Name | "configuration"
2 |  
Id | "52852113-744a-4351-9c92-d81399bb7e72"
MD5Sum | "70EA406A4CF3B372756DFDD45C953B21853EEC07"
Name | "CCSI_MEAModel.apw"
3 |  
Id | "9e9dce4f-e187-4293-9c97-5fd4d4db9342"
MD5Sum | "14B38A441EABB5E824EBEF5BDB25D9C05842343B"
Name | "ccsi10.dll"
4 |  
Id | "ccef9ecd-1191-4ba5-ba98-5d6d64e07d17"
MD5Sum | ""
Name | "aspenfile"
5 |  
Application | "AspenPlus"
Id | "8da85930-6ec3-42b0-9cc6-8509ee3219c8"
Name | "MEA_original"
StagedInputs |  
0 |  
Id | "a8ead9cf-b42f-45fd-b62c-1374efd59b32"
MD5Sum | "84DCA4FDBCA827D5253FDC0C3C5A7C9A138A3D3D"
Name | "CCSI_MEAModel.apw"
1 |  
Id | "ae6352cc-d21e-4a9a-b9b3-f6d2dc54ec17"
MD5Sum | ""
Name | "aspenfile"
2 |  
Id | "fc7ffe47-20a3-47d9-8963-ed3fd6afb924"
MD5Sum | "526895B0A754AFF7937E4FE5488896B560DD8D75"
Name | "configuration"
6 |  
Application | "AspenPlus"
Id | "cf5c6939-e782-48ba-8c10-e6381c316075"
Name | "test2"
StagedInputs |  
0 |  
Id | "1bb6a85a-9412-4a00-bafb-6b4396056265"
MD5Sum | "84DCA4FDBCA827D5253FDC0C3C5A7C9A138A3D3D"
Name | "CCSI_MEAModel.apw"
1 |  
Id | "544a6017-522a-48a1-b3bd-37b12f7e27d2"
MD5Sum | "18EFECBD135FBBECB75BDCF145112BDF114D6E8F"
Name | "ccsi.opt"
2 |  
Id | "87040dd9-d8fd-48e4-8c6d-9d3b8afda11c"
MD5Sum | "AB69D57DA23E3CA3B29D06AE2939BA1838259037"
Name | "configuration"
3 |  
Id | "bc533fee-0fb5-4fcc-9308-09ae33b32e2a"
MD5Sum | ""
Name | "aspenfile"
4 |  
Id | "cf3622f4-43a4-4594-a9d0-bbf7e0609cb0"
MD5Sum | "14B38A441EABB5E824EBEF5BDB25D9C05842343B"
Name | "ccsi10.dll"
7 |  
Application | "AspenPlus"
Id | "60c4e189-3b1b-4fb9-96cc-f3f1fd991b38"
Name | "test3"
StagedInputs |  
0 |  
Id | "158948b0-c378-4834-ab07-e8f5dc6e6280"
MD5Sum | "4761D582A7EF90E69D8E32412936EAB2378DCB0A"
Name | "Simulation 1.apw"
1 |  
Id | "86b4e5b6-f4ec-4e6b-bdba-251872f43153"
MD5Sum | "A50EC68B446E94313EC5CC36379223A1D87086B8"
Name | "configuration"
2 |  
Id | "f46c5310-be70-4216-91df-014851cc2b5c"
MD5Sum | ""
Name | "aspenfile"
8 |  
Application | "AspenPlus"
Id | "24029251-10bb-4406-83ad-555a2974be04"
Name | "v2"
StagedInputs |  
0 |  
Id | "ab0255f8-3bec-42be-85ce-4d9dc2be4489"
MD5Sum | "4761D582A7EF90E69D8E32412936EAB2378DCB0A"
Name | "Simulation 1.apw"
1 |  
Id | "bf149f28-d4ef-48e5-8d08-acd15715c85a"
MD5Sum | "CE1AFD7B2B7A430276625191917C035EE7BA7FBC"
Name | "configuration"
2 |  
Id | "eee25649-548c-4e47-852a-2757637ab1b8"
MD5Sum | ""
Name | "aspenfile"
9 |  
Application | "AspenPlus"
Id | "89809e22-e16e-45b4-9488-09d57ee009c4"
Name | "v2_redo"
StagedInputs |  
0 |  
Id | "bfb39b82-d278-4621-8716-28accee23c9d"
MD5Sum | "63F637A68E1A006BFE6BFDF974CE58464BD1B99B"
Name | "configuration"
1 |  
Id | "ea67b62d-6b7f-4400-8452-d828f7cdf4cd"
MD5Sum | ""
Name | "aspenfile"



**http://localhost:8000/TurbineLite/simulation/v2_redo has this**


  |  
-- | --
Application | "AspenPlus"
Id | "89809e22-e16e-45b4-9488-09d57ee009c4"
Name | "v2_redo"
StagedInputs |  
0 |  
Id | "bfb39b82-d278-4621-8716-28accee23c9d"
MD5Sum | "63F637A68E1A006BFE6BFDF974CE58464BD1B99B"
Name | "configuration"
1 |  
Id | "ea67b62d-6b7f-4400-8452-d828f7cdf4cd"
MD5Sum | ""
Name | "aspenfile"


**http://localhost:8000/TurbineLite/simulation/v2_redo/input/CCSI_MEAModel.apw has this even though the CCSI_MEAModel.apw file exists:**

<ErrorDetail>
<Code>101</Code>
<Description>Bad Data Format</Description>
<Detail>
simulation "v2_redo" input "CCSI_MEAModel.apw" does not exist
</Detail>
</ErrorDetail>

**Comment by boverhof** [comment]
For `v2_redo` the `aspenfile` is a blank, which means the content was never successfully uploaded.


First A couple years ago I updated Turbine to use a different FIPS crypto library, which created a bug that screwed up the simulation order.  I guess this is a possibility.  You should look at all `versions` of the simulations by adding a flag 'Verbose=true' to the HTTP GET.

```http://localhost:8000/TurbineLite/simulation/?verbose=true```

**Comment by boverhof** [comment]
Make sure the configuration file specifies the aspenfile name correctly, it should match.

Also there has been size limit issues in the past.  Possibly this is failing the upload, so try uploading the file directly as detailed below.

This issue #381 has a lot of details about using the command line tools to examine and upload files directly.  You can find the `turbine.cfg` in your FOQUS working directory or just make another one.

https://github.com/CCSI-Toolset/FOQUS/issues/381#issuecomment-486439633

```
(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_update -r aspenfile  v2_redo CCSI_MEAModel.apw turbine.cfg
```

If the above fails, attempt to upload a smaller file in its place.  For example, make a new file `CCSI_MEAModel.apw` that contains only 
```
hello world
```

**Comment by kbrink21** [comment]
I looked up http://localhost:8000/TurbineLite/simulation/?verbose=true in my web browser and didn't see any "versions" tag.  Does this mean something went wrong?

As for running turbine_simulation_update, after finding where this file was (it's in C:\Users\[username]\anaconda3\envs\ccsi-foqus\Scripts instead of \ProgramData\Anaconda3\Scripts) I tried running it and got an error saying "No module named 'turbine' " .  Am I running the right file?

As for the hello world test, I was able to create an apw file that was just a text file with "hello world," and I was able to upload it to foqus.  I'm not sure what this tells me about my problem though.

**Comment by boverhof** [comment]
```
I looked up http://localhost:8000/TurbineLite/simulation/?verbose=true in my web browser and didn't see any "versions" tag. Does this mean something went wrong?
```
This should show you all versions of the the simulation 'v2_redo'.  I'm just trying to see if there is a version of that simulation with both a 'configuration' and an 'aspenfile'.  It could be ordering is screwing things up, then I would suspect you have an the FIPS compliant version of TurbineLite that had a bug in it.


```
As for running turbine_simulation_update, after finding where this file was (it's in C:\Users[username]\anaconda3\envs\ccsi-foqus\Scripts instead of \ProgramData\Anaconda3\Scripts) I tried running it and got an error saying "No module named 'turbine' " . Am I running the right file?
```
I was assuming you're using `Anaconda` with a python that has `turbine` as an installed module.  Maybe you installed using `pip` and the setup is different?  If you have Anaconda open an Anaconda terminal and that should solve the module issue.

```
As for the hello world test, I was able to create an apw file that was just a text file with "hello world," and I was able to upload it to foqus. I'm not sure what this tells me about my problem though.
```
Uploading the `small` file successfully indicates to me that either there is probably a size limit we are butting up against that I haven't seen previously.

**Comment by kbrink21** [comment]
I tried running the turbine_simulation_update file in an anaconda prompt, and it still didn't work.

**Comment by kbrink21** [comment]
I actually fixed it just now.  I deleted a few old simulations in the turbine upload menu, and that fixed my problem for some reason.  Any idea why this caused my problem?
