### ISSUE TITLE
Scaling Spreadsheet in FOQUS example files not able to open

### ISSUE THREAD

**Issue by LingyanDeng** [CCSI-Toolset/FOQUS#872]
In the FOQUS-->Optimization-->Reference-->Problem Set Up-->step 4 (https://foqus.readthedocs.io/en/stable/chapt_opt/reference/optimization.html), it mentioned a scaling spreadsheet (in the FOQUS examples files) that provides a demonstration of the different scaling methods. The spreadsheet (\examples\other_files\Scaling_Spreadsheet) was unable to be opened .

**Comment by ksbeattie** [comment]
@fsoepyan this file seems corrupted, might you have an old correct copy of this still?

**Comment by ksbeattie** [comment]
@LingyanDeng, can you try [this scaling spreadsheet](https://github.com/ksbeattie/FOQUS/blob/ksb_872/examples/other_files/Scaling_Spreadsheet/scaling.xlsx?raw=true) file and let us know if it is correct?

**Comment by LingyanDeng** [comment]
@ksbeattie Thank you Keith for sharing the clean version of the scaling spreadsheet. It work from my end now.
