### ISSUE TITLE
Surrogate Modeling Tutorial 1: ALAMO      Figure and steps need update

### ISSUE THREAD

**Issue by LingyanDeng** [CCSI-Toolset/FOQUS#875]
I am using the newest version of FOQUS, in the FOQUS website, the Surrogate Modeling-->Tutorial1: ALAMO--> Method Setting--> Step 34 to 35 need update (https://foqus.readthedocs.io/en/stable/chapt_surrogates/tutorial/alamo.html), in the Setting Name column, there is no "**FOQUS Model (for UQ)**" and "**FOQUS Model (for Flowsheet)**" in this new version.  Also, in step 36, the "Initial Data Filter" has no option of "Initial". Maybe it intended to say "f1" as the filter created in step 28.

**Comment by anujad95** [comment]
Thanks @LingyanDeng 
So, in terms of the images that need to be updated in the tutorial, it would be Data Filter Dialog and ALAMO Method Settings.

**Comment by ksbeattie** [comment]
@MAZamarripa is going to review this.

**Comment by ksbeattie** [comment]
@LingyanDeng, do the changes that @anujad95 made look ok?

Here's the [before](https://foqus.readthedocs.io/en/3.8.0/chapt_surrogates/tutorial/alamo.html) and [after](https://foqus.readthedocs.io/en/3.9.0/chapt_surrogates/tutorial/alamo.html) pages.

**Comment by LingyanDeng** [comment]
> @LingyanDeng, do the changes that @anujad95 made look ok?
> 
> Here's the [before](https://foqus.readthedocs.io/en/3.8.0/chapt_surrogates/tutorial/alamo.html) and [after](https://foqus.readthedocs.io/en/3.9.0/chapt_surrogates/tutorial/alamo.html) pages.

Yes. The figures has been updated. I don't see any additional update needed at this point. Thank you.
