### ISSUE TITLE
AspenTech Engineering v12.0

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#877]
# Description
Need to obtain the v12.0 version, install, test with MEA model, and test with FOQUS and MEA Model.

- [x] Request AspenTech Engineering v12.0
- [x] Install on VM
- [x] Test with MEA Model 
- [x] test MEA Model With FOQUS

**Comment by boverhof** [comment]
# Request AspenTech Engineering v12.0
https://esupport.aspentech.com/S_TrackCase?cNumber=01952213
```
Dear Joshua Boverhof,


Customer Care Case# 01952213 has been created

Company:          U.S. Department of Energy
Caller Site:         U.S. Department of Energy
Contact Name:   Joshua Boverhof



Best Regards,
Aspen Technology, Inc.
www.aspentech.com
```

**Comment by ksbeattie** [comment]
Related to #878

**Comment by boverhof** [comment]
## Download Granted
Sounds like it's possible may need to update SLM license server and the actual license.  Will follow up with a consultant.
```
Dear JOSHUA,

Thank you for your recent request for the aspenONE V12.0 release.
 
You can now download the software, the tool to update your licenses and associated installation documentation may be accessed using the following link:

     https://esupport.aspentech.com/S_DownloadCenter
 
Your download links will now appear within your support account.  As an alternative to using the above link, you can log into your account, click on “Support” then select “Download Center”.   

Visit our Product Upgrade Journey page on the support site for best practices to help you upgrade faster and more efficiently.
 
IMPORTANT: You will need to update your SLM Server software on your license server to V12, as well as update your license file, to use any of the new features in this V12 release (https://www.aspentech.com/en/whats-new). 

You can download the SLM Server software here (https://esupport.aspentech.com/S_Article?id=000096556) and the Aspen License Deployment Assistant (ALDA) to update your license files here (https://esupport.aspentech.com/S_Article?id=000097332). 
```

**Comment by jmorgan29** [comment]
I have verified that the MEA model works in V12, using the ccsi11.dll file created for the last release. The results from the tutorial are reproducible. I will follow up with the results from testing in FOQUS.

**Comment by jmorgan29** [comment]
I set up an example problem in FOQUS using the MEA steady-state model in V12, and executed the work without any issues.

**Comment by jmorgan29** [comment]
The following pull request is proposed to modify the documentation in the MEA SSM to indicate compatibility with V12:

https://github.com/CCSI-Toolset/MEA_ssm/pull/18
