### ISSUE TITLE
Could Foqus be linked to the economic evaluation of an Aspen simulation?

### ISSUE THREAD

**Issue by jbernier040** [CCSI-Toolset/FOQUS#893]
Aspen simulator uses Aspen Process Economic Analyzer (APEA) to make an estimation of Capital cost and utility cost, my question is, Could Foqus linked whit Aspen (APEA) when Foqus is used to make a variability analysis of parameter in a simulation? 
![ASPEN - APEA picture](https://user-images.githubusercontent.com/79927485/110944873-082d5680-830b-11eb-9416-20639db4fa58.png)

**Comment by ksbeattie** [comment]
@jbernier040, thanks for the suggestion, we'll look into if this is possible with FOQUS.

**Comment by jmorgan29** [comment]
After investigating this issue, it seems as if the output variables associated with APEA (e.g., Total Capital Cost, Total Operating Cost, ... as shown in the screen shot) are not available in the Aspen Plus variable tree, which means that they cannot be added to a Sinter configuration file and imported into FOQUS.

**Comment by ksbeattie** [comment]
@jbernier040, it appears that the answer, for now, is no.  Feel free to contact us again, or re-open this is you have other questions or ideas.
