### ISSUE TITLE
Flowsheet: getting variable from "Variable Explorer" to "Node Script"

### ISSUE THREAD

**Issue by puttak** [CCSI-Toolset/foqus#91]
In Flow sheet mode, under node-script panel, it would be really nice and easy to work if we can get the variables from the variable explorer to the python code. We already have mode to see them. It will help little bit for the user if they can insert them directly to python code by clicking on the variable.

**Comment by fsoepyan** [comment]
Given that there is a solution to this issue, I will close this issue.
