### ISSUE TITLE
OUU Module Extension

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#927]
It would be helpful to test the extension of OUU module with external simulators, since this capability would be required by few other projects.

**Comment by sotorrio1** [comment]
I don't understand what you mean by "OUU Module Extension".

**Comment by anujad95** [comment]
As a part of this effort, we need to test the following:
1. If the OUU module can be directly connected, and work with external simulator models like Aspen/MATLAB, without any issues. I think currently, it works only with equation oriented form of models, but will have to check again.
2. Accordingly, we will either continue testing the OUU module with Aspen/MATLAB models, if the capability already exists, or work on introducing/fixing it.

**Comment by lbianchi-lbl** [comment]
@anujad95 is testing a solution discussed with @sotorrio1. Depending on the outcome of the testing, this might be included in the Sept release.

**Comment by sotorrio1** [comment]
After @anujad95 and I discussed further this issue, we came up with a list of items we need to take care of:

- [ ] If the OUU module can be directly connected, and work with external simulator models like Aspen/MATLAB, without any issues. I think currently, it works only with equation oriented form of models, but will have to check again.

- [ ] Accordingly, we will either continue testing the OUU module with Aspen/MATLAB models, if the capability already exists, or work on introducing/fixing it.

- [ ] It would be nice to be able to save the OUU problem setup parameters the same way the user is able to do with other modules such as Flowsheet, UQ and Optimization.

**Comment by ksbeattie** [comment]
@boverhof is working on making a VM available for @sotorrio1 to work with.

**Comment by ksbeattie** [comment]
See PR #1028

**Comment by boverhof** [comment]
And issue #1025

**Comment by ksbeattie** [comment]
An example is described in PR #1033

**Comment by ksbeattie** [comment]
> After @anujad95 and I discussed further this issue, we came up with a list of items we need to take care of:
> 
>     * [ ]  If the OUU module can be directly connected, and work with external simulator models like Aspen/MATLAB, without any issues. I think currently, it works only with equation oriented form of models, but will have to check again.
> 
>     * [ ]  Accordingly, we will either continue testing the OUU module with Aspen/MATLAB models, if the capability already exists, or work on introducing/fixing it.
> 
>     * [ ]  It would be nice to be able to save the OUU problem setup parameters the same way the user is able to do with other modules such as Flowsheet, UQ and Optimization.

These are being worked thru in #1009

**Comment by ksbeattie** [comment]
@anujad95, give the work @boverhof did in the above, now merged, PRs is this issue resolved now?

**Comment by lbianchi-lbl** [comment]
@anujad95, let us know your thoughts on this and whether we should close it or move to the next release.

**Comment by ksbeattie** [comment]
I'm moving this to the Sept release since the June one is done now.

**Comment by ksbeattie** [comment]
@anujad95, I'm closing this given that it looks like this is working, at least for Aspen, but possibly not for Matlab.
