### ISSUE TITLE
Unknow error, could not upload sinter configuration file traceback 

### ISSUE THREAD

**Issue by jbernier040** [CCSI-Toolset/FOQUS#932]
I have an aspen simulation, from backup of this simulation I made a sinter file. This file was running correctly. However, after including new input variables in this file (sinter), I tried to update this file in foqus but I get this error (see image below), I can't update it and several copies of this file are also showing the same error when I try to open them from foqus. Could you please tell me the reason for this error and how can I fix it? Additionally I add the error message that I get in anaconda prompt

best regards

Atache file 1: Picture of foqus error
![Error foqus sinter file_1](https://user-images.githubusercontent.com/79927485/126169672-4ea46202-fb07-4456-887d-481a0fb6d7f5.png)

Attach file 2: anaconda prompt error 
[Error foqus sinter file_1_1.txt](https://github.com/CCSI-Toolset/FOQUS/files/6841395/Error.foqus.sinter.file_1_1.txt)

**Comment by boverhof** [comment]
First you might want to try and restart `Turbine` and then retry.

![Screen Shot 2021-07-20 at 12 58 09 PM](https://user-images.githubusercontent.com/738295/126387743-6a3636eb-2895-4dfe-aa80-b1ec60d960ff.png)


If that doesn't work, shutdown `Turbine` and remove the database by changing it's name then start `Turbine`.

**Comment by ksbeattie** [comment]
@jbernier040, did @boverhof's suggestion help?  Is this still an problem for you?

**Comment by ksbeattie** [comment]
@jbernier040, do let us know if this is still a problem.
