### ISSUE TITLE
Apparently insecure use of wildcards

### ISSUE THREAD

**Issue by leonardoviveiros** [CCSI-Toolset/FOQUS#934]
Our research team at Tenchi found some apparently insecure use of wildcards `(*)` in your Custom Lambda Authorizer. Precisely [here](https://github.com/CCSI-Toolset/FOQUS/blob/bc0458af79cf4c7b35840778d474209c0dfc8609/cloud/aws/node/http-basic-authorizer/index.js#L75). When you use wildcards anywhere in policies resources other than in the very end and after a slash, you're very likely to be allowing your users to access more API endpoints than you intended. This is because the wildcard `(*)` doesn't stop expanding at slashes `(/)`, as the AWS documentation stated up until very recently. For clarification, please check out our blog post about the subject at [Tenchi Security](https://www.tenchisecurity.com/blog/thefaultinourstars)

**Comment by boverhof** [comment]
Currently there is only 1 level of authorization, users have access to all resources.  In the future I may revisit.
