### ISSUE TITLE
Status Error UQ

### ISSUE THREAD

**Issue by MDCA960418** [CCSI-Toolset/FOQUS#939]
What does the status error in UQ really mean? Based on the manual when is not zero, it means the simulation converged. However, when placing the same inputs in to Aspen it actually converged, is this normal?

**Comment by sotorrio1** [comment]
@MDCA960418  Would you mind providing more information/screen shots of the error message and what you're trying to do?
Thank you!

**Comment by MDCA960418** [comment]
![image](https://user-images.githubusercontent.com/66323673/128258770-acbaaa09-5936-4955-b2f9-0bb77284638a.png)

There is no error message, just trying to understand the real meaning of the status error =2

**Comment by sotorrio1** [comment]
> What does the status error in UQ really mean? Based on the manual when is not zero, it means the simulation converged. However, when placing the same inputs in to Aspen it actually converged, is this normal?

What manual are you referring to?

**Comment by MDCA960418** [comment]
I meant to say when the status is  zero the simulation has converged. I found out this in the manual made in March 28, 2019

**Comment by MDCA960418** [comment]
Here is the manual https://readthedocs.org/projects/foqus-mine/downloads/pdf/latest/ 
Go to page 68

**Comment by sotorrio1** [comment]
@MDCA960418 So in the documentation only mentions the status = 0 means that it converged. The other status values I don't know what they mean. But in the tutorial is talking about the file “gmoat5012_9levels.res” that is an output of the Turbine Gateway, so perhaps @anujad95 has more insights on what those different status codes mean.

**Comment by MDCA960418** [comment]
@sotorrio1 @anujad95 In addition to this error, there is another one concerning graph.error value. It is understood that any value different than zero means no convergence in the simulation. However, when doing cross checking with the simulation (ACM) there are some runs that did actually converge and FOQUS is outputting graph.error==1

![image](https://user-images.githubusercontent.com/66323673/128422666-f3b158d8-6595-480d-b1a8-113d61c72740.png)

**Comment by sotorrio1** [comment]
@MDCA960418 I'm sorry but I'm not familiar with Aspen or Turbine simulations so I won't be of any help. I'm pretty sure @anujad95 will know more about this :)

**Comment by boverhof** [comment]
# Sinter Errors:
`sinter_ISimulation.cs`
2- WARNING

```
    public enum sinter_AppError
    {
        si_OKAY = 0,
        si_SIMULATION_ERROR = 1,
        si_SIMULATION_WARNING = 2,
        si_COULD_NOT_CONTACT = 3,
        si_UNKNOWN_FIELD = 4,
        si_INPUT_ERROR = 5,
        si_SIMULATION_NOT_RUN = 6,
        si_SIMULATION_STOPPED = 7,  //The user stopped the simulation
        si_STOP_FAILED = 8,         //The user tried to stop the sim, but the stop timed out.  Terminate should probably be called.
        si_COM_EXCEPTION = 100

    }

```

**Comment by anujad95** [comment]
The status code 2 indicates that the simulation has converged with warnings. In order to look into these warnings in detail, you could select the option for making the simulation visible in the node editor settings. This would open the Aspen simulation in the background as the FOQUS flowsheet runs, and it would be easier to see the warnings through it.

**Comment by ksbeattie** [comment]
@MDCA960418, were you able to see the warnings now?  Can we consider this issue closed?

Also, note that the docs you should be looking at are here: https://foqus.readthedocs.io/en/stable/

**Comment by MDCA960418** [comment]
yes, thank you.
