### ISSUE TITLE
UI Settings/Turbine Start Service PopUp String Format

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#958]
# Description
After starting Turbine the information window that pops up contains text that is incorrectly formatted.
![Screen Shot 2021-09-07 at 1 13 54 PM](https://user-images.githubusercontent.com/738295/132405741-607aab0d-f174-4a45-b38b-a25e64232714.png)

**Comment by lbianchi-lbl** [comment]
We should look into this more in detail to see if the same issue applies to other dialog boxes.
