### ISSUE TITLE
SDoE: NUSF Error

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#969]
When trying this in **NUSF**, I received weird errors upon selecting **Estimate Runtime**, which seem to be dependent on the design size I selected. I have no idea why NUSF is giving me errors and USF and IRSF ran fine with the exact same datasets. 

Clicking Estimate Runtime for design of size 6 (all else defaults) in **NUSF**:
<img width="955" alt="foqus-cands+prevdata-errorEstRuntime-nusf-size6" src="https://user-images.githubusercontent.com/55799605/135925895-c288f022-5313-434e-9a5e-86be63ddf4fb.png">

Just changed to size 5:
<img width="954" alt="foqus-cands+prevdata-errorEstRuntime-nusf-size5" src="https://user-images.githubusercontent.com/55799605/135925942-57b17bd9-b55c-4aa6-bee2-ac6ceb9404d4.png">

**Comment by ksbeattie** [comment]
@sotorrio1 is working with the LANL folks on this.

**Comment by jmorgan29** [comment]
I was working through an example for NUSF and found an error that seems similar to this, with slightly different syntax:
![NUSF error](https://user-images.githubusercontent.com/11306727/140406532-353a6e86-4e56-4256-941a-880e05be5f11.png)

I also found that the last line generally takes the form 'could not broadcast input array from shape(m,) into shape(m+n,) where m is the chosen design size and n is the number of observations in the 'previous data'. If no previous data are used for the NUSF design, this error does not show up when estimating the run time, and the design is generated properly.

**Comment by ksbeattie** [comment]
@sotorrio1 is going to work with @pn51 on this, given his past experience with the NUSF numpy-ificaiton.

**Comment by ksbeattie** [comment]
@sotorrio1, any progress on this?

**Comment by sotorrio1** [comment]
@ksbeattie I started working on it with @pn51 and we're meeting again this Thursday. Hopefully we get to a solution to this issue then.

**Comment by ksbeattie** [comment]
@sotorrio1, any new on this?  I think we were hoping to get a PR addressing this into the 3.12.0 release this week?
