### ISSUE TITLE
SDoE UX: Remove pop-up window when uploading a candidate set without missing values 

### ISSUE THREAD

**Issue by sspoon** [CCSI-Toolset/FOQUS#977]
Currently in the SDoE module, when you upload a candidate set with no missing values using the "Load Existing Set" button, a pop-up window appears like this after the file is uploaded:

<img width="534" alt="Screen Shot 2021-11-06 at 10 35 00 AM" src="https://user-images.githubusercontent.com/5075865/140802730-f48ed3fc-9782-47d0-8d25-c6dae9a6ff70.png">

This pop-up window is useful when there actually are missing values but is confusing when there are no missing values (notice the 0/2 on each row). It gives the impression that there might have been some kind of error when you uploaded your candidate file. Since it's more common that data imputation is not needed, I suggest dropping the pop-up entirely unless there are missing values. 

This issue was first reported by Miranda and Abby, and I agree with their suggestion of removing this pop-up when there are no missing values.

**Comment by sotorrio1** [comment]
@sspoon I can definitely change that. Thanks!

**Comment by sotorrio1** [comment]
@sspoon @mirandamartin PR #979 should handle this better :)
