### ISSUE TITLE
PSUADE error during UQ sample generation

### ISSUE THREAD

**Issue by bpaul4** [CCSI-Toolset/FOQUS#988]
When attempting to load an existing session and generate UQ samples using the flowsheet, a blank window prompt quickly flashes and disappears and no samples are generated. The error occurred in an environment without PSUADE installed, and in an environment with PSUADE installed after setting the location of the client executable. This issue occurred on more than one system (@bpaul4 and @MAZamarripa).

**Comment by sotorrio1** [comment]
@bpaul4 @MAZamarripa I need more details on this. Can you share the session file you're using? What are the steps you're following? Have you installed the latest psuade-lite (1.8.0) following the instructions in the "Optional Software" documentation section (https://foqus.readthedocs.io/en/stable/chapt_install/install_optional.html)?
Thanks!

**Comment by bpaul4** [comment]
It's a simple session file with 4 variables and min/max values. It is not connected to any simulation (i.e, Aspen, Excel) and the goal is to just generate samples from the flowsheet. The error occurred using the latest psuade-lite (1.8.0) on Windows.

**Comment by bpaul4** [comment]
@MAZamarripa and I tested creating new session files and were able to successfully generate UQ samples. We believe the issue may have been due to a version mismatch in FOQUS from saving and loading the session. We will continue to test new FOQUS sessions, but are closing this issue as the UQ/PSUADE tools are working as expected.
